### ISSUE TITLE
Folders cannot be Referenced by other Resources until Created

### ISSUE THREAD

**Issue by BrianPi** [GoogleCloudPlatform/k8s-config-connector#104]
The `cnrm.cloud.google.com/folder-id` annotation requires a folder number that isn't available until the folder has been successfully created. This means that deploying projects inside folders or folders in other folders requires first deploying parent folders and scraping them for a numeric ID.

**Comment by toumorokoshi** [comment]
Just a thought here: couldn't KCC theoretically scrape the folder id based off of a name? Or are collisions possible in that scenario?

**Comment by yashsaini77** [comment]
There is not much available regarding dependency between resources has anyone found it ?

**Comment by caieo** [comment]
@yashsaini77, as of now, you will need to create the folder to get the folder ID and it can't be referenced in a resource's annotation unless you are manually adding it in. This is something we are hoping to support in the future and will update this thread with developments.

**Comment by jcanseco** [comment]
Hi all, we've just added support for the ability to reference `Folder` resources from `Project` and `Folder` resources. Please see [this comment for details and the caveats to be aware of](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/349#issuecomment-807529809). Closing this issue to consolidate discussions in the other linked issue.
