### ISSUE TITLE
Add metricsGCPServiceAccountEmail to GKEHubFeatureMembership

### ISSUE THREAD

**Issue by ymmt2005** [GoogleCloudPlatform/k8s-config-connector#1054]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Config Connector configures GKE Hub's ConfigManagement custom resource with GKEHubFeatureMembership.
Config Management deploys an OpenTelemetry collector pod in `config-management-monitoring`
namespace that tries to put metrics to Cloud Monitoring, but unfortunately, it does not
have the necessary privileges by default.

To resolve this issue, ConfigManagement has a field metricsGCPServiceAccountEmail:
```yaml
              metricsGCPServiceAccountEmail:
                description: MetricsGCPServiceAccountEmail specifies a Google Service
                  Account (GSA) Email with the Monitoring Metric Writer (roles/monitoring.metricWriter)
                  IAM role. This GSA Email is used to annotate the `default` Kubernetes
                  ServiceAccount under the `config-management-monitoring` namespace,
                  which allows Config Sync to export metrics to Cloud Monitoring.
                type: string
```

However, GKEHubFeatureMembership does not have this field, so we can't configure this.
We'd like to have `metricsGCPServiceAccountEmail` in GKEHubFeatureMembership.

**Comment by diviner524** [comment]
This field is introduced in a recent PR.

https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1052

It didn't make it to our release this week but should be included in the next one, probably around mid Jan next year.

**Comment by ymmt2005** [comment]
Thank you!

**Comment by ymmt2005** [comment]
It seems v1.112.0 includes the fix and is already available on Google Cloud.
Thanks again for your quick work.

**Comment by diviner524** [comment]
@ymmt2005 Sorry for the confusion! The git tag in this GitHub repository is not accurately reflecting the things we released. The discrepancy stems from mirroring the code to our internal release pipeline with some mismatched steps, and the actual changes will be available in the next release.

We're actively working on adjusting the version tags in this GitHub repository to accurately reflect the released changes!

**Comment by ymmt2005** [comment]
oh, didn't know that. understood.
