### ISSUE TITLE
ContainerNodePool with GpuDriverVersion update call failing

### ISSUE THREAD

**Issue by dmeister** [GoogleCloudPlatform/k8s-config-connector#1062]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We are using config connector 1.112.0  and created a node group with an GpuDriverInstallationConfig block in GCP. The node group was correctly created. However, the status of the object is `UpdateFailed`.

```  
- lastTransitionTime: "2023-12-07T22:50:36Z"
    message: 'Update call failed: cannot make changes to immutable field(s): [Field
      Name: nodeConfig.0.GuestAccelerator.0.GpuDriverInstallationConfig.0.GpuDriverVersion,
      Got: latest, Wanted: LATEST]; please refer to our troubleshooting doc: https://cloud.google.com/config-connector/docs/troubleshooting'
    reason: UpdateFailed
```

The message shows up directly after the object was created. There was never an upgrade to that object before the error message showed up. Afterwards, any updated to the objects are no longer correctly synced with the GCP GKE node group.

I deleted the node group and recreated it with the same result.

The expected behavior is that any changed to the config connector object are reflected in the GKE node group. The expected behavior is that the status should be "successful".

### Additional Diagnostic Information

N/A

### Kubernetes Cluster Version

v1.27.7-gke.1121000

### Config Connector Version

0.112.0

### Config Connector Mode

cluster mode

### Log Output

- lastTransitionTime: "2023-12-07T22:50:36Z"
    message: 'Update call failed: cannot make changes to immutable field(s): [Field
      Name: nodeConfig.0.GuestAccelerator.0.GpuDriverInstallationConfig.0.GpuDriverVersion,
      Got: latest, Wanted: LATEST]; please refer to our troubleshooting doc: https://cloud.google.com/config-connector/docs/troubleshooting'
    reason: UpdateFailed

### Steps to reproduce the issue

- Created node group with gpuDriverVersion
- 

### YAML snippets

```YAML
nodeConfig:
    diskSizeGb: 100
    diskType: pd-balanced
    guestAccelerator:
    - count: 1
      gpuDriverInstallationConfig:
        gpuDriverVersion: latest
      type: nvidia-l4
```

**Comment by diviner524** [comment]
It seems the underlying GCP API is normalizing user input "latest" to "LATEST". Could you update your YAML to use "LATEST" and see if the error goes away?

You will need to delete/abandon the KRM resource first.

**Comment by dmeister** [comment]
It worked. Thank you. I didn't make the connection with `latest` vs `LATEST`.
