### ISSUE TITLE
IAMPolicyMember undeletable

### ISSUE THREAD

**Issue by Jonpez2** [GoogleCloudPlatform/k8s-config-connector#108]
I'm using configconnector to create a SpannerInstance and an IAMPolicyMember that grants access to that instance.  If I try to do a global cleanup (simply deleting the GCP project namespace), then the deletion gets stuck as it deletes the SpannerInstance before the IAMPolicyMember, resulting in the following Status:

Status:
  Conditions:
    Last Transition Time:  2020-03-10T09:23:55Z
    Message:               couldn't get resource config for resource reference: error retrieving resource 'project-xxx/spanner-instance-xxx' with gvk 'spanner.cnrm.cloud.google.com/v1beta1, Kind=SpannerInstance': spannerinstances.spanner.cnrm.cloud.google.com "spanner-instance-xxx" not found
    Status:                False
    Type:                  Ready

**Comment by Jonpez2** [comment]
Is there any extra detail I can give here to help narrow down the problem?  At the moment my only hackaround is to edit the k8s object and remove the finalizer.  This makes me unhappy...

Thank you!

**Comment by spew** [comment]
Hi @Jonpez2 thank you for reporting this issue. We are looking into fixing it and will report back when we have an update.

**Comment by Jonpez2** [comment]
great thank you!

**Comment by kibbles-n-bytes** [comment]
@Jonpez2 A fix for this is now in as part of 1.5.1. Going to close this issue; let us know if you continue to face any problems with this.

**Comment by Jonpez2** [comment]
OK great thanks
