### ISSUE TITLE
Unable to deploy Cloud SQL example

### ISSUE THREAD

**Issue by eranchetz** [GoogleCloudPlatform/k8s-config-connector#11]
I am following the how to [guide](https://github.com/GoogleCloudPlatform/k8s-config-connector#cloud-sql) for Cloud SQL with MYSQL in the README.md

But it seems I am missing some secret that’s preventing the musicians pod from starting:

`musicians-prod-7b7cd9bd89-27wnr   0/2     ContainerCreating   0          17m`

```
$ kubectl describe pod musicians-prod-7b7cd9bd89-27wnr
…
 FailedMount  43s (x18 over 21m)  kubelet, gke-traffic-director-clu-default-pool-ba1b383a-sldg  MountVolume.SetUp failed for volume "google-cloud-key" : secrets "gcp-key" not found
…
```

**Comment by kibbles-n-bytes** [comment]
Hey eranchetz,

You'll need to go through the [Sample App Prerequisites](https://github.com/GoogleCloudPlatform/k8s-config-connector#prerequisites-1) section first. This has you create the service account and key that get injected as the `gcp-key` secret.

**Comment by kibbles-n-bytes** [comment]
Going to close this out; feel free to open another issue if there's another error.
