### ISSUE TITLE
Storage Bucket names must be globally unique

### ISSUE THREAD

**Issue by lhopki01** [GoogleCloudPlatform/k8s-config-connector#12]
The sample app tries to create a storage bucket `storagebucket-sample` but bucket names need to be globally unique.  This will cause issues with anyone following the guide.

**Comment by kibbles-n-bytes** [comment]
Is this from a sample app or from the sample resources? I don't believe any of the sample apps use storage buckets, so following the guide should work.

That said, I do agree it's not great that the resource can't be created as is and the globally-unique aspect would mostly be discovered through an error. Would it feel more intuitive if we put a placeholder uniquifier in the name in the sample YAML that would fail kubectl validation and require editing the YAML to fix?

**Comment by lhopki01** [comment]
It's for the sample resources.  I think setting an invalid kubenetes yaml placeholder is the best solution.

**Comment by zarbis** [comment]
I've just stuck on that. Spent whole day troubleshooting permissions of cnrm-system service account. In theory I knew bucket names should be globally unique, but one is just not paying attention to such things when following guides...

**Comment by maqiuyujoyce** [comment]
Hi @zarbis, yes you're right, the error message does not make it very obvious what the true issue is, and we are sorry to hear that this issue has caused you the headache it has caused.

As @kibbles-n-bytes suggested, we can investigate changing our StorageBucket sample YAMLs to use a placeholder name to fail kubectl validation.

**Comment by caieo** [comment]
We've removed the sample app that was used a few years ago and have included a disclaimer in all `StorageBucket` samples to avoid this issue in the future. Due to the inactivity on this bug/action taken to avoid this in future samples, I'm going to close this bug. Feel free to re-open or file a new issue if needed.
