### ISSUE TITLE
CloudSQL disk automatic resize broken

### ISSUE THREAD

**Issue by n1koo** [GoogleCloudPlatform/k8s-config-connector#120]
Hi, 

with default settings like 

```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: foobar
spec:
    diskAutoresize: true
```

the DB is created and autoscaling works but when the autoscaling kicks in we dont read in the new changed disk size but rather try to enforce the default (10GB). Maybe the logic doesn't reflect 

```
༶ kubectl describe foobar                                                              
Name:        foobar
Namespace:    iam-sit
----
API Version:  sql.cnrm.cloud.google.com/v1beta1
Kind:         SQLInstance
Metadata:
  Creation Timestamp:  2020-02-27T18:06:37Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
  Generation:        53
  Resource Version:  116080732
  Self Link:         ---
  UID:               e5d7a5cd-598b-11ea-8934-42010a237c09
Spec:
  Database Version:  MYSQL_5_7
  Region:            us-east1
  Settings:
    Activation Policy:  ALWAYS
    Disk Autoresize:  true
    Disk Size:        10
    Disk Type:        PD_SSD
```

```
  Warning  UpdateFailed  8m20s (x85 over 18h)  sqlinstance-controller  Update call failed: the desired mutation for the following field(s) is invalid: [settings.0.diskSize]
```

At this point the actual size was `15GB` and if I manually changed the `diskSize` to match the value the resource would be happy again (not trying to mutate)

**Comment by n1koo** [comment]
I think this is just an example of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/62 btw

**Comment by xiaobaitusi** [comment]
Hi n1koo, thanks for reporting this issue. We will look into it and will update here when we have more information about the fix.

**Comment by n1koo** [comment]
Thanks, any update on this? We are starting to hit it more as config-connector is being rolled out

**Comment by xiaobaitusi** [comment]
Hi @n1koo, we are currently working on it, ETA of the fix is within the next two releases.Thanks.

**Comment by n1koo** [comment]
Thanks! If we can help to test anything or provide anything i'm happy to help out

**Comment by kibbles-n-bytes** [comment]
Hey @n1koo , 1.7.2 adds a patch for the following:

If the `spec.settings.diskAutoresize` is set, then `spec.settings.diskSize` will be synced to what Cloud SQL auto-updates it to, unless you explicitly have kubectl apply-d a particular `spec.settings.diskSize` value. If you previously `kubectl apply`'d an explicit value, you can remove it with `kubectl edit-last-applied` and then it will be synced with the auto-resized value.

We're planning a more generic feature across our resources to allow for fields to be designated as cloud-managed (with documentation at that time to match), but we hope this patch helps fix this particular issue. Please let us know if the patch fixes the immediate issue or if there's more work on our part to be done here.
