### ISSUE TITLE
Implement a ConfigConnector k8s operator to handle the complexity of uninstall/upgrade internally

### ISSUE THREAD

**Issue by Scorpiion** [GoogleCloudPlatform/k8s-config-connector#122]
New tracking issue created to better follow the proposed ConfigConnector k8s operator mentioned in comment in issue [#118](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/118#issuecomment-602323666). 

If you would like this, please add a :+1: to this message.

**Comment by maqiuyujoyce** [comment]
@Scorpiion Thank you for opening the issue. We plan to release an operator for KCC in May. Will let you know if there is any update.

**Comment by derekperkins** [comment]
cc @whizard

**Comment by ct-dh** [comment]
@maqiuyujoyce did the operator for KCC get created in May?

**Comment by maqiuyujoyce** [comment]
Yes, please refer to the [documentation](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#add-on) for installation.

**Comment by jcanseco** [comment]
Hi @ct-dh, thanks for checking in. Yes, we released an operator to manage KCC installations in May.

You can either:
1. Enable the KCC operator on GKE as an add-on: see how to install KCC via "Add-on" [here](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#add-on). The KCC add-on essentially uses the KCC operator under the hood.
2. Install the KCC operator by itself: see how to install KCC in "Namespaced-mode" [here](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#namespaced-mode).

Note that in both cases, you have to use [namespaced-mode](https://cloud.google.com/config-connector/docs/concepts/installation-types#namespaced_mode), which is an installation mode that allows you to manage multiple projects with multiple Google service accounts. This is in contrast with the more traditional [Google Cloud Identity](https://cloud.google.com/config-connector/docs/concepts/installation-types#identity) and [Workload Identity](https://cloud.google.com/config-connector/docs/concepts/installation-types#workload_identity) installation modes, in which KCC uses just one Google service account throughout the cluster (i.e. "cluster-mode").

Note that we are currently in the process of adding support for "cluster-mode" for the operator, which will make it easier to migrate from a Google Cloud Identity or Workload Identity installation if either of those is currently what you're using, but you can start using the operator today if you migrate to using namespaced-mode.

**Comment by toumorokoshi** [comment]
The operator has been released, and have also provided a [GKE addOn](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall) as the preferred mode of installation.

Both namespace and cluster mode are supported. Feel free to file a new issue if there are any questions or issues.
