### ISSUE TITLE
Incorrect instructions for installing in namespaced mode

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#125]
The [installation description for namespaced mode](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#installing_kcc) is currently broken. Step 3 in the section **Set up your namespaces** says to execute:

```
kubectl apply -n [NAMESPACE] -f install-bundle-namespaced/per-namespace-components-[NAMESPACE].yaml
```
The problem is the `-n` option. All resources in the file already have namespaces and different namespaces so it should just be removed.

**Comment by jcanseco** [comment]
Hi Mattias, thank you for bringing this up. We are actually in the middle of fixing our namespaced-mode installation instructions because they have some outdated steps as you've noted, and we are also working to make the instructions clearer as a whole.

I will keep this issue open for visibility and update you when the new docs are out.

**Comment by yhrn** [comment]
Hi Jazel,

Sounds good. If there are changes to the actual installation package it would be great if we are told so we can update our scripts. Tagging on a small improvement request here. If you are changing the package structure it would be great if you could separate out cluster scoped resources and resources in different namespaces into separate files. This would improve our installation process a lot since we could easily use `kpt live apply` config sync to install the different parts.

**Comment by jcanseco** [comment]
There shouldn't be any changes to the actual installation package as part of the namespaced-mode doc fixes, so that shouldn't be an issue.

> it would be great if you could separate out cluster scoped resources and resources in different namespaces into separate files. This would improve our installation process a lot since we could easily use kpt live apply config sync to install the different parts.

This, though, is an interesting suggestion; we'll look into it.

**Comment by jcanseco** [comment]
Updated Namespaced-mode installation instructions are now out, found [here](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall). Closing this issue.
