### ISSUE TITLE
GSA name for cnrm system in namespaced mode too long

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#126]
See [installation description for namespaced mode](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#installing_kcc). The GSA that needs to be created for each namespace follows the pattern `cnrm-system-[NAMESPACE]`, which is problematic since GSA names can only be 30 characters (bytes really) long. With the given prefix this breaks for any project with a name longer than 18 characters.

**Comment by kibbles-n-bytes** [comment]
Hey @yhrn , we are currently in the process of implementing an operator that would make the setup simpler and this recommendation not needed. For the time being, there is no technical limitation with using a different GSA, as long as the KSA's workload identity annotation (part of the `per-namespace-components` installation) is updated to the associated value. Here is an example of how to do so:

Replace the following command from the namespaced mode installation:
```bash
sed -e 's/${PROJECT_ID?}/[PROJECT_ID]/' \
-e 's/${NAMESPACE?}/[NAMESPACE]/' \
install-bundle-namespaced/per-namespace-components.yaml > install-bundle-namespaced/per-namespace-components-[NAMESPACE].yaml
```

with:

```bash
sed -e 's/${PROJECT_ID?}/[PROJECT_ID]/' \
-e 's/${NAMESPACE?}/[NAMESPACE]/' \
-e 's|iam.gke.io/gcp-service-account.*|iam.gke.io/gcp-service-account: [ACCOUNT_ID]@[PROJECT_ID].iam.gserviceaccount.com|' \
install-bundle-namespaced/per-namespace-components.yaml > install-bundle-namespaced/per-namespace-components-[NAMESPACE].yaml
```

(Replacing `[PROJECT_ID]`, `[NAMESPACE]`, and `[ACCOUNT_ID]` with the appropriate values)

**Comment by yhrn** [comment]
Yes, that is pretty much what we are doing already. I'm also aware of the operator that is being developed but I thought that it was still worth reporting this as it is a problem with the instructions right now and I assume not everybody will use the operator in the future.

**Comment by kibbles-n-bytes** [comment]
Sounds good. We plan to make the operator the main mode of installation of Config Connector even for the standalone offering, and the installation instructions at that time will loosen the naming constraint. We'll leave this issue open until that is in place.

**Comment by toumorokoshi** [comment]
Closing as [namespace mode](https://cloud.google.com/config-connector/docs/how-to/advanced-install#configure_to_watch_your_namespaces) supports arbitrary service account names. So it should be possible to keep service accounts under the 30 character limit.
