### ISSUE TITLE
chore:lint:ci enable misspell linter

### ISSUE THREAD

**Issue by acpana** [GoogleCloudPlatform/k8s-config-connector#1286]
Enable the misspell linter.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/542bafac48806735b15164f5abf66cb7a1aa299f/.golangci.yaml#L40

Advice to implementors:
* try to cap your work around ~< 50 file changes
* in this case, a few smaller PRs is better than one big PR

Steps to tackle this:
- turn on linter locally by uncommenting
- fix issues

**Comment by justinsb** [comment]
CC @anhdle-sso
