### ISSUE TITLE
need a cloudsql user resource

### ISSUE THREAD

**Issue by paulczar** [GoogleCloudPlatform/k8s-config-connector#13]
We need a resource to be able to create/delete cloudsql users (with passwords ideally settable via a secret) so that applications can connect to the database without needing a service account and the cloudsql-proxy configured and running.

**Comment by AlexBulankou** [comment]
Thanks @paulczar . We'll update this shortly with planned ETA for sql_user resource or any potential workarounds.

**Comment by AlexBulankou** [comment]
Enabled in 0.0.9.
