### ISSUE TITLE
bigtable storage and replication

### ISSUE THREAD

**Issue by thecloudgeek** [GoogleCloudPlatform/k8s-config-connector#130]
I don't see in the YAML [definition](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/resources/bigtableinstance/bigtable_v1beta1_bigtableinstance.yaml) for bigtable that one can specify storage and replication. Is that something thats possible?

**Comment by kibbles-n-bytes** [comment]
Hey @thecloudgeek, please refer to our reference documentation for the full list of fields we support: https://cloud.google.com/config-connector/docs/reference/resources#spec_5 . I believe `storageType` and `numNodes` are the fields you're looking for.

If not, could you please refer to specifically what you're trying to configure from the [underlying API's REST reference](https://cloud.google.com/bigtable/docs/reference/admin/rest)?

**Comment by thecloudgeek** [comment]
@kibbles-n-bytes I see storage type but not storage size though. In the UI, I can configure storge type and size, and also a replication.

**Comment by xiaobaitusi** [comment]
Hi @thecloudgeek, by replication, I think that it means to add a new cluster. However I couldn't find in the google cloud console how to configure the size. 
It seems that the underlying API's rest objects don't have such as a field like "size" per [Instance reference](https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances#Instance) and [cluster reference](https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.clusters#Cluster).
Can you specify how to configure the size via UI?

**Comment by thecloudgeek** [comment]
ah I see now...misread on my part....the storage option was just to estimate costs in the UI
