### ISSUE TITLE
SQLUser limited to a single database

### ISSUE THREAD

**Issue by n1koo** [GoogleCloudPlatform/k8s-config-connector#134]
When creating `SQLInstance`s with multiple `SQLDatabase`s it would be useful to be able to use `SQLuser` in a way where it references the `SQLDatabase` (eg. only access that).

So eg. `GRANT ALL PRIVILEGES ON `[Database]`.* TO '[username]'@'[IP or subnet]';` kinda thing

Anything like this in the roadmap?

**Comment by xiaobaitusi** [comment]
Hi @n1koo, I'm looking at the GCP SQL reference doc: https://cloud.google.com/sql/docs/mysql/create-manage-users#updating_users
It seems that the 'grant' command is not supported as the REST API now.

**Comment by n1koo** [comment]
Seem so indeed :(

Thats a shame as the alternative is to build external tooling that would run a container to manually run the commands.

**Comment by RonaldFindling** [comment]
FYI: I created a [feature request](https://issuetracker.google.com/issues/227942163) on the GCP SQL side to support grants as it would also be needed in this [related issue](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/641).
