### ISSUE TITLE
Optimize CNRM- pods CPU and memory resource requests

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#136]
As of v.1.7.0, Config Connector installs the following resources:

* CNRM controller manager: CPU: 100m, memory: 256Mi
* CNRM deletion defender: CPU: 100m, memory: 256Mi
* CNRM resource stats recorder: CPU: 50m, memory: 64Mi
* CNRM webhook manager: CPU: 100m, memory 128Mi

The latest addition is deletion defender that is requesting 100m, 256Mi. Is this required? Comparing with system level pods preinstalled on GKE cluster, I'm seeing that many of them (fluentd, prometheus-to-sd) are requesting much less. Can the requests be trimmed where not required?

**Comment by xiaobaitusi** [comment]
Hi @AlexBulankou, thanks for bringing it up. There might be some room to reduce the limit of CPU/memory usage. We will take a look at this issue and update the thread when we have more information.

**Comment by kibbles-n-bytes** [comment]
The limits for our non-controller workloads have been lowered as of 1.7.2, so closing this issue out.
