### ISSUE TITLE
Increase the number of replicas for deployment/statefulsets

### ISSUE THREAD

**Issue by cristifalcas** [GoogleCloudPlatform/k8s-config-connector#137]
Can I expect any problems if I modify the spec replicas for deployments and statefulsets?

I want to set it to 3, but not sure if the components are designed to work with this.

Is this going to cause any problems:
```
cnrm-controller-manager-0                       1/1     Running   0          23m
cnrm-controller-manager-1                       1/1     Running   0          23m
cnrm-controller-manager-2                       1/1     Running   0          23m
cnrm-deletiondefender-0                         1/1     Running   0          23m
cnrm-deletiondefender-1                         1/1     Running   0          23m
cnrm-deletiondefender-2                         1/1     Running   0          23m
cnrm-resource-stats-recorder-6f6d8bc488-28fqm   1/1     Running   0          23m
cnrm-resource-stats-recorder-6f6d8bc488-kd5qx   1/1     Running   0          23m
cnrm-resource-stats-recorder-6f6d8bc488-zqmrx   1/1     Running   0          23m
cnrm-webhook-manager-58985c88d9-2xhs8           1/1     Running   0          23m
cnrm-webhook-manager-58985c88d9-8rzzt           1/1     Running   0          23m
cnrm-webhook-manager-58985c88d9-s522x           1/1     Running   0          23m
```

**Comment by jcanseco** [comment]
Hi @cristifalcas, Config Connector's Deployments (`cnrm-resource-stats-recorder` and `cnrm-webhook-manager`) can indeed be scaled up, but the StatefulSets (`cnrm-controller-manager` and `cnrm-deletiondefender`) should have at most 1 replica each.

Can you maybe explain what problem you're trying to solve by scaling up the StatefulSets? Perhaps there is something we can help with here.

**Comment by cristifalcas** [comment]
I was trying to increase availability. But thinking about it, it's not a big deal for config-connector, since the resources that need to be created are done infrequent and the volume should be small.

So a loss for small periods of the manager shouldn't be critical.

**Comment by jcanseco** [comment]
> So a loss for small periods of the manager shouldn't be critical.

Yes you are correct. The `cnrm-controller-manager` pod will also reconcile newly created or recently updated resources eventually once it does come back online.

I'll be closing this issue now, though do let us know if you have any further questions or concerns.
