### ISSUE TITLE
need an iamserviceaccountkey resource for creating secrets containing credentials

### ISSUE THREAD

**Issue by paulczar** [GoogleCloudPlatform/k8s-config-connector#14]
I can create an IAM service account and policies, but I can't use it as part of an application without extra work.  We should allow the user to provide a namespace / secret to store the credentials json file that can be created for a service account.

see example here - https://github.com/paulczar/gcp-cloud-compute-operator/blob/master/pkg/controller/serviceaccountkey/serviceaccountkey_controller.go

**Comment by xiaobaitusi** [comment]
Hi Paul, thanks for the feedback. I agree with you on the native support to use service account key. We do a task to add service account key CRD which allows users to create a secret to store the credential key. The ETA is that it's going to come within next two releases.

**Comment by AlexBulankou** [comment]
@kibbles-n-bytes , can you please close when this addressed (I believe either in 0.0.8 or 0.0.9? )

**Comment by AlexBulankou** [comment]
It didn't make it into 0.0.9, but on track for 0.0.10. 
CC @kibbles-n-bytes @xiaobaitusi

**Comment by kibbles-n-bytes** [comment]
0.0.10 is now released, with `IAMServiceAccountKey` support, along with a controller to convert the GSA private key to a Kubernetes `Secret` for easily mounting into your pods.
