### ISSUE TITLE
Logging and Monitoring resources

### ISSUE THREAD

**Issue by gobins** [GoogleCloudPlatform/k8s-config-connector#144]
KCC does not support any logging or monitoring related resources at the moment for GCP.
https://cloud.google.com/config-connector/docs/reference/resources

We would like to see some basic resources like log metric and alerting policies which can be created using KCC.

**Comment by jcanseco** [comment]
Hi @gobins, when you say "log metric" and "alerting policies", am I correct to understand that you're requesting support for the following GCP resources?

* [`projects.metrics`](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics) (implemented in Terraform as [`google_logging_metric`](https://www.terraform.io/docs/providers/google/r/logging_metric.html))
* [`projects.alertPolicies`](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies) (implemented in Terraform as [`google_monitoring_alert_policy`](https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html))

**Comment by gobins** [comment]
Yes that is correct. Those are some examples, we would like to use Stackdriver for logging and monitoring. And would like to drive the creation of those resources through KCC.

**Comment by jcanseco** [comment]
Gotcha. 

> Those are some examples

Does this mean there are logging/monitoring-related resources you'd like to see supported other than the two I listed? If so, would you happen to know which ones?

**Comment by jcanseco** [comment]
For reference, you can find the list of REST resources corresponding to logging/monitoring-related GCP resources [here](https://cloud.google.com/logging/docs/reference/v2/rest), and Terraform implementations of some (or likely all) of these resources [here](https://www.terraform.io/docs/providers/google/) (on the left navigation bar, click "Filter" and enter "Stackdriver")

**Comment by jcanseco** [comment]
Hi @gobins, I'd just like to follow up on this. Would support for the two resources I mentioned above ([`google_logging_metric`](https://www.terraform.io/docs/providers/google/r/logging_metric.html) and [`google_monitoring_alert_policy`](https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html)) be sufficient for you, or are there other resources you'd like supported as well?

Also can you shed some light on how urgent this request is for you?

**Comment by gobins** [comment]
Yes those two resource would be sufficient for now. At this point the request is not urgent.

**Comment by jcanseco** [comment]
Great, thanks for clarifying!

**Comment by jcanseco** [comment]
Hi @gobins, we've just added support for the `MonitoringAlertPolicy` resource in KCC v1.30.0.

Will update this thread once we have support for `LoggingMetric`.

**Comment by tonybenchsci** [comment]
@jcanseco What about support for monitoring dashboards? https://cloud.google.com/blog/products/management-tools/cloud-monitoring-dashboards-using-an-api

**Comment by jcanseco** [comment]
Hey @tonybenchsci, yep monitoring dashboards is also in our backlog. We're currently targeting late Q1 to early Q2 for it.

**Comment by mathieu-benoit** [comment]
Indeed, having the equivalent of `google_monitoring_dashboard` with Terraform https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_dashboard would be really great.

**Comment by tonybenchsci** [comment]
@jcanseco Thanks, just checking in on logging resource support. I see that we can now use LoggingSinks (great!), we do have a pretty strong need for logging Metrics though; currently relying on manual Deployment Manager for LoggingMetrics

**Comment by xiaobaitusi** [comment]
Hi @tonybenchsci and @mathieu-benoit, those resources are in your backlog, we will let you know when you have more information.

**Comment by irvifa** [comment]
Will this also provided the access for Strackdriver metrics in KCC as well?

**Comment by jcanseco** [comment]
Hey @irvifa, could you please clarify what you mean? If you're looking for something like [`google_logging_metric`](https://www.terraform.io/docs/providers/google/r/logging_metric.html), then yes, that is currently on our backlog.

**Comment by irvifa** [comment]
@jcanseco yes I am, I’m also would like to know if it’s possible to use this requested feature to create alerting in stackdriver as well

**Comment by jcanseco** [comment]
Great, thanks for confirming.

On the second point, we do support a [`MonitoringAlertPolicy`](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringalertpolicy) resource today. Can you please see if that's the one you're looking for?

**Comment by irvifa** [comment]
@jcanseco great, I'll try to use it and find if it fits my need 👍

**Comment by ihaquekzHEqs24** [comment]
@jcanseco Does `monitoringMetricDescriptor` v1.58.0 include this?

**Comment by jcanseco** [comment]
Hi @ihaquekzHEqs24, yep, we released [MonitoringMetricDescriptor](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringmetricdescriptor) as part of KCC 1.58.0 (see [releases](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases)).

**Comment by tokatsu-gc** [comment]
I have a customer who would like to use the log based metric corresponding to google_logging_metric of terraform.
When will the log based metric be supported by Config Connector?

**Comment by maqiuyujoyce** [comment]
Hi @tokatsu-gc, currently the ETA for LoggingMetric is highly variable, but we're looking at late Q4 (October-December) as a tentative date.

**Comment by tokatsu-gc** [comment]
> Hi @tokatsu-gc, currently the ETA for LoggingMetric is highly variable, but we're looking at late Q4 (October-December) as a tentative date.

Will LoggingMetric is coming soon or Will it be some time in next year?

**Comment by mbzomowski** [comment]
Hi, it's still looking like it'll be added some time in the next year.

**Comment by jcanseco** [comment]
Hi all. From what I can see, it seems that all resources that have been requested in this thread are now supported in the latest version of Config Connector (v1.71.0):
* [LoggingLogMetric](https://cloud.google.com/config-connector/docs/reference/resource-docs/logging/logginglogmetric)
* [MonitoringAlertPolicy](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringalertpolicy)
* [MonitoringDashboard](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringdashboard)
* [MonitoringMetricDescriptor](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringmetricdescriptor)
* [MonitoringService](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringservice)
* [MonitoringServiceLevelObjective](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringservicelevelobjective)

Let us know if there's any that we missed.
