### ISSUE TITLE
[Compositions] Delete of CR didn't delete the resources that it owns

### ISSUE THREAD

**Issue by zicongmei** [GoogleCloudPlatform/k8s-config-connector#1483]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I created a resource group, AKS cluster and attached cluster in a composition. Then delete the CR of this composition, no resource is deleted.

### Additional Diagnostic Information

kubectl apply -f https://user.git.corp.google.com/zicong/kcc-alice/+/3277c4653e1463a08eee626f78d668347d19de5c/composition/

kubectl delete -f https://user.git.corp.google.com/zicong/kcc-alice/+/3277c4653e1463a08eee626f78d668347d19de5c/composition/

And the resources created by this CR remains undeleted.

### Kubernetes Cluster Version

N/A

### Config Connector Version

N/A

### Config Connector Mode

namespaced mode (default)

### Log Output

No related logs

### Steps to reproduce the issue

kubectl apply -f https://user.git.corp.google.com/zicong/kcc-alice/+/3277c4653e1463a08eee626f78d668347d19de5c/composition/

kubectl delete -f https://user.git.corp.google.com/zicong/kcc-alice/+/3277c4653e1463a08eee626f78d668347d19de5c/composition/

And the resources created by this CR remains undeleted.

**Comment by barney-s** [comment]
@zicongmei - Thanks for the bug. We have added a potential fix. Feel free to verify it from your side.
