### ISSUE TITLE
[Compositions] Add a tool to generate the CRDs for composition

### ISSUE THREAD

**Issue by zicongmei** [GoogleCloudPlatform/k8s-config-connector#1485]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

We shoudn't request user to write a CRD from scratch like https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/experiments/compositions/alice. That is too much work for them.

**Comment by barney-s** [comment]
https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1614
