### ISSUE TITLE
Deleting K8s cluster doesn't clean up GCP resources that were created

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#15]
- Enable Config Connector 0.0.7 on K8s cluster
- Create pubsubtopic resource
- Delete K8s cluster

Expected: pubsubtopic resource is deleted when the cluster is deleted
Actual: pubsubtopic resource is left behind orphaned

If this is expected behavior, I think it needs to be documented in the user guide. Currently the default behavior that is described, without abandon annotation is that underlying GCP resources are deleted when K8s resources are deleted.

**Comment by kibbles-n-bytes** [comment]
Unfortunately, there's not much we can do if the cluster is nuked. It depends on the Kubernetes provider whether they try to do any cleanup before just shutting the infrastructure off. This has been a problem on GKE as well, where it would leak load balancers on GCE if the user had any existing `Service`s of type `LoadBalancer`.

That said, agreed that documenting the actual behavior would be good!

**Comment by toumorokoshi** [comment]
Hi! I'm going to close this issue as the behavior described is common to anything using Kubernetes, and really generally applies to any control plane being deleted without proper cleanup.

If there's a behavior that's more specific to config connector that should be documented, please feel free to file a new issue.
