### ISSUE TITLE
Cannot create CloudBuildTriggerSample, unknown field "spec.github.repo"

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#154]
**Describe the bug**
Cannot create CloudBuildTriggerSample, unknown field "spec.github.repo"

**ConfigConnector Version**
1.7.2

**To Reproduce**
Run amples/resources/cloudbuildtrigger/build-trigger-for-github-repo/cloudbuild_v1beta1_cloudbuildtrigger.yaml sample from the installation package.

Error: admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.github.repo"

**Comment by jcanseco** [comment]
Ah yes, this is an error in our samples. Thanks for bringing it up. We'll put out a fix for the next release.

**Comment by jcanseco** [comment]
The correct field name to indicate a repo in this case should be `spec.github.name`.

**Comment by jcanseco** [comment]
Hi @AlexBulankou. This sample has been fixed in the `v1.8.0` release. I'll be closing this issue now.
