### ISSUE TITLE
Cannot create ComputeDisk sample, unknown field "spec.physical_block_size_bytes"

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#156]
**Describe the bug**
Cannot create ComputeDisk sample, unknown field "spec.physical_block_size_bytes"

**ConfigConnector Version**
1.7.2

**To Reproduce**
Run samples/resources/computedisk/regional-compute-disk/compute_v1beta1_computedisk.yaml sample from the installation package.

Error: admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.physical_block_size_bytes"

**Comment by caieo** [comment]
@AlexBulankou, this is an error with our samples. The field in the samples is: `spec.physical_block_size_bytes` but should be `spec.physicalBlockSizeBytes`. This will be fixed in the next release.

**Comment by jcanseco** [comment]
Hi @AlexBulankou. This sample has been fixed in the `v1.8.0` release. I'll be closing this issue now.
