### ISSUE TITLE
Cannot create computesubnetwork or computeinstancetemplate samples: unknown field "spec.enableFlowLogs"

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#157]
**Describe the bug**
Cannot create computesubnetwork or computeinstancetemplate samples: unknown field "spec.enableFlowLogs"

**ConfigConnector Version**
1.7.2

**To Reproduce**
Run samples/resources/computeinstancetemplate/compute_v1beta1_computesubnetwork.yaml
or run samples/resources/computesubnetwork/compute_v1beta1_computesubnetwork.yaml
from the installation package

Error: admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.enableFlowLogs"

**Comment by caieo** [comment]
@AlexBulankou, `enableFlowLogs` was removed in favor of `logConfig`. This sample will be fixed in the next release.

**Comment by AlienResidents** [comment]
> @AlexBulankou, `enableFlowLogs` was removed in favor of `logConfig`. This sample will be fixed in the next release. In the meantime, if this field is present in your YAML, please remove it. If `logConfig` is present flow logs are enabled.

Hi, the online documentation also provides  an example manifest that has `spec.enableFlowLogs` too.  Is this the right forum to have that documentation updated as well, or should I go somewhere else?

**Comment by jcanseco** [comment]
Hi @AlexBulankou. This sample has been fixed in the `v1.8.0` release. I'll be closing this issue now.
