### ISSUE TITLE
Support Artifact Registry

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/k8s-config-connector#158]
We would like to provision Artifact Registry repos and IAM with KCC

**Comment by derekperkins** [comment]
cc @whizard

**Comment by spew** [comment]
Hello @derekperkins, thank you for the request, we have added this to our list of resources to add to KCC.

**Comment by TravRan** [comment]
@spew Where are we at with this request?

**Comment by caieo** [comment]
Hi @TravRan, I'm currently working on this CRD. You can expect it sometime in the near future and we'll update this thread when it's out.

**Comment by eypher** [comment]
we're looking for this feature as well

**Comment by mbzomowski** [comment]
ArtifactRegistryRepository has been added: https://cloud.google.com/config-connector/docs/reference/resource-docs/artifactregistry/artifactregistryrepository
