### ISSUE TITLE
no matches for kind "PubSubSubscription" in version "pubsub.cnrm.cloud.google.com/v1alpha2"

### ISSUE THREAD

**Issue by barkatdhillon** [GoogleCloudPlatform/k8s-config-connector#17]
I have taken all the steps mentioned in [Prerequisite](https://github.com/GoogleCloudPlatform/k8s-config-connector#prerequisites-1)

when I execute apply command as mentioned at [Bookstore Sample](https://github.com/GoogleCloudPlatform/k8s-config-connector#kubernetes-microservice-application-backed-by-gcp-infrastructure---bookstore-sample), some deployment works fine, but for some, I get the following errors:
`kubectl apply -f samples/apps/bookstore/config/release-configuration.yaml`

Errors:

> service "booksfe" created
> service "inventory" created
> service "purchases" created
> service "users" created
> deployment.extensions "booksfe" created
> deployment.extensions "inventory" created
> deployment.extensions "purchases" created
> deployment.extensions "users" created
> unable to recognize "samples/apps/bookstore/config/release-configuration.yaml": no matches for kind "PubSubSubscription" in version "pubsub.cnrm.cloud.google.com/v1alpha2"
> unable to recognize "samples/apps/bookstore/config/release-configuration.yaml": no matches for kind "PubSubTopic" in version "pubsub.cnrm.cloud.google.com/v1alpha2"
> unable to recognize "samples/apps/bookstore/config/release-configuration.yaml": no matches for kind "SpannerInstance" in version "spanner.cnrm.cloud.google.com/v1alpha2"

**Comment by kibbles-n-bytes** [comment]
I can think of two things that could cause this:
- Config Connector was never installed. Could you confirm that the CRDs are listed in `kubectl get crds`? If no `[RESOURCE].[SERVICE].cnrm.cloud.google.com` CRDs exist, you'll need to run through the normal installation instructions [here](https://github.com/GoogleCloudPlatform/k8s-config-connector#instructions).
- You're on an older backwards-incompatible Config Connector version, and so the installed CRDs are out-of-date with respect to the YAML you're trying to apply. If this is the case, you'll need to delete Config Connector and re-install (note that deleting with delete all the GCP resources associated with Config Connector).

**Comment by barkatdhillon** [comment]
I downloaded the latest files which seems to be last updated on 30-Jul and 31-Jul, and redo normal installation as instructed in first point. Now I didn't get any error.
`kubectl get crds` I am getting following output now

> NAME                                                               CREATED AT
> backendconfigs.cloud.google.com                                    2019-08-07T13:44:57Z
> bigquerydatasets.bigquery.cnrm.cloud.google.com                    2019-08-07T14:15:34Z
> bigtableclusters.bigtable.cnrm.cloud.google.com                    2019-08-07T14:15:35Z
> bigtableinstances.bigtable.cnrm.cloud.google.com                   2019-08-07T14:15:35Z
> computebackendservices.compute.cnrm.cloud.google.com               2019-08-07T14:15:36Z
> computefirewalls.compute.cnrm.cloud.google.com                     2019-08-07T14:15:37Z
> computehealthchecks.compute.cnrm.cloud.google.com                  2019-08-07T14:15:37Z
> computenetworks.compute.cnrm.cloud.google.com                      2019-08-07T14:15:38Z
> containerclusters.container.cnrm.cloud.google.com                  2019-08-07T14:15:38Z
> iampolicies.iam.cnrm.cloud.google.com                              2019-08-07T14:15:39Z
> iamserviceaccounts.iam.cnrm.cloud.google.com                       2019-08-07T14:15:40Z
> kmskeyrings.kms.cnrm.cloud.google.com                              2019-08-07T14:15:40Z
> managedcertificates.networking.gke.io                              2019-08-07T13:45:29Z
> pubsubsubscriptions.pubsub.cnrm.cloud.google.com                   2019-08-07T14:15:41Z
> pubsubtopics.pubsub.cnrm.cloud.google.com                          2019-08-07T14:15:42Z
> redisinstances.redis.cnrm.cloud.google.com                         2019-08-07T14:15:42Z
> scalingpolicies.scalingpolicy.kope.io                              2019-08-07T13:45:29Z
> servicemappings.core.cnrm.cloud.google.com                         2019-08-07T14:15:43Z
> spannerinstances.spanner.cnrm.cloud.google.com                     2019-08-07T14:15:43Z
> sqldatabases.sql.cnrm.cloud.google.com                             2019-08-07T14:15:44Z
> sqlinstances.sql.cnrm.cloud.google.com                             2019-08-07T14:15:45Z
> sqlusers.sql.cnrm.cloud.google.com                                 2019-08-07T14:15:46Z
> storagebucketaccesscontrols.storage.cnrm.cloud.google.com          2019-08-07T14:15:46Z
> storagebuckets.storage.cnrm.cloud.google.com                       2019-08-07T14:15:47Z
> storagedefaultobjectaccesscontrols.storage.cnrm.cloud.google.com   2019-08-07T14:15:47Z

After running following command successfully, I still don't see PubSub topic/subscription and Spanner Instance
`$ kubectl apply -f samples/apps/bookstore/config/release-configuration.yaml`

> service/booksfe created
> service/inventory created
> service/purchases created
> service/users created
> deployment.extensions/booksfe created
> deployment.extensions/inventory created
> deployment.extensions/purchases created
> deployment.extensions/users created
> pubsubsubscription.pubsub.cnrm.cloud.google.com/cnrm-subscription created
> pubsubtopic.pubsub.cnrm.cloud.google.com/cnrm-topic created
> spannerinstance.spanner.cnrm.cloud.google.com/cnrm-instance created

when I checked Kubernetes -> Workloads, I see these errors for 2 
**booksfe**
ERROR: Required Pub/Sub topic "cnrm-topic" does not exist.

**inventory**
{ Error: 5 NOT_FOUND: Instance not found: projects/[PROJECT_ID]/instances/cnrm-instance at Object.exports.createStatusError (/inventory/node_modules/grpc/src/common.js:91:15) at Object.onReceiveStatus (/inventory/node_modules/grpc/src/client_interceptors.js:1204:28) at InterceptingListener._callNext (/inventory/node_modules/grpc/src/client_interceptors.js:568:42) at InterceptingListener.onReceiveStatus (/inventory/node_modules/grpc/src/client_interceptors.js:618:8) at callback (/inventory/node_modules/grpc/src/client_interceptors.js:845:24)

**Comment by kibbles-n-bytes** [comment]
The corresponding Kubernetes resources should say what their status is; i.e. if they were created successfully in GCP, and if not, why. Can you show the output of:

```
kubectl describe pubsubtopics
```

If that doesn't say what's going on, then confirm the controller is up by running the following:

```
kubectl describe pods -n cnrm-system
```

**Comment by kibbles-n-bytes** [comment]
Closing this out as it seems stale and due to an installation issue. Feel free to open a new issue if the problem is still occurring.
