### ISSUE TITLE
PromQL support for MonitoringDashboard

### ISSUE THREAD

**Issue by areyia** [GoogleCloudPlatform/k8s-config-connector#1749]
Hi, I recently discovered [MonitoringDashboard](https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringdashboard) and is something that we are looking into. Looking at the CRD, it appears that the only query language supported is the MQL, not promQL. The JSON model for the dashboard appears to have a distinction under 'timeSeriesQuery', via either 'prometheusQuery' or 'timeSeriesQueryLanguage', with only the latter supported via the CRD. Is this something that is already on the team's roadmap? This would be really useful for us to move all our dashboards from a 3rd party app into Cloud Monitoring. Thanks!

**Comment by davidcollom** [comment]
I needed this for this myself and it looks like this will be included within the 1.120.0 release: 

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/v1.120.0/scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md

**Comment by areyia** [comment]
Thanks, can confirm that this is now supported! Closing this issue.
