### ISSUE TITLE
Add mockgcp coverage for `sqlInstance` `settings.edition` 

### ISSUE THREAD

**Issue by yuwenma** [GoogleCloudPlatform/k8s-config-connector#1804]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

We are moving to the direction of using MockGCP to improve the KCC resource test coverage.  Related to #1802 

### Additional information

[MockGCP Guide](https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/mockgcp)
[Mock sql instance](https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/mockgcp/mocksql)

**Comment by jingyih** [comment]
The special behavior of `settings.edition` field is basically a bug. I don't feel it is worth the time to mimic that behavior in mock. Given that we already added #1823 to cover its behavior against real GCP API, I am going to close this one.
