### ISSUE TITLE
Possible to get the definition of an existing resource?

### ISSUE THREAD

**Issue by max-sixty** [GoogleCloudPlatform/k8s-config-connector#184]
There's a good description of how to start managing existing resources [here](https://cloud.google.com/config-connector/docs/how-to/managing-deleting-resources). 

But I'm unclear on whether there's an easy way to get the yaml that describes the resource: is the currently recommended way to write out the definition manually?

Thanks!

**Comment by max-sixty** [comment]
I think a duplicate of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/93

**Comment by spew** [comment]
Hello @max-sixty, you can try this out now. Documentation is [here](https://cloud.google.com/config-connector/docs/how-to/importing-existing-resources).

**Comment by max-sixty** [comment]
Thanks @spew!
