### ISSUE TITLE
Deploy Google Cloud Functions from Config Connector

### ISSUE THREAD

**Issue by saranicole** [GoogleCloudPlatform/k8s-config-connector#193]
We create Storage Buckets with Config Connector, and we use Google Cloud Functions as bucket monitors for those buckets.  Right now we have to add the monitors after the bucket creation, but it would be great if we could add the monitor with the bucket via Config Connector.  

If it roughly followed the Terraform pattern of using a storage bucket as a source that would work fine:

https://www.terraform.io/docs/providers/google/r/cloudfunctions_function.html 

Thanks!
Sara

**Comment by caieo** [comment]
Hi @saranicole, thanks for requesting this. I've marked it as a resource request and we will look into implementing it within a few weeks. We'll update this bug when it's supported.

**Comment by tonybenchsci** [comment]
@caieo Is there an expected date for Cloud Functions support?

**Comment by Cna59** [comment]
Is there any update on this resource request?

**Comment by jean-baptisteb** [comment]
+1

**Comment by rskrzypczak-adeo** [comment]
+1

**Comment by jordanngamba** [comment]
+1

**Comment by jcanseco** [comment]
Hi all, and apologies for missing your comment @tonybenchsci.

We're actively working on support for Cloud Functions, and we're currently targeting mid to late Q2.

**Comment by DWSR** [comment]
@jcanseco Hi there, it's almost Q3. Is there an update on the status of Cloud Functions support?

**Comment by jcanseco** [comment]
Hi @DWSR, the resource has been in active development, but there is still work that needs to be done. I'll see if I can get back to you with a more up-to-date ETA.

**Comment by jcanseco** [comment]
Hi @DWSR, unfortunately, it seems we probably won't be able to finish the leftover work required for this resource and get it released until Q4 or later due to lack of capacity.

If this resource is critical and time-sensitive for your use-cases, I encourage you to file a ticket with GCP support [here](https://cloud.google.com/support-hub).

**Comment by ihaquekzHEqs24** [comment]
Hi there, we're still looking forward to this functionality, seeing as how we are at the very cusp of Q4 beginning, can we get an update on the timeline, and if everything is in order for a Q4 delivery, and potentially, a higher-resolution ETA than "Q4"?

**Comment by jcanseco** [comment]
Hi @ihaquekzHEqs24, yes we're still aiming for Q4, but please note that given our lack of capacity, it might still slip to Q1. It's difficult to give a higher-resolution ETA at the moment unfortunately.

**Comment by red8888** [comment]
For more complex apps it would be amazing to deploy a regular k8s Deployment on GKE alongside a cloud function that interacts with it and describe them both in the same manifest. But what I'm really curious about is how this k8s resource will actually work- can you provide the initial broad strokes?

Is the cloud function k8s resource going to zip up and deploy packages to a GCS bucket too? Will the resource require a bucket and package to already exist and then you just point to it in the resource config? If its the later then how does my deployment work? Do I script out zipping up and copying the package to GCS and _then_ deploy my k8s manifest? Curious how you expect this resource to be leveraged by users.

**Comment by xiaobaitusi** [comment]
Hi @red8888,

Per [Cloud Function API documentation](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions), my read is that there are two ways to specify the source code. The first one is via a GCS bucket; as you mentioned as the latter, it requires users to upload the manifest to some GCS and then point to it the cloud function resource config. The second approach is to specify a source repository where a function is hosted.

**Comment by mnahkies** [comment]
If I'm not mistaken this is now supported: https://cloud.google.com/config-connector/docs/reference/resource-docs/cloudfunctions/cloudfunctionsfunction

**Comment by diviner524** [comment]
@mnahkies Yes it is supported. We are also looking into supporting Cloud Functions (2nd gen) in the coming months.
