### ISSUE TITLE
Manage Org Policies from Config Connector

### ISSUE THREAD

**Issue by TravRan** [GoogleCloudPlatform/k8s-config-connector#198]
**Describe the feature or the resource that you want.**
We would like to use Config Connector to manage our Org Policies.
A clear and concise description of what you want to happen
We would like to be able to able to bind org policies to our Organization, Projects, or Folders.

**Comment by caieo** [comment]
Hi @TravRan,
Thanks for requesting this feature, we'll look into supporting this. Any updates on this feature will be posted in this thread.

**Comment by jcanseco** [comment]
Hi @TravRan, we now support org policies in KCC 1.27.0 via the **ResourceManagerPolicy** resource.
