### ISSUE TITLE
Reference IAMPolicy from IAMPolicyMembers

### ISSUE THREAD

**Issue by TravRan** [GoogleCloudPlatform/k8s-config-connector#199]
**Describe the feature or the resource that you want.**
We would like it if there was a way to have IAMPolicyMembers reference IAMPolicy. 
A clear and concise description of what you want to happen
If IAMPolicyMembers could reference IAMPolicy maybe there would be a way to utilize IAMPolicy for strict enforcement, but still be able to add new IAMPolicyMember bindings. An example would be we deploy a GKE pattern. That pattern would add the Kubernetes Engine Service Agent plus our custom GSA bindings. The new bindings are added to the IAMPolicy, and we are still strictly enforcing our IAMPolicy.

**Comment by caieo** [comment]
Hi @TravRan,
Thanks for requesting this enhancement and providing a helpful scenario for us to better understand why this is necessary. We will look into supporting this and will post any updates in this thread.

**Comment by xiaobaitusi** [comment]
Hi all,

KCC now supports IAMPartialPolicy represents a non-authoritative intent for the associated Google Cloud resource's IAM policy. The specified bindings will be merged together with any existing bindings and audit configs.

Note that IAMPartialPolicy CRD supports inline modification to add/remove/modify role bindings, please give it a try and let us know if you run into any issue.

Thanks

**Comment by xiaobaitusi** [comment]
Closing this since https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampartialpolicy is released
