### ISSUE TITLE
How to customize  

### ISSUE THREAD

**Issue by axot** [GoogleCloudPlatform/k8s-config-connector#20]
It is great so we can manage gcp resource via these CRDs, one question here is, because all these operators are not open source, is it possible to customize, for example, after creating MemoryStore instances, we also want assign a DNS record for each instance, how to achieve this?

**Comment by nrobert13** [comment]
:+1: for DNS support

**Comment by xiaobaitusi** [comment]
Hi all, I'm not familiar with the concept of DNS assignments. Can you give us more context or details about it? What is your typical use case? Thanks.

**Comment by xiaobaitusi** [comment]
Further follow-ups: we currently don't support DNS yet, though it's planned for future resource coverage. As for assigning DNS record, we now don't have any generic approach for field valuing snitching. There are to possible ways to achieve this: 1) use 'kubectl wait --field-selector' to ensure 'host' is populated from underlying API and 'kubectl apply' the DNS resource with the ip address value extracted. There would be two steps in your deployment pipeline. 2) write your own controller to watch MemoryStore Instance CRD for the 'host' value and generate a DNS CR object once it's populated.

**Comment by axot** [comment]
Hi @xiaobaitusi, Thanks for the tips!
