### ISSUE TITLE
Audit logs

### ISSUE THREAD

**Issue by max-sixty** [GoogleCloudPlatform/k8s-config-connector#200]
Would it be possible to add Audit Logs configuration (i.e. https://console.cloud.google.com/iam-admin/audit) to the resources that config connector can manage?

**Comment by caieo** [comment]
Hi @max-sixty, thanks for making this resource request. We'll look into supporting this resource soon!

**Comment by spew** [comment]
This is now available as a granular resource, `IAMAuditConfig` in version 1.21.1. We will soon be adding it to the `IAMPolicy` resource as well.
