### ISSUE TITLE
Support Config Connector Addon in ContainerCluster Ressource

### ISSUE THREAD

**Issue by sbrunk** [GoogleCloudPlatform/k8s-config-connector#203]
I'm trying to bootstrap a Config Connector enabled cluster completely via Config Connector itself (running in another cluster).

Now I'm running into an issue early on: It seems that it's currently not possible to enable the addon on the ContainerCluster resource. As you certainly know, the feature is available in [beta API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.AddonsConfig).

Is this something that could be added to the ContainerCluster resource definition?

**Comment by toumorokoshi** [comment]
Closing this issue as we now support the ConfigConnector addOn config in the container cluster:

https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster

Please re-open or file a separate issue if you find any additional issues. Thanks for waiting!
