### ISSUE TITLE
how can i reference a resource output  

### ISSUE THREAD

**Issue by ni-ezakaria** [GoogleCloudPlatform/k8s-config-connector#205]
Hi 

is it possible to reference a resource output . for example when you create a compute address, i would like to take this IP and link it to a DNS A record resources

**Comment by kibbles-n-bytes** [comment]
Hey @ni-ezakaria , we don't support arbitrary field stitching between our resources. However, the IP address -> DNS case comes up enough that we are looking into adding support for this case. Is there any other situation in which this stitching is necessary?

**Comment by ni-ezakaria** [comment]
@kibbles-n-bytes  many thanks for your reply , well this is the only drawback so far in my use case . 
Probably support for secrets manager will be great addition.  along with making kcc a managed service will make it the best gcp infrastructure solution. 
But honestly great work guys :)

**Comment by kibbles-n-bytes** [comment]
Aww, thanks a lot! 😄

**Comment by toumorokoshi** [comment]
I'm going to close this issue as the question was answered. Please feel free to file additional issues for specific use cases / requests.

Regarding IP into DNS recordset: this is a duplicate of #101.
