### ISSUE TITLE
cnrm-controller-manager cannot schedule pods for long namespace names

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#209]
**Describe the bug**
We are using the GKE addon to install Config Connector and for long namespace names the stateful set that gets created for the namespace cannot schedule its Pod because it gets a label with a too long value so it is forever stuck on zero replicas.

**ConfigConnector Version**
1.9.1

**To Reproduce**
Create a namespace with a long enough name, 30 characters will be enough, in a cluster with the ConfigConnector addon and create a ConfigConnectorContext in this namespace.

Describe the StatefulSet `cnrm-controller-manager-your-long-namespace-name` in the `cnrm-system` namespace, it will have an event describing the problem:

```
Warning    FailedCreate   9m40s (x93 over 21h)    statefulset-controller
create Pod cnrm-controller-manager-storage-declarative-playground-0 in 
StatefulSet cnrm-controller-manager-storage-declarative-playground failed error:
Pod "cnrm-controller-manager-storage-declarative-playground-0" is invalid: 
metadata.labels: Invalid value: "cnrm-controller-manager-storage-declarative-playground-69448ff666": 
must be no more than 63 characters
```

**Comment by AlexBulankou** [comment]
Thanks @yhrn  for reporting. We are investigating. Do you currently have a workaround?

**Comment by spew** [comment]
Hi @yhrn while we work on a long term fix to enable any namespace length, do you know the length of your longest namespace that you wish to use with KCC right now?

**Comment by yhrn** [comment]
Right now the longest project id/namespace name we have is 30 characters (it breaks at 29 characters) but it is really out of our control since anything that is a valid project id can show up at any time. We have gone with the strict convention that project id = namespace name and it would not be feasible for us to change that as a short term workaround.

**Comment by AlexBulankou** [comment]
@yhrn , immediate workaround available would be not to use GKE add-on, but instead [use standalone installation with namespace mode](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#namespaced-mode) and manually shorten in `install-bundle-namespaced/per-namespace-components.yaml` prior to installing. 
We'll follow up separately during our syncs on GKE addon fix ETA. (CC @soellman)

**Comment by yhrn** [comment]
Back to work now after a couple of days off - I don't switching back to manual installation is a feasible short term workaround, but we can discuss that at the sync.

**Comment by xiaobaitusi** [comment]
Hi @yhrn ,
The standalone operator of version 1.13.0 can support long namespace names now. Note that per each namespace, the operator generate a uuid for it and controller manager statefulset/service/pod now are named using the uuid as the suffix. You can use label "cnrm.cloud.google.com/scoped-namespace=[NAMESPACE]" to distinguish them. 

You can follow the instruction here https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#namespaced-mode to use the operator for namespaced mode. The GKE addon will have the fix within 3 weeks.

Thanks

**Comment by yhrn** [comment]
Thanks, we are currently blocked on upgrading because of #222 but once there's a version where that is fixed we'll try this out.

**Comment by toumorokoshi** [comment]
Hi! I'm going to close this issue as we have released a fix on our side, but please re-open if you find that it doesn't solve your issue.
