### ISSUE TITLE
list of possible values for status.conditions.reason (for type: Ready)

### ISSUE THREAD

**Issue by jlgeering** [GoogleCloudPlatform/k8s-config-connector#211]
We are using config connector together with ArgoCD, which has the concept of custom health checks (basically you can map a status to a color / icon by writing a lua snippet). For the our config-connector resources we currently have the following:

for the config connector config
```
    core.cnrm.cloud.google.com/ConfigConnectorContext:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.healthy == true then
            hs.status = "Healthy"
            hs.message = ""
            return hs
          end
        end
        hs.status = "Progressing"
        hs.message = ""
        return hs
```
 
for most (all?) resources listed [here](https://cloud.google.com/config-connector/docs/reference/overview)

```
    <%= name %>:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "False" and condition.reason == "Updating" then
                hs.status = "Progressing"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "False" and condition.reason == "DependencyNotFound" then
                hs.status = "Progressing"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end
        hs.status = "Progressing"
        hs.message = ""
        return hs
```

(posted the full snippet in case someone comes across this question and wants to do some copy-pasta)

i.e. based on trial and error, we have found these values for status.conditions.reason: `DependencyNotFound` `Updating` and `UpToDate` and the documentation (e.g. https://cloud.google.com/config-connector/docs/reference/resource-docs/storage/storagebucket#status) only says _Unique, one-word, CamelCase reason for the condition's last transition._

Do these value come from config connector, and if yes, where are they documented? Or do they come from the underlying apis ... and if yes, where can we find the documentation :-)

**Comment by jlgeering** [comment]
and somewhat related: it seems like most (all?) resources follow the same pattern when it comes to status / conditions => is this assumption correct? i.e. is there a way to get an overview of the different "types" of status / conditions?

**Comment by AlexBulankou** [comment]
@jlgeering , this is the behavior that we follow today - the table below shows the possible conditions and the state in the resource lifecycle it represents. 
This behavior can change at any time and without notice and this post will not be kept up to date with the latest behavior. However this may be helpful to you today for building your custom health checks.

Going forward, we'll look into documenting the resource lifecycle transitions.
 
<table>
  <tr>
   <td>Creating resource
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "Update in progress" <br/>
    reason: "Updating" <br/>
    status: "False" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Created resource
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "The resource is up to date" <br/>
    reason: "UpToDate" <br/>
    status: "True" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Create failed
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "Update call failed: %v" <br/>
    reason: "UpdateFailed" <br/>
    status: "False" <br/>
    type: "Ready"  
<p>
  ]  
   </td>
  </tr>
  <tr>
   <td>Updating resource
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "Update in progress" <br/>
    reason: "Updating" <br/>
    status: "False"
<p>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Updated resource
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "The resource is up to date" <br/>
    reason: "UpToDate" <br/>
    status: "True" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Update failed
   </td>
   <td>status:
<p>
  conditions: [
<p>
lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
message: "Update call failed: %v" <br/>
reason: "UpdateFailed" <br/>
status: "False" <br/>
type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Deleting resource
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "Deletion in progress" <br/>
    reason: "Deleting" <br/>
    status: "False" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Deleted resource
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "Successfully deleted" <br/>
    reason: "Deleted" <br/>
    status: "False" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Delete failed 
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "Delete call failed: %v" <br/>
    reason: "DeleteFailed" <br/>
    status: "False" <br/>
    type: "Ready" <br/>
  ]
   </td>
  </tr>
  <tr>
   <td>Dependency Not Ready
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "reference %v %v is not ready" <br/>
    reason: "DependencyNotRead" <br/>
    status: "False" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Dependency Not Found
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "reference %v %v is not found" <br/>
    reason: "DependencyNotFound" <br/>
    status: "False" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
  <tr>
   <td>Dependency Invalid
   </td>
   <td>status:
<p>
  conditions: [
<p>
    lastTransitionTime: &lt;yyyy-mm-ddT00:00:00> <br/>
    message: "key %v was not found in secret %v" <br/>
    reason: "DependencyInvalid" <br/>
    status: "False" <br/>
    type: "Ready"
<p>
  ]
   </td>
  </tr>
</table>

**Comment by jlgeering** [comment]
@AlexBulankou this is perfect, thank you

(and yes, having this be part of the public / documented api or in the changelog in the future would be great)
