### ISSUE TITLE
Include severity in cnrm-controller-manager log output

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#216]
Currently all cnrm-controller-manager (manager container) logs show up as errors in Cloud Logging, by including "severity" in the log output this could be remediated. For example:

```json
{"level":"info","severity":"INFO","ts":1592985320.2246182,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"spannerdatabase-controller"}
```
instead of

```json
{"level":"info","ts":1592985320.2246182,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"spannerdatabase-controller"}
```

**Comment by spew** [comment]
Thank you for reporting this, noted and added to our backlog.

**Comment by caieo** [comment]
Hi @yhrn, release 1.21.0 ([notes here](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.21.0)) should now support "severity" in our logs. Please re-open this issue if this does not work for you.
