### ISSUE TITLE
Support GKE Dataplane V2

### ISSUE THREAD

**Issue by errordeveloper** [GoogleCloudPlatform/k8s-config-connector#217]
I was wondering how could one use `gcloud beta` and  `gcloud alpha` equivalents in Config Connector, I'm hoping it's possible since the concepts seem quite generic to Google APIs.

**Comment by spew** [comment]
Hi @errordeveloper we do support some beta features in config connector. Can you let us know if there are any specific alpha / beta APIs or features that you want access to?

**Comment by errordeveloper** [comment]
Hi @spew, thanks for prompt response!

I was generally thinking whether alpha/beta API could be consumed in the same way `gcloud alpha`/`gcloud beta` works. I was searching the docs and couldn't quite tell.

The specific feature I would be looking to use is the equivalent of `gcloud alpha container clusters create  --datapath-provider=advanced`.

**Comment by spew** [comment]
Hi @errordeveloper, under the hood we use a mixture of GA and beta APIs. We can also add an alpha feature if there is desire for it.

I don't see the `datapath-provider` option on this page: https://cloud.google.com/sdk/gcloud/reference/alpha/container/clusters/create?hl=de

Is this something you opted into?

**Comment by errordeveloper** [comment]
@spew 
> I don't see the datapath-provider option on this page... Is this something you opted into?

Sounds like this could be some sort of opt-in, didn't know API features can be exposed as `gcloud` flags, I wonder if somehow Config Connector could provide a dynamic mode of sorts.

> under the hood we use a mixture of GA and beta APIs. We can also add an alpha feature if there is desire for it.

I guess it would make sense if it worked similarly to `gcloud`, e.g. with something like `ContainerClusterBeta`  and ` `ContainerClusterAlpha`, or in fact via `apiVesion` actually. I thought that alpha/beta APIs were defined as separate REST endpoints, at least that seems like what `gcloud` suggest (assuming `gcloud` actually mirrors the API). But from what you are saying, it sounds like alpha/beta features are fields within stable API object? (as if those were separate endpoints, using a mixture would be less trivial, especially in context of something like Config Connector, where most code is probably generated).

**Comment by spew** [comment]
Hi @errordeveloper it could work as you describe with different config connector CRD API versions mapping to different GCP api versions. If there is enough interest we can / could do that. That is a good suggestion. 

There are significant features that many customers use that are in beta, hence why we use a mixture of GA and beta right now.

**Comment by errordeveloper** [comment]
Hey @spew!

I don't have a direct need for full-on `gcloud beta` and  `gcloud alpha`  equivalents, but it would make sense if there was a clear mapping between CNRM object and the alpha and beta APIs.

The one feature I'd like to be able to use is [GKE Dataplane V2](https://cloud.google.com/blog/products/containers-kubernetes/bringing-ebpf-and-cilium-to-google-kubernetes-engine).

**Comment by caieo** [comment]
Hi @errordeveloper , 

For supporting GKE Dataplane V2, it looks like our CRDs are a little behind, but should be supporting them in an upcoming release. I'll update this thread when the feature is added, but in the future, you can open a feature request to ask for feature support. 

As for actually using it, taking a quick look at the API tab of this section https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy-logging#create-cluster shows how you might set up your YAML config so that Dataplane V2 is enabled.

**Comment by toumorokoshi** [comment]
Hi! I'm going to update this ticket to the current topic (Support GKE Dataplane V2) for some light cleanup.

**Comment by jetersen** [comment]
the gcloud cli is currently supporting it via `--enable-dataplane-v2` and CRDs are missing this option at the moment 😅

**Comment by mathieu-benoit** [comment]
FYI: `datapathProvider: ADVANCED_DATAPATH` on [`ContainerCluster`](https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster) allows to enable the GKE Dataplane V2.

**Comment by jetersen** [comment]
Thanks @mathieu-benoit that did the trick, had to ensure I disabled the networkPolicy

```
datapathProvider: ADVANCED_DATAPATH # Dataplane v2
networkPolicy:
    enabled: false # using Dataplane v2 which provides network policy
```

**Comment by jetersen** [comment]
Properly another issue but.

ConfigConnector is trying to update the object after being deployed and seems to throw the same condition I experienced when networkPolicy was enabled.

```
status:
  conditions:
    - lastTransitionTime: '2022-02-24T22:49:22Z'
      message: >-
        Update call failed: error applying desired state: summary: googleapi:
        Error 400: Enabling NetworkPolicy for clusters with
        DatapathProvider=ADVANCED_DATAPATH is not allowed., badRequest
      reason: UpdateFailed
      status: 'False'
      type: Ready
```

Status should be update to date as I had not touched the config since deploying it.

**Comment by xiaobaitusi** [comment]
Hi @jetersen, let's use the other issue https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/616 to to diagnose the update failed issue.

This particular issue is asking for GKE dataplane v2 support via KCC. Per https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/217#issuecomment-1050300839, this is already supported. Thanks @mathieu-benoit for sharing the knowledge. We will consider adding a sample to make it intuitive around how to set up a GKE cluster with dataplane v2.
