### ISSUE TITLE
Support RetryPolicy on PubSubSubscription

### ISSUE THREAD

**Issue by jonaslindmark** [GoogleCloudPlatform/k8s-config-connector#218]
I would love to be able to configure the [RetryPolicy](https://github.com/googleapis/java-pubsub/blob/master/proto-google-cloud-pubsub-v1/src/main/proto/google/pubsub/v1/pubsub.proto#L749) on a PubSubSubscription. Is there any way we can expose that option here?

**Comment by spew** [comment]
Hi @jonaslindmark thank you for requesting this feature, we have noted it and added it to our backlog.

**Comment by x4d3** [comment]
Hello, I would like that too pretty please. It would be neat and grand !

**Comment by spew** [comment]
RetryPolicy is now available in version `1.21.1.
