### ISSUE TITLE
Unable to delete non-empty StorageBucket

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#22]
Even though the we set `forceDestroy: true` in the `spec` deletion fails. In the cnrm-controller-manager logs we can see that it's failing to set the corresponding flag for the delete request.

**Comment by kibbles-n-bytes** [comment]
This behavior should now work. Please try using the following annotation on your `StorageBucket` resource:
```yaml
annotations:
  cnrm.cloud.google.com/force-destroy: "true"
```
Please let me know if you're still seeing issues even with this annotation.
