### ISSUE TITLE
Support for Log Sinks / Exports

### ISSUE THREAD

**Issue by jsun6383** [GoogleCloudPlatform/k8s-config-connector#224]
Log sink / export is an important part of the logging & monitoring eco-system. We are looking at a number of use cases with log sinks / exports. 

I would like to request support for creating log sinks / exports resources through config-connector.

**Comment by xiaobaitusi** [comment]
Hi @jsun6383, thanks for making the resource requests. Just to clarify your use cases, do you refer to the following resources?(I'm using terraform resources for comparison)
google_logging_billing_account_sink
google_logging_folder_sink
google_logging_organization_sink
google_logging_project_sink

**Comment by jsun6383** [comment]
hi @xiaobaitusi, yes that is correct. The only exception is `google_logging_billing_account_sink` which we currently do not have a use case for.

**Comment by xiaobaitusi** [comment]
Thanks for the clarification. We've added them to the list of resources that we're looking into and will let you know when we have more information.

**Comment by jcanseco** [comment]
Log sinks for projects, folders, and organizations are now supported in KCC 1.27.0 via the `LoggingLogSink` resource.
