### ISSUE TITLE
Resource request: CRD for Dataproc workflow templates

### ISSUE THREAD

**Issue by tonybenchsci** [GoogleCloudPlatform/k8s-config-connector#225]
**Describe the feature or the resource that you want.**
GCP Dataproc workflow templates can be used to instantiate workflows. 
Since workflow templates define GCP infra and GCE usage, KCC should support this. 
The usage is to create dataproc workflow templates using KCC, and then using KCC to define IAM to grant groups/users permissions to instantiate workflow jobs.

Ref: https://cloud.google.com/dataproc/docs/concepts/workflows/using-workflows?_ga=2.268542961.-1021085820.1562077551

**Comment by xiaobaitusi** [comment]
hi @tonybenchsci, thanks for making the resource request. We've added it to the list of resources we're looking into and will let you know when we have more information.

**Comment by jcanseco** [comment]
Closing as this has been implemented in KCC.
