### ISSUE TITLE
Support for Cloud Monitoring Uptime Checks

### ISSUE THREAD

**Issue by stevewww** [GoogleCloudPlatform/k8s-config-connector#226]
**Describe the feature or the resource that you want.**
I would like to attach Uptime checks to Services and then apply Alerting Policy to the Uptime check. 

Alerting policy has been raised here: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/144

Uptime checks would satisfy the use case of deploying a Service, and then attaching an Uptime check to the URL associated with the Ingress/LB. 

The Uptime check resource is described here: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs

**Comment by xiaobaitusi** [comment]
Hi @stevewww, thanks for making the resource request. We've added it to the list of resources we're
looking into and will let you know when we have more information.

**Comment by maqiuyujoyce** [comment]
Hi @stevewww  , `MonitoringUptimeCheckConfig` has been released in [1.70.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.70.0).
