### ISSUE TITLE
Naming requirements for k8s objects and GCP objects are different

### ISSUE THREAD

**Issue by ssmall** [GoogleCloudPlatform/k8s-config-connector#229]
# Describe the bug
I see the following when trying to create a backend bucket with a valid (Kubernetes) name:
```yaml
Events:
  Type     Reason        Age                   From                             Message
  ----     ------        ----                  ----                             -------
Warning  UpdateFailed  62s (x15 over 3m14s)  computebackendbucket-controller  Update call failed: error fetching live state: error reading underlying resource: Error when reading or editing ComputeBackendBucket "projects/redacted/global/backendBuckets/test.example.com-backend-bucket": googleapi: Error 400: Invalid value for field 'backendBucket': 'test.example.com-backend-bucket'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}', invalid
```

# ConfigConnector Version
1.13.1

# To Reproduce
I am attempting to create the following resource:

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendBucket
metadata:
  name: test.example.com-backend-bucket
spec:
  bucketRef:
    name: redacted
  description: contains a reference to a bucket for use with HTTP(S) load-balancing
```

via `kubectl apply`.

**Comment by ssmall** [comment]
The reason I think this should be considered a bug is because of the following expectation: as a user, the way that Config Connector transforms the k8s object name into a GCP resource name is completely opaque to me. If there are restrictions on valid names, I would expect one of the following scenarios to be true:

1. `kubectl apply` fails when `metadata.name` is not valid for the underlying GCP resource
2. I am required to specify `spec.name`, which validates against the naming requirements for the GCP resource I am trying to create.
3. Config Connector automatically generates a valid name for the underlying GCP resource

**Comment by xiaobaitusi** [comment]
Hi @ssmall , thanks for reporting the issue. 
We plan to add the resource name override feature to allow users to specify `spec.resourceName` (the field name is TBD) when they don't want to use or cannot use metadata.name to name the resource.

> kubectl apply fails when metadata.name is not valid for the underlying GCP resource

This sounds an interesting enchantment, we will look into it and let you know when we have more information.

**Comment by toumorokoshi** [comment]
(minor cleanup) we have a tracking issue (#25) for supporting setting a GCP resource name via a field that is not subject to the k8s naming restrictions.

Please watch the issue mentioned. ETA for the feature is before first week of Jan.
