### ISSUE TITLE
Provide a way to set GCP labels outside of Kubernetes labels

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#23]
The strategy of using k8s resource labels as GCP resource labels seems flawed since the key and value spaces are not compatible. This means that it is possible to add valid k8s labels that will fail GCP resource creation. One suggestion is to completely separate the two and instead define GCP resource labels as part of the `spec`

**Comment by xiaobaitusi** [comment]
Close this in favor of #607
