### ISSUE TITLE
Using IAM protected APIs using KCC objects from kubebuilder-generated operator

### ISSUE THREAD

**Issue by marcoderama** [GoogleCloudPlatform/k8s-config-connector#237]
I want to use a kubebuilder-generated operator to, for example, create an IAMPolicyMember (to grant a role to generated IAMServiceAccount).  The IAMPolicyMember KCC object is created but has the status message:

```
    message: 'error setting policy member: error applying changes: Error applying
      IAM policy for Spanner Database: my-project/my-instance/my-db:
      Error setting IAM policy for Spanner Database: my-project/my-instance/my-db:
      googleapi: Error 403: Caller is missing IAM permission spanner.databases.setIamPolicy
      on resource projects/my-project/instances/my-instance/databases/my-database.,
      forbidden'
```
So I need my _controller_ to have the perms to set that IAMPolicy.  I've looked at https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/215 which led me to [Creating a relationship between KSAs and GSAs](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#creating_a_relationship_between_ksas_and_gsas).

I _think_ I need to associate my operator KSA with a GSA that has been granted the `spanner.databases.setIamPolicy`.  Am I on the right track here?  If so, any particular gotchas I need to lookout for?

Thanks for any help on this.

**Comment by maqiuyujoyce** [comment]
Hi @marcoderama , thank you for your question! It seems to me that the GSA your KCC controller is using (usually it's `cnrm-system@[PROJECT_ID].iam.gserviceaccount.com`) doesn't have sufficient permissions. Could you verify that if you can see the same error message when you create the same IAMPolicyMember using `kubectl` directly?

**Comment by marcoderama** [comment]
D'oh!  I hadn't thought about the KCC controller for some reason.  I just confirmed that I get the same error when creating the IAMPolicyMember using `kubectl` directly.  We're using a different GSA, but I _believe_ the gcp-key was setup correctly with the different name.  I've confirmed that the GSA we're using has role/editor.

How now?  What else can I check?

This with Config Connector 1.13.1 btw.

**Comment by maqiuyujoyce** [comment]
Hi @marcoderama , thank you for your verification. As you've confirmed, your GSA has `roles/editor` on your project, and `roles/editor` actually doesn't have the `spanner.databases.setIamPolicy` permission. You can verify it via this command: `gcloud iam roles describe roles/editor | grep spanner.databases.setIamPolicy`. To grant your GSA the permission, you'll want to add an additional role `roles/spanner.databaseAdmin` or `roles/spanner.admin` at the project level. More details about the roles can be found [here](https://cloud.google.com/spanner/docs/iam#roles).

**Comment by marcoderama** [comment]
Heh.  Yeah, I ended up adding `roles/spanner.databaseAdmin` to the user and things worked.  As is often the case, the fix was simple.  I learned a bunch taking the circuitous path there at least.  :-)

Thanks very much for the excellent and timely responses.  You can close this!

**Comment by maqiuyujoyce** [comment]
No problem!
