### ISSUE TITLE
Upgrading between minor releases

### ISSUE THREAD

**Issue by ct-dh** [GoogleCloudPlatform/k8s-config-connector#238]
Hi, looking at the upgrade docs (https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#manual-upgrade) for manual installs (in our case we used the YAML definition to deploy for a workload identity based setup) we have to delete various things and then perform the regular install as below:

```
1. Remove the system components:

kubectl delete sts,deploy,po,svc,roles,clusterroles,clusterrolebindings --all-namespaces -l cnrm.cloud.google.com/system=true --wait=true
kubectl delete validatingwebhookconfiguration abandon-on-uninstall.cnrm.cloud.google.com --ignore-not-found --wait=true
kubectl delete validatingwebhookconfiguration validating-webhook.cnrm.cloud.google.com --ignore-not-found --wait=true
kubectl delete mutatingwebhookconfiguration mutating-webhook.cnrm.cloud.google.com --ignore-not-found --wait=true

2. Run the manual install steps
```

I saw in a comment on an issue somewhere that upgrades for minor versions of CC, such as 1.9 -> 1.10 should be fine to just apply without the deletes first, so just `kubectl apply` the new 0-cnrm-system.yaml), is this a valid statement, if so could it be added to the docs to make it clearer?

**Comment by jcanseco** [comment]
Hi @ct-dh, our recommendation is to follow the whole upgrade procedure as documented, including the deletions. We do not recommend just `kubectl apply`-ing the new system YAMLs without performing the deletions, since it is possible for system components to be renamed/removed across minor version bumps.

**Comment by ct-dh** [comment]
Okay, thanks for the answer :)
