### ISSUE TITLE
Incorrect instance metadata endpoint in 1.15.0

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/k8s-config-connector#247]
**Describe the bug**

Since upgrade to 1.15.0, _cnrm.*_ resources fail resolution because they're unable to fetch the service account token from the instance metadata endpoint.

**ConfigConnector Version**

`1.15.0`

**To Reproduce**
*Steps to reproduce the behavior:*
1. Deploy `1.15.0` version.
2. Attempt to deploy Config Connector-managed resources.
3. Observe errors of the following type:
```
{
  "level": "error",
  "ts": 1595278536.7752554,
  "logger": "controller-runtime.controller",
  "msg": "Reconciler error",
  "controller": "iampolicymember-controller",
  "request": "<namespace>/<resource>",
  "error": "error getting policy member: error fetching live state for resource: error reading underlying resource: Error when reading or editing Resource \"project \\\"projects/<project>\\\"\" with IAM Member: Role \"roles/cloudsql.client\" Member \"serviceAccount:<sa-account>@<project>.iam.gserviceaccount.com\": Error retrieving IAM policy for project \"projects/<project>\": Post https://cloudresourcemanager.googleapis.com/v1/projects/<project>:getIamPolicy?alt=json&prettyPrint=false: metadata: GCE metadata \"instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email\" not defined",
  "stacktrace": "cnrm.googlesource.com/cnrm/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/github.com/go-logr/zapr/zapr.go:128\ncnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\ncnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\ncnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"
}
```

It looks like the new CNRM version uses an incorrect instance metadata endpoint
```
instance/service-accounts/default/token?scopes=
  https://www.googleapis.com.auth.compute&
  https://www.googleapis.com.auth.cloud-platform&
  https://www.googleapis.com.auth.ndev.clouddns.readwrite&
  https://www.googleapis.com.auth.devstorage.full_control&
  https://www.googleapis.com.auth.userinfo.email
```
which is not understood by the GKE metadata server, because `scopes=` argument is not supported on GCE instances (afaik it can only be used inside Cloud Functions/App Engine/Cloud Run). In response, the metadata server returns a 404, which results in `not defined` error.

We have run into this issue before, but were assured that it was fixed in GKE 1.16.0+. However, it seems to have manifested again.

Removing `cnrm-system` namespace and re-deploying CNRM `1.14.0` makes everything work again.

*YAML snippets:*

Any Config Connector example from [samples](https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/samples), e.g.

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    label-one: "value-one"
  name: pubsubtopic-sample
```

**GKE Version**

`1.16.9-gke.6`

The cluster is configured with Workload Identity, if that matters.

**Comment by dinvlad** [comment]
It looks like GCE metadata endpoint with `scopes=` does work after all with CNRM `1.14.0`, so this may not be the culprit. Still, it's puzzling why we're getting the token fetching error with `1.15.0`.

**Comment by AlexBulankou** [comment]
@dinvlad , thanks for reporting. Trying to reproduce the issue:
  - KCC version 1.15.1. (latest)
  - GKE cluster 1.16.9-gke.6
  - installed in Workload Identity mode

applying pubsub resource, as in your example, works without problems:

```
Normal  UpToDate  56s   pubsubtopic-controller  The resource is up to date
```

**Comment by dinvlad** [comment]
Thanks @AlexBulankou - we're using 1.14.0 for now and didn't try 1.15.1 yet (and our issues were with 1.15.0, I think). Tbh since this is working well for now, I think I will revisit it at some point but not having the capacity to try out further atm.

**Comment by AlexBulankou** [comment]
@dinvlad , closing for now, please reactivate, if you can reproduce it on 1.15.1 or later.
