### ISSUE TITLE
CRD for compute subnetworks is missing metadata_fields in the log config for custom metadata

### ISSUE THREAD

**Issue by dustin-decker** [GoogleCloudPlatform/k8s-config-connector#249]
**Describe the feature or the resource that you want.**

I would like to be able to specify `metadata_fields` when `metadata` is set to `CUSTOM_METADATA` to include GKE fields that make the flow logs k8s-aware.

https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks

**Comment by spew** [comment]
Hi @dustin-decker thank you for the feature request, we have noted it and will look into prioritizing it an upcoming release.

**Comment by jcanseco** [comment]
Hi @dustin-decker, can you comment on whether this request is a nice-to-have, a pain point, or a blocker?

**Comment by dustin-decker** [comment]
I'd categorize it as a nice-to-have and a pain point. 

Flow logs for GKE nodes aren't very useful unless they have the metadata to identify the workload involved. The feature has been published for a few months, but doesn't seem well-supported. I tried adding it to terraform, but we got stuck on what appears to be an API bug: https://github.com/GoogleCloudPlatform/magic-modules/pull/3603 (`b/162771344`).

**Comment by dustin-decker** [comment]
`filterExpr` is another field that was added at the same time which would be nice to see supported.

**Comment by jcanseco** [comment]
Gotcha, thanks for elaborating in detail!

**Comment by dustin-decker** [comment]
The terraform provider now includes this feature: https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.37.0
From: https://github.com/GoogleCloudPlatform/magic-modules/pull/3603

**Comment by jcanseco** [comment]
Thanks for your contributions @dustin-decker! We'll work on bringing them into KCC in the coming weeks.

**Comment by caieo** [comment]
@dustin-decker , these fields should now be supported as of our [1.21.0 release](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.21.0).
