### ISSUE TITLE
Provide a field to set the GCP resource name instead of metadata.name

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#25]
We need a way of specifying the name of the underlying GCP resource so that it is different from the k8s resource name. In many cases this not critical but for some resource types the idea of the 1:1 relationship between k8s namespace and GCP project breaks down, e.g. `SQLUser` - if you have multiple `SQLInstance` resources in the same namespace there seems to be no way of setting the root password for more than one of them.

**Comment by dpetersen** [comment]
I am doing some fairly unwieldy workarounds for this same issue with `SQLUser` and `SQLDatabase`. It would be great to have a consistent way to have the Kubernetes name and actual resource name differ for this case, and also future cases. I doubt this will be the last resource to have this kind of mismatch.

**Comment by toumorokoshi** [comment]
We are planning on delivering a way to provide a field not bound by k8s resource name restrictions, to set the resource name in GCP.

The ETA to deliver that feature is before January 1st, hopefully sooner.

**Comment by dpetersen** [comment]
That's great news, thank you very much!

**Comment by maqiuyujoyce** [comment]
Hi, we just released Config Connector v1.32.0, which supports the resource ID overrides for `Folder` and BigQuery resources via the `resourceID` field. Will keep you updated when we support the feature in more resources. Detailed documentation will be coming soon.

**Comment by maqiuyujoyce** [comment]
Starting from [v1.35.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.35.0), Config Connector supports the resource ID overrides for `IAMCustomRole`, `SQL` resources, `Storage` resources, `KMS` resources, `PubSub` resources, and `LoggingLogSink`.

Also the detailed documentation for the `resourceID` field has been [published](https://cloud.google.com/config-connector/docs/how-to/managing-resources-with-resource-ids).

**Comment by maqiuyujoyce** [comment]
In [v1.36.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.36.0), Config Connector start supporting the resource ID overrides for `Compute` resources.

**Comment by maqiuyujoyce** [comment]
In [Config Connector v1.37.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.37.0), we added the `resourceID` support for the following resources:
  * `ArtifactRegistryRepository`
  * `Bigtable` resources
  * `DataflowJob`
  * `DNS` resources
  * `Monitoring` resources
  * `RedisInstance`
  * `ResourceManagerLien`
  * `SecretManagerSecret`
  * `Spanner` resources
  * `StorageTransferJob`

**Comment by maqiuyujoyce** [comment]
In [Config Connector 1.38.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.38.0), we added the `resourceID` support for the following resources:
* `AccessContextManager` resources
* `Container` resources
*  `SourceRepoRepository`

**Comment by aw185176** [comment]
When will `Project` support `resourceID`?

**Comment by maqiuyujoyce** [comment]
Hi @aw185176 , thank you for your question. We don't have a ETA yet but `Project` is the resource that we plan to look into next. Will post the updates when we have more information. Meanwhile, it would be great if you can share how urgent/important this feature is for your project. This could help us prioritize the feature.

**Comment by aw185176** [comment]
This feature is definitely urgent for our product, we are currently running into issues with creating `Project`s for tenants -- any code we implement to mitigate lack of `resourceID` will be tossed as soon as `Project` supports it

**Comment by maqiuyujoyce** [comment]
Closing as `resourceID` has been supported in all requested resources.
