### ISSUE TITLE
Feature Request: Support for Memcached Memorystore

### ISSUE THREAD

**Issue by balaji** [GoogleCloudPlatform/k8s-config-connector#267]
This is a request to provide support for managing [Memcached Memorystore](https://cloud.google.com/memorystore/docs/memcached) resources. Thanks.

**Comment by maqiuyujoyce** [comment]
Hi @balaji , thank you for your request. Just to confirm, the resource you need is [Memcached Instance](https://cloud.google.com/memorystore/docs/memcached/reference/rest/v1beta2/projects.locations.instances), right?

**Comment by balaji** [comment]
Hi @maqiuyujoyce. That is correct, very similar to how [Memorystore Redis Instance](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/redis_v1beta1_redisinstance.yaml) is managed in KCC.

**Comment by maqiuyujoyce** [comment]
Gotcha, thanks for your confirmation, @balaji ! We've added it to the list of resources we're
looking into and will let you know when we have more information.

**Comment by jcanseco** [comment]
This has been implemented: [MemcacheInstance](https://cloud.google.com/config-connector/docs/reference/resource-docs/memcache/memcacheinstance).
