### ISSUE TITLE
Integration with k8s secrets

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#27]
It would make a lot of sense to be able to reference a k8s secrets, e.g. as the password of an `SQLUser`.

**Comment by nrobert13** [comment]
:+1:

**Comment by kibbles-n-bytes** [comment]
Thanks for the suggestion. We plan to support this feature for known sensitive fields within the coming months.

**Comment by kibbles-n-bytes** [comment]
Hey yhrn@, this is available in the latest release. Let us know if you have any further feedback or issues.

**Comment by mithrandi** [comment]
Is there any documentation yet on how to use this?

**Comment by jcanseco** [comment]
@mithrandi: apologies for the late response. Documentation for using K8s Secrets with Config Connector can be found [here](https://cloud.google.com/config-connector/docs/how-to/secrets).
