### ISSUE TITLE
Support for gRPC fields and resource part of Google Traffic Director

### ISSUE THREAD

**Issue by erikjoh** [GoogleCloudPlatform/k8s-config-connector#274]
Hi!
We are looking at configuring proxyless gRPC in Google Traffic Director using KCC and are missing some stuff:

* `grpcHealthCheck` field in [HealthCheck](https://cloud.google.com/compute/docs/reference/rest/v1/healthChecks) (medium-high prio)
* [TargetGrpcProxy](https://cloud.google.com/compute/docs/reference/rest/v1/targetGrpcProxies) (low-medium prio)
* `GRPC` as `protocol` field in [BackendService](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) (low-medium prio)

**Comment by caieo** [comment]
Hi @erikjoh, 

We now support `grpcHealthCheck` in version 1.21.0 [release notes here](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.21.0).  

We've added TargetGrpcProxy to our list of resource requests and will look into supporting it in the future.

I'll update this thread when we add support for `GRPC` as `protocol` field in ComputeBackendService.

**Comment by jcanseco** [comment]
`ComputeBackendService` now supports `GRPC` as `protocol` in KCC 1.24.0.

We'll be working to add support for `ComputeTargetGrpcProxy` next. We'll update this thread accordingly once that's out.

**Comment by erikjoh** [comment]
Hi again,
Noticed now that the `ComputeTargetGrpcProxy` now is available! :smile: 
However, for it to be usable, the [forwarding rule resource](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/compute_v1beta1_computeforwardingrule.yaml) must also support the `targetGrpcProxyRef` field.

**Comment by maqiuyujoyce** [comment]
Hi @erikjoh , thank you for your follow up. We'll look into prioritizing it. Will provide updates when we have more information.

**Comment by erikjoh** [comment]
Are there any updates on this?

**Comment by toumorokoshi** [comment]
Hi! `targetGRPCProxyRef` will be in the forwarding rule in the next release.

**Comment by maqiuyujoyce** [comment]
`targetGRPCProxyRef` is now supported in [v1.41.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.41.0)

**Comment by maqiuyujoyce** [comment]
In [v1.41.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.41.0), `targetGRPCProxyRef` field is supported in `ComputeForwardingRule`.
