### ISSUE TITLE
Why is iam_v1beta1_iampolicymember.yaml CRD missing gcp category? 

### ISSUE THREAD

**Issue by MarkD43** [GoogleCloudPlatform/k8s-config-connector#286]
When executing kubectl get gcp -n {namespace}, iam policy members are not returned.  IAM policy member CRD is missing gcp category and short names.

We are currently using kcc version 1.19.1 but I see the latest CRD version is missing gcp category as well.

**Comment by caieo** [comment]
Hi @MarkD43 , thank you for bringing our attention to this. We are aware that our IAM Policy/IAM Policy Member CRDs don't have "gcp" category and shortnames the way the rest of our resources do. The short explanation is that our IAM resources are generated a little differently and we haven't yet added those fields/indicators into it. I will mark this as a bug and we will look into fixing this!

**Comment by jcanseco** [comment]
Hi @MarkD43, this has now been fixed in KCC 1.24.0.
