### ISSUE TITLE
All the CRD names and categories should be retrievable without loading the CRD files locally

### ISSUE THREAD

**Issue by maqiuyujoyce** [GoogleCloudPlatform/k8s-config-connector#2869]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Right now when we want to retrieve all kind/CRD names and their categories (TF-base/DCL-based/direct), we call [supportedgvks.All()](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/ace7489767a246333bbc0ca0b4c210d36d084b98/pkg/gvks/supportedgvks/supportedgvks.go#L32). However, this calls [supportedgvks.resourcesWithDirect()](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/ace7489767a246333bbc0ca0b4c210d36d084b98/pkg/gvks/supportedgvks/supportedgvks.go#L46) and eventually calls [repo.GetRootOrTestFatal()](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/ace7489767a246333bbc0ca0b4c210d36d084b98/pkg/util/repo/repo.go#L57), which assumes that the caller is within a local copy of our Git repo. However, if supportedgvks.All() is called in the controllers (webhooks, direct controllers, etc) that is not under a local copy of our git repo, this will fail with error like:

```
unable to locate repo root in working directory "/"
```

We should figure out a way to retrieve all kind/CRD names and their categories.

**Comment by jasonvigil** [comment]
Ref to the original fix: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2868
