### ISSUE TITLE
Add categories to Config Connector CRDs

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#29]
Adding some categories to the Config Connector CRDs would make them nicer to work with using `kubectl`. I'm thinking the category "all" makes sense as you probably want to see them when doing `kubectl get all`, but maybe also a category like "gcp" that allows you to list all GCP resources.

**Comment by kibbles-n-bytes** [comment]
We just added a `gcp` category; this change will be in the 0.1.7 release at the end of this week. For this first cut, IAMPolicy and the Bigtable resources are missing from the query, but the others should all show up. We'll work on getting those in in a follow-up.

Closing for now; feel free to open a new issue if an element isn't addressed after the 0.1.7 release.

**Comment by yhrn** [comment]
@kibbles-n-bytes While I think that the `gcp` category makes sense, wouldn't it also be nice to add `all`? My understanding is that `all` is suitable for any resource type that a user would be managing directly, possibly with some exceptions like secrets, and I feel like the GCP resources fall into that category.

**Comment by kibbles-n-bytes** [comment]
I'll need to double check to see if there's any updated guidance, but my first impression is that yeah, we should be able to add most of them to `all` as well. We likely will need to filter out certain types like `IAMServiceAccountKey` from that, though. `gcp` seemed like a good first candidate to start with, and then we'll follow up on `all`; I'll open a new issue tracking just that piece.

**Comment by kibbles-n-bytes** [comment]
#44
