### ISSUE TITLE
Can you publish contributing material? How can my team add more resources to Conifg Connector?

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/k8s-config-connector#299]
It's not clear how new resource support happens -- this could rapidly expand coverage of config connector if users have some contribution pathway to support more types of gcp resources.

**Comment by kibbles-n-bytes** [comment]
Hey @tmc , at the moment unfortunately we're not accepting external contributions. We're sorry that we're not able to fully support more GCP resources at the moment, and we recognize this is one of the key blockers for adoption. We're working internally now to ensure that in 2021 the pipeline is set up such that resource support is a non-issue going forward.
