### ISSUE TITLE
notificationConfig on StorageTransferJob

### ISSUE THREAD

**Issue by vic614** [GoogleCloudPlatform/k8s-config-connector#303]
StorageTransferJob object is missing the `notificationConfig` spec as per the API. https://cloud.google.com/storage-transfer/docs/reference/rest/v1/NotificationConfig 

Any plan supporting this?

**Comment by jcanseco** [comment]
Hi @vic614, I created an issue against the Google Terraform provider to add a `notification_field` for the `google_storage_transfer_job` resource. Once that's done, we can bring that change over into Config Connector's `StorageTransferJob` resource. We'll update this issue accordingly once we have an update.

**Comment by jasonneurohr-stake** [comment]
+1 would also like this to be added. Any update?

**Comment by jcanseco** [comment]
Hi @jasonneurohr-stake, unfortunately there has been no movement on https://github.com/hashicorp/terraform-provider-google/issues/7775, so it would appear that the Terraform team has had no capacity to work on it.

We don't have much capacity currently either so I don't see us being able to work on this any time soon.
