### ISSUE TITLE
apiextensions.k8s.io/v1beta1 is deprecated; migrate to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by xvzf** [GoogleCloudPlatform/k8s-config-connector#308]
**Describe the feature or the resource that you want.**
https://github.com/kubernetes/kubernetes/issues/82022

**Comment by toumorokoshi** [comment]
Thanks for filing the issue! I'm noting that the API is deprecated, and it looks like the copmletely removal has been pushed to v1.22  so maybe a year down the road. 

We'll try to get this scheduled so we're done well before then. thanks!

**Comment by xvzf** [comment]
In case you maintain them manual, I can open  a PR to fix it!

**Comment by xiaobaitusi** [comment]
Our [CRDs](https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/crds) are not handcrafted, modification on github will be overwritten  by our pipeline on next release. We need to change our CRD generation pipeline and runtime controllers to start using apiextensions.k8s.io/v1. Thanks for offering though!

**Comment by jcanseco** [comment]
Closing as I believe this has been fixed.
