### ISSUE TITLE
StorageBucket crd support for customTime conditions

### ISSUE THREAD

**Issue by Muni10** [GoogleCloudPlatform/k8s-config-connector#309]
**Describe the feature or the resource that you want.**
I can see from the crd that there is currently no support for customTimeBefore and daysSinceCustomTime in the lifecycleRules for storage buckets created with cnrm. Are there any plans to make this available?

**Comment by ramrock93** [comment]
**+1**

**Comment by toumorokoshi** [comment]
Hi! Thanks for filing the request.

I've added an issue in our internal tracker. Regarding timeline, would you mind elaborating on what this is blocking for you? 

If you have a ballpark as to whether this is a blocker, and if so what type of scenarios it's blocking, that would be great.

**Comment by Muni10** [comment]
We would like to control documents in the storage bucket by setting the custom time so when we have finished processing a document we can delete it using the custom time marker. This is to ease handling and maintenance of the bucket. As for blocking, there are workarounds as handling all deletion specifically in the application. As cnrm is controlling the bucket, there is no simple way to override cnrms settings for the bucket in the application, which means we would have to delete documents one by one for all applications using buckets. With custom time implemented we could make this available for all buckets in our deployment mechanism. So this is not blocking, but rather a very useful feature.

**Comment by maqiuyujoyce** [comment]
Hi @Muni10 , thank you for elaborating your scenario. We will take it into consideration when we prioritize the work. Will let you know if there is any update.

**Comment by jcanseco** [comment]
Hi all, these are now supported in [KCC v1.34.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.34.0).
