### ISSUE TITLE
v1/instanceGroupManagers and v1/regionInstanceGroupManagers support

### ISSUE THREAD

**Issue by bshimc** [GoogleCloudPlatform/k8s-config-connector#314]
**Describe the feature or the resource that you want.**

Are managed instance groups (MIG) on the roadmap?  They are notably absent from the compute resources.

https://cloud.google.com/compute/docs/reference/rest/v1/instanceGroupManagers

**Comment by xiaobaitusi** [comment]
Hi @bshimc, thanks for reaching out.
Yes, they are on our roadmap. Do you mind sharing the rough time when you want to start using those two resources? Are they currently blocking you?

**Comment by bshimc** [comment]
Hi @xiaobaitusi it's blocking consolidation onto the Kubernetes API as the single mechanism of configuration for me.  Either type will satisfy my use case and the I have no opinion on which is more important (the trade-offs are a wash for us).

**Comment by xiaobaitusi** [comment]
Thanks for the clarification. We'll start looking into those two resources and will let you know when we have more updates.

**Comment by jcanseco** [comment]
Hi @bshimc, we just added support for `ComputeInstanceGroupManager` in [KCC 1.56.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.56.0).
