### ISSUE TITLE
Config connector not updating bucket when uniformBucketLevelAccess is modified

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#316]
Not sure if this is expected behavior or not

Initially I was using  `bucketPolicyOnly: true` which I then switched to `uniformBucketLevelAccess: false`

After applying the manifest the bucket still has uniform access enabled

Does config connector not update resources or is this a bug with this specific resource?

**Comment by xiaobaitusi** [comment]
Hi @red8888, I assume that you want to switch Access control from `uniform access` to `Fine-grained`. By reading this [doc](https://cloud.google.com/storage/docs/uniform-bucket-level-access?_ga=2.171808864.-1596458070.1604017512), it seems that the `unform access` cannot be reverted after 90 days. Can you confirm if this is the case for you? Sorry that I don't have a storage bucket with `uniform access` enabled older than 90 days to repo the behaviour.

Besides, if you run 'kubectl describe StorageBucket [YOUR_BUCKET] -n [YOUR_NAMESAPCE]', what is the status for this resource?

**Comment by red8888** [comment]
sorry I just deleted the bucket and recreated it. I can close this, but I will say it was immediate. I created a bucket with `uniform access` and like hours later changed the config to `uniformBucketLevelAccess: false`. waited a while but it didnt update
