### ISSUE TITLE
Confused about how importing existing resources works

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#317]
Reading the docs on importing existing resources: https://cloud.google.com/config-connector/docs/how-to/import-export/export

I has me kind of confused here, it seems like the `config-connector export` command is just generating yaml for me that I then apply? Does that mean if I just added a resource definition for an existing resource config connector will try to import it? I would expect it to throw an error saying it already exists. Does the `config-connector export` command do more than just generate a yaml manifest? Does it also prep config connector so it knows the resource is to be imported?

> Export the topic with config-connector export by running the following command:
> 
> config-connector export ${TOPIC_RESOURCE_NAME}
> 
> The output is a Config Connector resource in YAML format.
> 
> ---
> apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
> kind: PubSubTopic
> metadata:
>   annotations:
>     cnrm.cloud.google.com/project-id: project_id
>   name: sample-topic
> ...
> 
> In the output, project-id will be replaced with your with your Google Cloud project.
> 
> You can pass this resource into Config Connector with kubectl apply -f -. To pass the resource directly, run the following command:
> 
> config-connector export ${TOPIC_RESOURCE_NAME} | kubectl apply -f -  --namespace CC_NAMESPACE

**Comment by xiaobaitusi** [comment]
Hi @red8888, sorry for the confusion here.
>  it seems like the config-connector export command is just generating yaml for me that I then apply?

yes, config-connector cli's export command will only generate yaml for the existing resource. The CLI is a separate component than Config Connector installation in k8s cluster; only after applying the generated yaml to your cluster with Config Connector addon installed, KCC will start manage the underlying GCP resource.

The config-connector cli is meant to be an convenient tool to bring your existing GCP infrastructure as they are under Config Connector management. Then you can start to manage your GCP resources by modifying the corresponding k8s objects.

**Comment by red8888** [comment]
yeah but this is the source of my confusion: `only after applying the generated yaml to your cluster with Config Connector addon installed, KCC will start manage the underlying GCP resource`

How does it know to import and not recreate that resource? What I would expect is kcc to try to create a new resource and fail because it already exists. If not then that makes me a little concerned because that means someone can inadvertently import an existing resource they didn't know already existed into kcc right?

**Comment by red8888** [comment]
If I describe a resource in a kcc CRD that already exists will kcc just import and own it? or will it throw an error saying it already exists?

**Comment by maqiuyujoyce** [comment]
Hi @red8888 , thank you for your questions and sorry for the confusion.

> How does it know to import and not recreate that resource?

> If I describe a resource in a kcc CRD that already exists will kcc just import and own it? or will it throw an error saying it already exists?

Config Connector will try to fetch the GCP resource before creating it. If the Google Cloud resource already exists with the same name, then Config Connector takes control of the resource and manages it with the YAML the user provides. It will not throw an error unless the provided YAML contains changes to immutable fields (and the error is not an `already_exists` error).

> What I would expect is kcc to try to create a new resource and fail because it already exists. If not then that makes me a little concerned because that means someone can inadvertently import an existing resource they didn't know already existed into kcc right?

Yes, we understand that it's a valid concern. Currently, if the user has the right permission, and the resource name and the immutable fields are matching, then yes, they can acquire an existing resource they didn't know already existed using KCC. What is the particular scenario you want to handle? Do you plan to only create new resources using Config Connector but not managing existing resources with it? We'd like to learn more about your use case.

**Comment by red8888** [comment]
Yes that is my only concern. It would be nice to make this configurable somehow to prevent the scenario i described.

This is the most obvious issue I think one would want to avoid: 

> 1. User1 deploys app-123 with a manifest that includes a gcs bucket via kcc CRDs
> 2. User2 deploys app-abc with a manifest that includes a gcs bucket via kcc CRDs inadvertently with the same bucket ID
> 3. Now they are fighting for management of the same resource and we would have no way of knowing this is happening because kcc is happy to just "grab" it
> 4. app-123 changes some config on the bucket CRD and that breaks app-abc because its expecting a different configuration of that resource
> 5. Even worst lets say app-123 is turned down and deleted including its dependent resources. Now that resource that app-abc depends on is gone.

Also, I have some resources that should be shared between many apps and some that are "owned" by specific apps. I worry about one of those "shared" resources accidentally being brought into kcc management.

**Comment by red8888** [comment]
Also, I would definitely make this a warning or highlight this clearly and early in the docs- sorry if it already is, I frankly have not pour over them completely yet

Maybe its just my experience but I think, generally speaking, this sort of behaviour is unexpected from an IaC tool. Im thinking about terraform, cloudformation, even google's own deployment manager- all of these tools are explicit about importing _existing_ resources into configuration management before they can be managed by the tool

**Comment by maqiuyujoyce** [comment]
Hi @red8888 , thank you for providing the detailed use case. If I've understood it correctly, it seems that you want to prevent more than one KCC resource managing the same GCP resource at the same time, right? For that particular scenario, you might consider using annotation `cnrm.cloud.google.com/management-conflict-prevention-policy: resource` to prevent conflicts with multiple Config Connector instances. More details can be found [here](https://cloud.google.com/config-connector/docs/concepts/managing-conflicts). Basically, after one Config Connector resource has successfully acquired the GCP resource, other Config Connector resources can't take control of the GCP resource any more. Please let us know if this could support your use case.

> Also, I have some resources that should be shared between many apps and some that are "owned" by specific apps. I worry about one of those "shared" resources accidentally being brought into kcc management inside a manifest that is scoped to a specific app's deployment

Gotcha. So in this use case, do you plan to have those "shared" resources managed by Config Connector, maybe in a manifest that is scoped to "admin"? Or do you plan to manage them outside of Config Connector?

> Also, I would definitely make this a warning or highlight this clearly and early in the docs- sorry if it already is, I frankly have not pour over them completely yet

Thank you for the suggestion. We'll try to improve our documentation based on it.

> Maybe its just my experience but I think, generally speaking, this sort of behaviour is unexpected from an IaC tool. Im thinking about terraform, cloudformation, even google's own deployment manager- all of these tools are explicit about importing existing resources into configuration management before they can be managed by the tool

You've brought a good point that those IaC tools are more explicit about importing existing resources. Config Connector, on the other hand, is slightly different from a traditional IaC tool. We've designed our user experience based on the concept of [Configuration as Data](https://cloud.google.com/blog/products/containers-kubernetes/understanding-configuration-as-data-in-kubernetes), which tries to minimize imperative steps in managing resources. But we agree that we should better support the scenario. If there is a "creation-policy" annotation that you can use to restrict the ability to acquire, does that sound like an option for you?

**Comment by red8888** [comment]
Thanks for the detailed response! 

"cnrm.cloud.google.com/management-conflict-prevention-policy: resource" is great and solves my first issue. Is there a way to apply that cluster wide so that's the default behavior for all resources or do I have to add that to every individual resource?

I actually manage my shared, more static resources with another IaC tool (terraform) and plan to keep using it for that. Terraform is cross platform and it feels safer and easier for managing foundational infra. I'm trying to use kcc in a more dynamic gitops way so my apps and all the resources they own are described In a single template (k8s manifest)

a "creation-policy" annotation your suggesting sounds pretty much exactly what I want. Just something that returns an error if the resource exists

Also just curious, the tools I mentioned before all have the notion of "state" which is reconciled against the existing resources. Does kcc not use "state" in the same way and does that make what I'm asking for a little tricky?

I'll close this because you've answered my main questions in you last comment

**Comment by maqiuyujoyce** [comment]
No problem!

> "cnrm.cloud.google.com/management-conflict-prevention-policy: resource" is great and solves my first issue. Is there a way to apply that cluster wide so that's the default behavior for all resources or do I have to add that to every individual resource?

Yes, you can annotate your namespace with the annotation to apply it to all the resources under it. Here is an [example of how to annotate a namespace](https://cloud.google.com/config-connector/docs/how-to/organizing-resources/project-scoped-resources#annotate_namespace_configuration).

> I actually manage my shared, more static resources with another IaC tool (terraform) and plan to keep using it for that. Terraform is cross platform and it feels safer and easier for managing foundational infra. I'm trying to use kcc in a more dynamic gitops way so my apps and all the resources they own are described In a single template (k8s manifest)
>
> a "creation-policy" annotation your suggesting sounds pretty much exactly what I want. Just something that returns an error if the resource exists

Thanks for the information and suggestion.

> Also just curious, the tools I mentioned before all have the notion of "state" which is reconciled against the existing resources. Does kcc not use "state" in the same way and does that make what I'm asking for a little tricky?

Config Connector, like the tools you've mentioned, also reconciles the desired state against the actual state of the matching resource, but it takes a Kubernetes-native strategy. The drift detection happens automatically and the reconciliation is "self-healing". Config Connector reconciles the resources regularly, and once it finds that the desired state and the actual state don't match, it tries to close the gap by itself as much as it can. For example, a Google Compute instance will be recreated automatically after it is deleted if it's managed by Config Connector. So in the acquisition scenario, if there is an existing GCP resource that matches the yaml configuration exactly, it means there is no gap and the resource is ready to go.

Because of that, it is a bit tricky to support the scenario you described. But we understand it is a valid case so we will be looking into how to support it in long-term.
