### ISSUE TITLE
Can I safety "disconnect" and reimport a resource into config connector? 

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#318]
I want to use config connector but I need to make sure it gives me a similar level of safety when recovering from a misconfiguration that terraform does which I use now.

for example with terraform if the terraform configuration of a resource is "broken" or something I can remove that resource from terraform state and terraform will no longer track it or touch it, then I can reimport the resource back into terraform state all without modifying the actual resource itself

With config connector can I just detach a resource and have config connector stop tracking it and then if I want to reimport the resource? I want to do this without having to delete the resource or modify the resource itself.

How can I remove a config connector resource without removing the actual GCP resource its tracking is essentially what I am asking

Thanks!

**Comment by spew** [comment]
Hi @red8888 thanks for your question. You can take a look at our "abandon" deletion-policy for achieving what you want: https://cloud.google.com/config-connector/docs/how-to/managing-deleting-resources#keeping_resources_after_deletion
