### ISSUE TITLE
Support creating GCP Projects using KCC

### ISSUE THREAD

**Issue by jlewi** [GoogleCloudPlatform/k8s-config-connector#32]
It doesn't look like its possible to use KCC to create GCP projects today; is that accurate?

In which case filing this issue to track adding support for that.

**Comment by kibbles-n-bytes** [comment]
We now have support for creating projects via Config Connector. Please see the following samples:
- https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/resources/project/project-in-folder/resourcemanager_v1beta1_project.yaml
- https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/resources/project/project-in-org/resourcemanager_v1beta1_project.yaml

Let us know if you have any further requests!
