### ISSUE TITLE
Enhancement: Hub/Connect Resources in KCC

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/k8s-config-connector#330]
I want to be able to do `gcloud container hub memberships register` with KCC in order to unblock multi-cluster ingress.

https://cloud.google.com/sdk/gcloud/reference/container/hub

I probably also want to enable MultiClusterIngress (`gcloud container hub ingress enable`) and MultiClusterService (`gcloud container hub multi-cluster-services enable`) on GKE.

**Comment by maqiuyujoyce** [comment]
Hi @karlkfi , thank you for your suggestions. We've added it to the list of resources we're looking into and will let you know when we have more information.

**Comment by toumorokoshi** [comment]
The GKEHubFeature resources have been added, with [MultiClusterIngress configurable](https://cloud.google.com/config-connector/docs/reference/resource-docs/gkehub/gkehubfeature). 

Thank you!
