### ISSUE TITLE
BigQuery Authorized View

### ISSUE THREAD

**Issue by tdigangi** [GoogleCloudPlatform/k8s-config-connector#333]
Add support for [bq authorized view](https://cloud.google.com/bigquery/docs/share-access-views).

**Comment by maqiuyujoyce** [comment]
Hi @tdigangi , thank you for your suggestion. We will look into how to support the BigQuery Authorized View. Will let you know when we have more information.

**Comment by travisrandolph-bestbuy** [comment]
@maqiuyujoyce Did you ever investigate Authorized datasets/views? We have teams that would like to use this feature through KCC.

**Comment by maqiuyujoyce** [comment]
Thanks for confirming, @travisrandolph-bestbuy !
