### ISSUE TITLE
Duplicate cnrm in image path in building kcc release

### ISSUE THREAD

**Issue by xiaoweim** [GoogleCloudPlatform/k8s-config-connector#3336]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We found duplicate cnrm/ in image path. Issue reference: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3164/commits/295914cae9d5f087ec130df19ed4bdfc5b648e7b

### Additional Diagnostic Information

The difference in release bundle version 1.125.0 and 1.124.0 is that the image path went from `image: gcr.io/cnrm-eap/recorder:xxx` to `image: gcr.io/cnrm-eap/cnrm/recorder:xxx`.

When replacing `cnrm-eap` with `gke-release/cnrm`, it causes the duplicate cnrm in image paths.

### Kubernetes Cluster Version

v1.16.4

### Config Connector Version

1.125.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

```
$ cd operator
$ make upgrade-kcc
```

**Comment by xiaoweim** [comment]
In `operator/Makefile`, the `upgrade-kcc` command leverages the the pre-build release bundle `gs://cnrm/${Version}/release-bundle.tar.gz`. 
 - For example in version 1.125.0 release bundle `gs://cnrm/1.125.0/release-bundle.tar.gz`, the images are in the format of `gcr.io/cnrm-eap/cnrm/recorder:xxxxx`, thus when replacing `gcr.io/cnrm-eap` with `gcr.io/gke-release/cnrm`, it will result in duplicate cnrm in the image path.
 - However, in version 1.124.0 release bundle `gs://cnrm/1.124.0/release-bundle.tar.gz`, images are in the format of `image: gcr.io/cnrm-eap/recorder:xxx`, thus when replacing `gcr.io/cnrm-eap` with `gcr.io/gke-release/cnrm`, it does not cause the same problem.

**Comment by xiaoweim** [comment]
The image path changes (to add /cnrm after $PROEJCT_ID) in `Makefile` introduced in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2667, is added with the purpose to clearly identify built kcc images in developers' local workspace and for development and testing. 

This change has also appended a /cnrm with the legacy build process that have caused the issue. However, a new build process to simplify the kcc release build is introduced in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2736 with the command `VERSION=${VERSION} dev/tasks/propose-tag`.

**Comment by xiaoweim** [comment]
The new kcc release process does not leverage the legacy build release bundle, therefore after changing the the project substitution in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3304, it should resolve the issue and allow us to smoothly migrate to the new release process. @yuwenma @cheftako

**Comment by xiaoweim** [comment]
The process to build the bundle to be stored in the gcs bucket is in the internal GOB.

**Comment by yuwenma** [comment]
Thanks for the investigation.
