### ISSUE TITLE
ConfigConnector Webhook uses deprecated 'CommonName' field for certificates and cannot be installed in k8s 1.19.x

### ISSUE THREAD

**Issue by Tonyqu123** [GoogleCloudPlatform/k8s-config-connector#335]
**Describe the bug**
After install the k8s-config-connector on our k8s cluster[version: 1.19.3]. I try to install an sql instance by following the sample yaml. Use the command `kubectl create -f /path/to/sample-sql.yaml`

Error from server (InternalError): error when creating "/Users/i519593/Code/cnrm/tmp/samples/sql.yaml": Internal error occurred: failed calling webhook "annotation-defaulter.cnrm.cloud.google.com": Post "https://cnrm-validating-webhook.cnrm-system.svc:443/annotation-defaulter?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

**ConfigConnector Version**
1.16.0

**To Reproduce**
Install a k8s 1.19.x cluster.  kubectl create -f /path/to/sample-sql.yaml 

*YAML snippets:*
  apiVersion: sql.cnrm.cloud.google.com/v1beta1
  kind: SQLInstance
  metadata:
    name: sqlinstance-sample-mysql
  spec:
    databaseVersion: MYSQL_5_7
    region: us-central1
    settings:
      tier: db-f1-micro%

**Comment by Tonyqu123** [comment]
K8s 1.19.x  is now built with golang 1.15.0-rc.1. As it says:
`The deprecated, legacy behavior of treating the CommonName field on X.509 serving certificates as a host name when no Subject Alternative Names are present is now disabled by default. It can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable. (#93264, @justaugustus) [SIG API Machinery, Auth, CLI, Cloud Provider, Cluster Lifecycle, Instrumentation, Network, Node, Release, Scalability, Storage and Testing]`

**Comment by Tonyqu123** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#v1194

**Comment by caieo** [comment]
Hi @Tonyqu123 , thank you for bringing this to our attention. Just to get more context, are you currently using a GKE cluster?

Given this breaking change of disabling the `CommonName` field for certificates, it looks like Config Connector cannot work with 1.19 and above Kubernetes Clusters until we update our webhook. Sorry for the inconvenience, but can you try using a lower versioned Kubernetes cluster until we fix this issue?

**Comment by Tonyqu123** [comment]
Yes, we could use a lower version one. By the way, we are not using GKE, but [gardener](https://github.com/gardener/gardener)

**Comment by caieo** [comment]
Ah okay, thank you for the update & being flexible to use a lower versioned cluster. We'll update this thread when we fix the issue with k8s 1.19 compatibility.

**Comment by maqiuyujoyce** [comment]
This bug should be fixed in [Config Connector v1.37.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.37.0). Please let us know if you have any other questions.
