### ISSUE TITLE
Support minutes and seconds values for maxAge attribute of the Bigtable Garbage Collection Policy (GCP)

### ISSUE THREAD

**Issue by wesam80** [GoogleCloudPlatform/k8s-config-connector#345]
It seems that the smallest `maxAge` value we can get using config-connector is [`days`](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/b846b13592a181810047b448d51fc369b208971e/crds/bigtable_v1beta1_bigtablegcpolicy.yaml#L81)

We are looking for `minutes`. 

[Google's documentations](https://cloud.google.com/bigtable/docs/configuring-garbage-collection#cbt_4) states that the supported time units are `days`, `minutes`, and `seconds`

**Comment by caieo** [comment]
Hi @wesam80, I filed an issue against the Google Terraform provider to support `minute` and `seconds` for the `maxAge` field. Once that's done, we will bring that change over to ConfigConnector's `BigtableGCpolicy` resource. We will post any updates in this issue thread.

**Comment by kevinsi4508** [comment]
This should be resolved by using [`gc_rules`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_gc_policy#gc_rules). Currently we are waiting for KCC to update to the latest Google Terraform Provider version.

**Comment by mbzomowski** [comment]
`spec.gcRules` has been added to `BigTableGCPolicy` as of Config Connector [v1.97.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.97.0). We don't recommend using `maxAge`, `maxVersion` or `mode` for defining a
BigTableGCPolicy as these fields have known drift detection issues. Please use `gcRules` instead.
