### ISSUE TITLE
Support for Network Security Resources

### ISSUE THREAD

**Issue by JamesDuncanNz** [GoogleCloudPlatform/k8s-config-connector#347]
Added support for [Network Security AuthorizationPolicies](https://cloud.google.com/sdk/gcloud/reference/alpha/network-security/authorization-policies)

Added support for [Network Security ClientTlsPolicies](https://cloud.google.com/sdk/gcloud/reference/alpha/network-security/client-tls-policies)

Added support for [Network Security ServerTlsPolicies](https://cloud.google.com/sdk/gcloud/reference/alpha/network-security/server-tls-policies)

**Comment by maqiuyujoyce** [comment]
All the resources have been supported since Config Connector [v1.54.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.54.0).
