### ISSUE TITLE
Add support for defining named ports for instance groups

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#35]
Backend service requires a named port. There's a separate issue opened on [supporting instance groups](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/33) , this one is track support for named ports configuration as part of supporting instance groups.

**Comment by toumorokoshi** [comment]
namedPort is now supported: https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computeinstancegroup
