### ISSUE TITLE
Can I prevent users from deleting a gke cluster if there are remaining config connector resources?

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#356]
Im pretty sure this is impossible but figured I would ask if it might be supported at some point

As soon as I start managing my resources with kcc I want to make sure that if a cluster needs to be deleted all the kcc managed resources are deleted first.

To enforce that is there a way to have something almost like a "finalizer" on the gke cluster itself? So for example if a user deletes a cluster they get an error saying that the kcc running on that cluster is still managing GCP resources.

**Comment by spew** [comment]
I am not aware of any such hook or mechanism. That being said, if a cluster is deleted, as long as the namespaces are deleted then all of the KCC managed resources are deleted.

Does deleting a GKE cluster cause the namespaces to be deleted first? Or is the cluster destroyed without deleting the namespaces?

**Comment by red8888** [comment]
oh wow it would be amazing if it worked like that

I don't really know the order in which things are deleted when you delete a gke cluster.

So what I _thought_ would happen if a gke cluster with kcc is just deleted (via gcloud or console) is that the underlying GCE instances and control plane are killed ASAP- without waiting on any namespace finalizers or anything. So my thinking was that the cluster is just killed and all the namespaces go away because the cluster doesn't exist. I didn't think GKE gracefully removed k8s resources/namespaces before deleting a cluster.

If a namespace finalizer, like what kcc has, would prevent a gke cluster from getting deleted, or ensure the namespace was gracefully removed so that kcc could clean up, that would be awesome. thats all I want, not necessarily preventing users from deleting clusters, just ensuring that kcc cleans up its gcp resources when a cluster is deleted.

**Comment by spew** [comment]
I think you are right and GKE just terminates everything without gracefully cleaning up resources. If your command which deletes the cluster would first delete the namespaces in the cluster then you could achieve your desired behavior.

**Comment by spew** [comment]
Here is a command which deletes namespaces which have the KCC project-id annotation and removes their associated workload identity binding.


```
for namespace in $(kubectl get namespaces -o json | jq --raw-output '.items[] | select(.metadata.annotations != null) | select(.metadata.annotations."cnrm.cloud.google.com/project-id" != null) | select(.status.phase == "Active") | .metadata.name'); do
  gcloud iam service-accounts remove-iam-policy-binding ${CNRM_SYSTEM_GSA_EMAIL} \
    --member "serviceAccount:${PROJECT_ID}.svc.id.goog[cnrm-system/cnrm-controller-manager-${namespace}]" \
    --role "roles/iam.workloadIdentityUser" \
    --no-user-output-enabled || true
  echo "Deleting namespace ${namespace}..."
  kubectl delete --wait=false namespace ${namespace}
done
```

**Comment by red8888** [comment]
I can script this myself, just wanted to confirm if there was any native feature for cleaning up on cluster delete, but looks like there is not. Seems there is no cluster deletion prevention either- apart from restricting permissions of course

**Comment by spew** [comment]
Correct, thank you for working around this limitation. Closing for now -- please reopen if there are more questions.
