### ISSUE TITLE
UrlMap resource cannot identify the link to backend service

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#36]
As part of configuring UrlMap I was attempting to link existing backend service, however that reference was not recognized, even though backend service was already configured:

```apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeURLMap
metadata:
  name: node-app-url-map
spec:
  defaultServiceRef:
    name: node-app-backend-service
    kind: ComputeBackendService
```

**Comment by kibbles-n-bytes** [comment]
I cannot reproduce this behavior with the latest version. Feel free to open a new issue if you're still having problems.
