### ISSUE TITLE
Support for Dataproc Cluster

### ISSUE THREAD

**Issue by anmoel** [GoogleCloudPlatform/k8s-config-connector#365]
Hello,

we want to create [Dataproc Cluster](https://cloud.google.com/dataproc) with config-connector.

kind regards
André

**Comment by caieo** [comment]
Hi @anmoel, thanks for requesting this resource. We've added it to our queue for resource requests and will update this thread for more information. If you need support for this resource urgently, please elaborate your reason and the expected timeline for it.

**Comment by jcanseco** [comment]
Closing. This is supported on KCC now.
