### ISSUE TITLE
GKE Config connector error during resource upload: unknown field "spec.resourceID"

### ISSUE THREAD

**Issue by michaelnorris1** [GoogleCloudPlatform/k8s-config-connector#372]
Hello!

I am following this guide to try to keep a YAML template of some of our cloud resources. We are interested in the storage buckets, pubsub topics, pubsub subscriptions, and their related IAM policies.
https://cloud.google.com/config-connector/docs/how-to/getting-started?hl=en

I used the bulk export to download our project's current resources, and copied out the relevant ones.
https://cloud.google.com/config-connector/docs/how-to/import-export/bulk-export

I see that the buckets, topics, and subscriptions have a resourceID field in this exported data. When I try to upload some of the resources I have exported as a sort of echo test with `kubectl apply -f aps-sap.yaml` (where `aps-sap.yaml` contains the downloaded data), I get this error:
```
Error from server: error when creating "aps-sap.yaml": admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.resourceID"
```
The IAM policies print this, so it looks like those succeed:
```
iampolicy.iam.cnrm.cloud.google.com/boomi-bucket-dev-iampolicy unchanged
```
Why does it cause an error to import a subset of what I exported? Based on this link, it sounds like a user-created resource should be getting acquired by the Config Connector successfully.
https://cloud.google.com/config-connector/docs/how-to/managing-resources-with-resource-ids?hl=en#acquiring_a_resource_with_the_resourceid_field

**Comment by spew** [comment]
Hello @michaelnorris1, resourceID is a new feature of config connector that enables you to define a `metadata.name` value for your K8s config connector resource that differs from the name or resourceid of the associated GCP resource. This feature was recently added to config connector.

In this case, it seems like the version of the `config-connector bulk-export` you are using is ahead of the version of config connector you have installed on your cluster. You can downgrade your `config-connector` to match your cluster version by doing the following:


```
CC_VERSION=$(kubectl get StatefulSets -n cnrm-system -o=jsonpath="{.items[0].metadata.annotations['cnrm\.cloud\.google\.com/version']}")
gsutil cp gs://cnrm/${CC_VERSION}/cli.tar.gz .
```

**Comment by michaelnorris1** [comment]
Thanks @spew, that worked! The error I get now is related to immutable fields like `the IAMPolicy's spec.resourceRef is immutable`, but this sounds like expected behavior. I think at this point the upload should work on a separate project.
