### ISSUE TITLE
kubectl applies resources, but can't find where they got applied.

### ISSUE THREAD

**Issue by michaelnorris1** [GoogleCloudPlatform/k8s-config-connector#373]
Hello,

After the resolution of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/372, I can now upload the exported YAML file without any errors (hooray!). Now, these lines print which match all resources in the file:
```
iamserviceaccount.iam.cnrm.cloud.google.com/boomi-aps created
storagebucket.storage.cnrm.cloud.google.com/boomi-bucket-uat created
iampolicy.iam.cnrm.cloud.google.com/boomi-bucket-uat-iampolicy created
pubsubtopic.pubsub.cnrm.cloud.google.com/boomi-to-aps created
pubsubsubscription.pubsub.cnrm.cloud.google.com/boomi-to-aps-push created
iampolicy.iam.cnrm.cloud.google.com/boomi-to-aps-iampolicy created
```
However, I can't find these resources in the project. When I type `gcloud init`, the `project` that gets printed matches the name of the project in GCP. However, I cannot find the bucket, subscription, or topic in that GCP project.

I realize there could be multiple wrong things I'm doing. Is there another option I should be setting so I can view these in the UI? I chose a namespace with the exact same name as my project, instead of using the "default" one.

**Comment by spew** [comment]
Hi @michaelnorris1 one thing you can do is describe the resources in config connector and see which project id annotation they have which may clear some things up.

Try `kubectl get pubsubtopic boomi-to-aps -o yaml` and see what value there is for `.metadata.annotations` on the `cnrm.cloud.google.com/project-id` annotation.
