### ISSUE TITLE
Bug: Deleting a Namespace breaks KCC in namespace mode

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/k8s-config-connector#375]
**Describe the bug**
If KCC is in namespace mode, with ConfigConnectorContext defined in namespace X and you `kubectl delete namespace X` the ConfigConnectorContext gets deleted before the other resources, which causes all the kcc resources in that namespace to block on a finalizer that hangs forever, blocking deletion of the namespace. 

**ConfigConnector Version**
1.31.1

I don't know how this should be fixed, but the workaround seems to require editing every resource to remove the finalizer and then deleting them. Force delete doesn't work.

**Comment by karlkfi** [comment]
Deleting the finalizers wasn't good enough.
I had to also mark the resources as abandoned.

```
#!/bin/bash

# Remove the finalizers and abandon every gcp resource in a namespace

set -o errexit -o nounset -o pipefail

NAMESPACE=${1:-}
if [[ -z "${NAMESPACE}" ]]; then
  echo "Syntax: $0 <namespace>"
  exit 1
fi

RESOURCES=$(kubectl get gcp --show-kind --no-headers --ignore-not-found -n "${NAMESPACE}" \
  | cut -d' ' -f1)

while IFS='' read -r resource; do
    echo "Definalizing: ${resource}"
    kubectl patch -n "${NAMESPACE}" --type merge -p '{"metadata":{"annotations":{"cnrm.cloud.google.com/deletion-policy":"abandon"},"finalizers":null}}' "${resource}"
    echo "Deleting: ${resource}"
    kubectl delete -n "${NAMESPACE}" "${resource}" --ignore-not-found
done <<< "${RESOURCES}"
```

**Comment by spew** [comment]
Thanks for reporting this @karlkfi it seems like the ConfigConnectorContext should have a finalizer which verifies that all config connector CRs are removed from the namespace before allowing itself to finalize (understanding there may be some race conditions but that would solve most of the problem).

**Comment by spew** [comment]
admission webhook to block new resources would get around the racy issues.

**Comment by spew** [comment]
Do we get blocking for free? Something to follow up with and find out.

**Comment by toumorokoshi** [comment]
> An admission webhook to block new resources from being created would get around race conditions, however, it is possible that the API server blocks new resources in a namespace marked for deletion. That is something for follow up.

Looks like Kubernetes will reject new resources in deleted namespaces:

```
Error from server (Forbidden): error when creating "./examples/gh-375/create.yaml": secrets "secret-sa-sample-2" is forbidden: unable to create new content in namespace gh-375 because it is being terminated
```

**Comment by karlkfi** [comment]
Right, so if the namespace is being deleted you can't re-create the ConfigConnectorContext to fix the problem. You have to delete all the finalizers instead.

**Comment by spew** [comment]
This is fixed in 1.53.0

**Comment by karlkfi** [comment]
How was this fixed exactly?

**Comment by spew** [comment]
The visible behavior is documented here: https://cloud.google.com/config-connector/docs/how-to/advanced-install#configure_to_no_longer_manage_resources_in_your_namespace

Internally, the `config-connector-operator` which is responsible for managing the Config Connector installation, adds a finalizer to the ConfigConnectorContext object, when that object is deleted, the `config-connector-operator` will not "finalize" the deletion until all KCC resources in the Context's namespace are removed. While in this state, the operator does not kill any of the manager pods so the customer is free to delete any KCC resources.

When deleting a namespace, the ConfigConnectorContext in the namespace is also deleted. That deletion will not finalize until all the KCC resources are deleted.

**Comment by karlkfi** [comment]
Awesome! Thanks for explaining. :+1:
