### ISSUE TITLE
Add support for GlobalAddress

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#38]
Declarative way to provision global address is part of enabling fully declarative multi-cluster ingress scenario. Adding this issue to track adding this support.

**Comment by axisofentropy** [comment]
It looks like this is implemented now?

**Comment by caieo** [comment]
Yes, it was added in release 0.3.0. Documentation on Global Compute Address can be found [here](https://cloud.google.com/config-connector/docs/reference/resources#computeaddress). Thank you for noticing this open issue, I will go ahead and close it!
