### ISSUE TITLE
Add .status.errorResult and .status.state to BigQueryJob

### ISSUE THREAD

**Issue by kanterov** [GoogleCloudPlatform/k8s-config-connector#381]
There is no way to determine if a BigQuery job has successfully finished by looking into `.status`. field. DataflowJob has `.status.state` for that purpose. We can extend BigQueryJob `.status.state` and `.state.errorResult` similarly to [JobStatus in BigQuery API][1].

[1]: https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobStatus

**Comment by maqiuyujoyce** [comment]
Hi @kanterov , thank you for your suggestion. We'll be looking into prioritizing it. Meanwhile, do you mind sharing how urgent or important this feature is for you?

**Comment by kanterov** [comment]
Hi @maqiuyujoyce. Thanks for the prompt response. I'm working on a Config Connector plugin for https://github.com/flyteorg/flytepropeller. It's k8s operator for workflow orchestration system called Flyte (https://flyte.org/). There are open-source plugins for Spark, Hive, Presto, etc. I want to add support for BigQuery and Dataflow, and eventually open-source it.

I already got it working for Dataflow jobs using "classic" templates. For Dataflow jobs, I relied on `.status.state` field to see if the job is finished. However, the BigQuery plugin doesn't work as expected, because it doesn't determine if a BigQuery job is finished or not. Given that, this feature is required to finish the BigQuery plugin. If there is a way how I can contribute to Config Connector, I'm happy to help with that. You can contact me at `gleb` at spotify.com.

**Comment by maqiuyujoyce** [comment]
Hi @kanterov , thank you for your clarification. The `BigQueryJob` is supported on top of the Terraform resource, `google_bigquery_job`, so I just filed a [enhancement request](https://github.com/hashicorp/terraform-provider-google/issues/8357) to them. Will keep you posted when we have any updates.

**Comment by kanterov** [comment]
Hi @maqiuyujoyce. I got help with the pull request for enhancement in Terraform resource, and now it's merged. I am wondering if at this point Config Connector part becomes something that can be prioritized soon?

**Comment by maqiuyujoyce** [comment]
Hi @kanterov , thank you so much for contributing to the Terraform resource! As long as your PR is released (releases are posted [here](https://github.com/hashicorp/terraform-provider-google/releases), and seems that your change will be released next week), we will have it merged into Config Connector and then have it released. The entire process might take a couple of to a few weeks. We'll try to align better on the timeline and minimize the time of the process. Will keep you posted.

**Comment by maqiuyujoyce** [comment]
Hi @kanterov , now you should be able to retrieve the `state` and `errorResult` of the BigQueryJob in Config Connector via `status.status.state` and `status.status.errorResult`. Note that the first `status` is the subresource of Config Connector CR, and the second `status` is the one [added to the Terraform resource](https://github.com/hashicorp/terraform-provider-google-beta/pull/2926).

**Comment by kanterov** [comment]
@maqiuyujoyce thanks! didn't check it out yet because we haven't yet upgraded our deployment
