### ISSUE TITLE
Support for Cloud SQL Query Insights

### ISSUE THREAD

**Issue by jcanseco** [GoogleCloudPlatform/k8s-config-connector#399]
**Describe the feature or the resource that you want.**

Context: see https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/386

Cloud SQL for PostgreSQL recently added a feature known as [Query Insights](https://cloud.google.com/sql/docs/postgres/insights-overview). The [API docs](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#Settings) for `SQLInstance` don't yet document how to configure this feature via the API, but the API presumably exposes a `settings.insightsConfig` field based on the sample request body [on this page](https://cloud.google.com/sql/docs/postgres/using-insights#rest-v1).

**Comment by ve6yeq** [comment]
The upstream changes have been made - what needs to be done to import the changes here?

**Comment by jcanseco** [comment]
Hi @ve6yeq, now that Terraform released the feature as part of their `v3.58.0` release, it should be brought over to Config Connector once we upgrade our Terraform dependency. This means that, assuming there are no issues with the dependency upgrade, the feature should come out on Config Connector within the next couple of releases.

**Comment by maqiuyujoyce** [comment]
`insightsConfig` field in `SQLInstance` is now supported in [v1.41.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.41.0).

**Comment by maqiuyujoyce** [comment]
In [v1.41.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.41.0), `insightsConfig` field is supported in `SQLInstance`.
