### ISSUE TITLE
User guide refers to non-existing file release-configuration.yaml

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#4]
In user guide:
```
kubectl apply -f samples/apps/bookstore/config/release-configuration.yaml
```
The file does not exist

@kibbles-n-bytes

**Comment by OchiengEd** [comment]
Hi Alex,

Just looked into the issue you raised. If you clone the repository the path will not match. However, if you follow the steps in the **Downloading the samples** section, then the steps are accurate.

**Comment by kibbles-n-bytes** [comment]
Hey Alex,

As @OchiengEd points out, this file is not included in the repo itself, but is assembled dynamically and included in the tarball during releases. We recompile every so often to keep our base image up-to-date.
