### ISSUE TITLE
Support for container node-pools ephemeral storage

### ISSUE THREAD

**Issue by neuromantik33** [GoogleCloudPlatform/k8s-config-connector#400]
Is is possible to request features that are still in Beta such as [ephemeral storage](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/local-ssd#creating_a_node_pool_using_ephemeral_storage_on_local_ssds)

Thanks in advance

Nicolas

**Comment by maqiuyujoyce** [comment]
It's supported since Config Connector [v1.44.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.44.0).
