### ISSUE TITLE
Config Connector should output kstatus-compatible resource status

### ISSUE THREAD

**Issue by toumorokoshi** [GoogleCloudPlatform/k8s-config-connector#410]
Today, Config Connector does not include some of the fields and behavior to be compatible with [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus), which is becoming a standard for querying resource status.

Some specific requirements:

- The ready status should reflect whether the resource has been reconciled to the desired state or not, as specified in #387.
- Adding support for the [observedGeneration field](https://googlecontainertools.github.io/kpt/reference/live/apply/#recommendations-for-crds).

**Comment by toumorokoshi** [comment]
Update: this is is currently being investigate, to be delivered near the end of Q1 (March / April)

**Comment by snuggie12** [comment]
@toumorokoshi Do you want additonal issues for other resources? I experienced this on a GCS bucket recently.

**Comment by toumorokoshi** [comment]
Hi! I would suggest just adding +1 reactions to this issue: if we perform
this work it will be applicable for all resources.

**Comment by toumorokoshi** [comment]
As an update: `observedGeneration` is now supported by KCC. I'll close this ticket as #387 is tracking the other issue (ready state flapping, which is not specific to kstatus)
