### ISSUE TITLE
Resource Request: Support GKE Autopilot cluster resources

### ISSUE THREAD

**Issue by JamesDuncanNz** [GoogleCloudPlatform/k8s-config-connector#411]
This request is to support the ability to manage [GKE Autopilot](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-an-autopilot-cluster#create_an_autopilot_cluster) cluster resources.

Relevant gcloud command is: `gcloud container clusters create-auto CLUSTER_NAME --region REGION --project=PROJECT_ID`

**Comment by toumorokoshi** [comment]
Thanks for the request! We'll take a look and try to get back with an ETA.

Taking a quick glance, it seems the enabling autopilot [is a flag in the API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.zones.clusters).

**Comment by JohanWork** [comment]
Is there any update to the ETA @toumorokoshi

**Comment by toumorokoshi** [comment]
Hi! Currently our ETA (tentative) is in about a month (end of April). I'll try to update if that changes.

**Comment by jwhitlark** [comment]
Hi @toumorokoshi.  I'm also very interested in this feature.  I'm writing a book about developing for Kubernetes, and I *really* want to use autopilot as the main environment, so that I don't need to cover nearly as much ground on teaching Kubernetes administration.  Is there an updated ETA, and is there anything I might contribute to in order to help?

**Comment by JohanWork** [comment]
I belive it already is live if you check here https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster @jwhitlark

**Comment by toumorokoshi** [comment]
> I belive it already is live if you check here https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster @jwhitlark

Correct! It is live as of [1.46.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.46.0) (add-on can be behind so make sure to double-check the version).

Apologies for not closing the issue, I'll do so now.

**Comment by yspreen** [comment]
So how would you enable it? All I'm getting is 

```
gcloud container clusters update $CLUSTER \
    --update-addons ConfigConnector=ENABLED
ERROR: (gcloud.container.clusters.update) INVALID_ARGUMENT: Addons {"config-connector"} are not supported for Autopilot clusters.
```

**Comment by yspreen** [comment]
I'm on 1.20, and this is the web interface info:
![image](https://user-images.githubusercontent.com/12631527/130333147-7027fbce-db9f-4343-9195-4d08439ba113.png)

**Comment by toumorokoshi** [comment]
Hello! Sorry, to clarify: this is the ticket to support the *creation* of GKE Autopilot clusters, rather than supporting enabling ConfigConnector on GKE autopilot clusters.

I'll author a second ticket to clarify.
