### ISSUE TITLE
Deletion fails for folders which are already deleted

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/k8s-config-connector#416]
## Bug Description

If a KCC-managed folder is deleted out of band (ex. through `gcloud`) KCC will fail to delete it when deleting the Kubernetes resource. Finalizers block deletion forever and have to be manually removed.

This is the error from the KCC status:
```
Delete call failed: error fetching live state: error reading underlying resource: summary: Error when reading or editing Folder Not Found : folders/218601082279
```

If KCC is attempting to delete a folder which doesn't exist, it should treat that as a no-op and simply proceed.

### Config Connector Version

```
1.39.0
```

**Comment by maqiuyujoyce** [comment]
Hi @morgante , thank you for reporting the issue. Is this issue consistently happening? I tried the following steps on v1.39.0, but couldn't reproduce it (the Folder resource was deleted successfully). Is there any additional step I missed?

1. Create a new GCP Folder via Config Connector.
2. Delete the GCP Folder on Cloud Console.
3. Delete the Folder resource via Config Connector.

**Comment by morgante** [comment]
It was happening on many folders before but I can't seem to reproduce now. I will reopen if it happens again, thanks for investigating.
