### ISSUE TITLE
SQLInstance missing support for transactionLogRetentionDays

### ISSUE THREAD

**Issue by isaacseymour** [GoogleCloudPlatform/k8s-config-connector#419]
**Describe the feature or resource**
The [SQLInstance](https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance) resource does not have an option for setting `transactionLogRetentionDays`. This is available [in the REST API](https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1beta4/instances#backupconfiguration)

**Importance**
This is a pain point, since this setting can be modified in the GCP Console, but when it's not in the config-as-code there's no documentation about what the setting should be and why.

**Comment by maqiuyujoyce** [comment]
Hi @isaacseymour , thank you for your request. We'll be looking into prioritizing it.

Just to share some context - The `SQLInstance` resource is supported on top of the Terraform resource, `google_sql_database_instance`, and Config Connector will support `transactionLogRetentionDays` after the TF resource supports it. Currently there is an [open enhancement request](https://github.com/hashicorp/terraform-provider-google/issues/7980) for supporting this particular field. Will keep you posted when we have any updates.

**Comment by isaacseymour** [comment]
Aha! Looks like that request is being [closed](https://github.com/hashicorp/terraform-provider-google/pull/8582) in the unreleased version of the terraform provider, so hopefully that won't be a blocker for much longer! Thanks for the speedy reply :)

**Comment by isaacseymour** [comment]
Looks like this was added to the Google Terraform provider in [3.60.0](https://registry.terraform.io/providers/hashicorp/google/3.60.0/docs/resources/sql_database_instance#transaction_log_retention_days). Is there another issue I should be following to track when that update will be included in config-connector?

**Comment by maqiuyujoyce** [comment]
Hi @isaacseymour , `transactionLogRetentionDays` in SQLInstance has been supported in Config Connector [1.44.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.44.0). Please let us know if you have any additional questions.

**Comment by isaacseymour** [comment]
Oh amazing! Thanks!
