### ISSUE TITLE
Multiple Namespaces for multiple tenants

### ISSUE THREAD

**Issue by axisofentropy** [GoogleCloudPlatform/k8s-config-connector#43]
We're exploring Config Connector for a multi-tenant cluster, but I saw this limitation:

> To function correctly, the GCP project and the destination Kubernetes Namespace must have the same name.

Is it possible to use Config Connector for many namespaces within the same GCP Project?

This may or may not be related to #26

**Comment by spew** [comment]
Hello, 

Sorry you ran into this. You can configure your namespace to point to a different project by following the instructions here under "Annotate your Namespace with Config Connector's project ID":

https://cloud.google.com/config-connector/docs/how-to/setting-default-namespace

**Comment by axisofentropy** [comment]
Thanks @spew ! So I can set up many namespaces, one for each client, and then annotate all of them with the same project ID?

**Comment by spew** [comment]
Yes you can.

**Comment by axisofentropy** [comment]
Oh, what kind of conflicts? You mean they can create resources with colliding ID's? We'll be creating resources on behalf of our tenants so hopefully we can prevent that ourselves.

Is there some other risk too?

**Comment by spew** [comment]
That is the primary / only risk. That resources are created with the same IDs.

**Comment by spew** [comment]
Closing -- please reopen if there are more questions.
