### ISSUE TITLE
Issue creating StorageBucket Notification because of permissions

### ISSUE THREAD

**Issue by RoryShively** [GoogleCloudPlatform/k8s-config-connector#433]
I'm trying to create a storagebucketnotification with config connector but getting a permissions error

Heres the output I get from `kubectl -n cnrm-system logs cnrm-controller-manager-0 -c manager`:
```
{"severity":"error","logger":"controller-runtime.manager.controller.storagenotification-controller","msg":"Reconciler error","reconciler group":"storage.cnrm.cloud.google.com","reconciler kind":"StorageNotification","name":"my-project-name-logs-cloud-green","namespace":"default","error":"Update call failed: error applying desired state: summary: Error creating notification config for bucket my-project-name-cloud-logs_cloud: googleapi: Error 403: The service account 'service-801025423570@gs-project-accounts.iam.gserviceaccount.com' does not have permission to publish messages to to the Cloud Pub/Sub topic '//pubsub.googleapis.com/projects/my-project-name/topics/my-project-name-logs-cloud-green', or that topic does not exist., forbidden, detail: "}
```

The pubsub topic does indeed exist and following the troubleshooting guide at https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#troubleshooting-permissions-for-resource-reconciliations I can verify that I'm setup for worload identity.

I am not able to give my service account `owner` or `editor` permissions for security reasons but I have given it these permissions which I think would be enough to create a storage bucket notification
- BigQuery Admin
- Logging Admin
- Monitoring Viewer
- Pub/Sub Admin
- Pub/Sub Editor
- Storage Admin
- Storage Object Admin
- Storage Object Creator

Is there any roles Im missing that are needed or anything else I should look into?

**Comment by RoryShively** [comment]
Also looking through the examples Im not sure what role the IAMPolicyMember in this sample plays and if it's necessary. If so do you know what roles I would need to deploy this resource as well?

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/samples/resources/storagenotification/storage_v1beta1_storagenotification.yaml

**Comment by RoryShively** [comment]
Answered my own question. IAMPolicyMember was needed

**Comment by jcanseco** [comment]
Hi @RoryShively, yes you're correct. I'm glad that you were able to resolve your issue.

For others who may have the same question: you need to give your project's [GCS Service Agent](https://cloud.google.com/storage/docs/projects#service-agents) the IAM role `roles/pubsub.publisher` on the target `PubSubTopic` (e.g. see [the IAMPolicyMember in our StorageNotification sample](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/f7bb580befdba4cfab55bf7b7cf3a75b97645ce2/samples/resources/storagenotification/iam_v1beta1_iampolicymember.yaml)).

It was a miss on our part not to call out that requirement more explicitly in our docs/samples. We'll put out a doc update to rectify the issue. Thanks for pointing out this miss, @RoryShively.

**Comment by raphaelarias** [comment]
I'll post here for future reference, for me and other poor souls that come to face the same issue.

In my case, I have Cloud Storage API active, I create a bucket using the Nodejs SDK, but the account is never created. Doesn't matter how long I wait. So I went to IAM & Admin > Add, and add the full service account name there, then I add the Pub/Sub Publisher role. To the best of my knowledge, this is documented nowhere.

**Comment by draeder** [comment]
@raphaelarias Based on my experience with this, the GCS service agent account is created once you invoke the API to create the notification. I find this overall concept of a service agent account unusual since I need no service agent account to use the normal pub/sub API. Only to use storage notifications. This may become a security concern when the application I'm writing hits security review.

Note: The documentation is still not updated.

**Comment by bjornleffler** [comment]
Here's the command line solution for folks that find this bug through Google searching. The command below allows the associated GCS service account to post notifications to all pubsub topics in the project. Change PROJECT to the name of your project and change NUMBER to the project number.

gcloud projects add-iam-policy-binding MYPROJECT --member=serviceAccount:service-NUMBER@gs-project-accounts.iam.gserviceaccount.com --role=roles/pubsub.publisher
