### ISSUE TITLE
Kubernetes Config Connector Support for Pub/Sub Message Schemas

### ISSUE THREAD

**Issue by norlove** [GoogleCloudPlatform/k8s-config-connector#435]
**Describe the feature or resource**
My customer uses Pub/Sub in their environment today, and thus far, in order to sanitize the messages published into Pub/Sub topics, they have had AVRO schemas baked into the producers of the messages. This is messy for multiple reasons. Chief among which, is that there is no single source of truth in the system for what is the current schema. This is why they were thrilled to learn about the new schema support in Pub/Sub [1], which went into preview on March 1st, 2021 [2]. They are already planning on using this new feature in their production environment, however as a rule, they follow infrastructure as code best practices. This approach spans Kubernetes resources as well as GCP resources, and their tool for infrastructure as code is KCC. Seeing that Pub/Sub Message Schemas are not supported by KCC, the work around is to have a custom kubernetes job, using the Google cloud SDK docker image, to instantiate and manage the schema resources, as well as the pub/Sub topics that use them. This is far from ideal.

**Importance**
This lack of support makes my customer's management harder, so this would be greatly appreciated. However this is probably more of a P2 since a work around exists. 

[1] https://cloud.google.com/pubsub/docs/schemas
[2] https://cloud.google.com/pubsub/docs/release-notes#March_01_2021

**Comment by jcanseco** [comment]
Hi @norlove, thanks for the feature request and the details you've provided regarding the customer impact and priority. I've added it to our resource request backlog, and we'll update you once we have more information.

**Comment by norlove** [comment]
Hey Jazel,
Wanted to check in, any update around supporting Pub/Sub Message Schemas with KCC?

**Comment by caieo** [comment]
HI @norlove, this resource request is in our queue and we are hoping to have it supported sometime in Q3.

**Comment by norlove** [comment]
Hey @caieo any update on this ETA considering we are nearing the end of Q3?

**Comment by jcanseco** [comment]
Update: It seems there has been progress and discussions internally on this issue; let me try to determine if we have a good new ETA.

**Comment by adrieng1977** [comment]
Can there be an update on this?

**Comment by maqiuyujoyce** [comment]
Hi @adrieng1977 , we recently prioritized this feature but at the moment we don't have a good ETA for it. Will post updates once we have an ETA.

**Comment by jcanseco** [comment]
Hi folks, we added support for the `PubSubSchema` resource in [1.89.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.89.0) and added a way to reference it from `PubSubTopic` in [1.90.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.90.0).

Closing. Please comment though if you need anything else.
