### ISSUE TITLE
Unable to upgrade resources .. denied the request: unknown field "spec.resourceID"

### ISSUE THREAD

**Issue by ni-ezakaria** [GoogleCloudPlatform/k8s-config-connector#438]
Hi 

i am unable to update resources with the below error
cannot patch "NAME" with kind DNSManagedZone: admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.resourceID"

Resources affect :

- DNSManagedZone
- SQLInstance
- ComputeAddress
- ContainerCluster

Gke Cluster "v1.18.12-gke.1210".  with addon enabled 
cnrm.cloud.google.com/operator-version=1.31.1

Any help is much appreciated

**Comment by kvokka** [comment]
@ni-ezakaria Can you please share how did you solved this? Regarding [this document](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#upgrading) it should upgrade with the cluster, but it did not, so i'm still on configConnector 1.12 (and cluster is on k8s 1.18.16, so we are almost on the same boat)

I found that it is required to have configConnector at least 1.35 for this operations. I added crd's from that version but it did not help. So i should upgrade configConnector. How did you managed this?

Thank you!

**Comment by ni-ezakaria** [comment]
@kvokka  i had to edit the resorces manually and revmove the "resourceID:" line .
After that i was able to apply my manifests successfully

**Comment by kvokka** [comment]
Thank you for the hint. unfortunately it is not for me, cos i need this update exactly for this feature

**Comment by caieo** [comment]
Hi @kvokka, sorry you ran into this issue! Are you using a GKE cluster? It looks like GKE clusters at versions 1.18.16+ _should_ be tied to ConfigConnector versions 1.39 and above, which should update automatically. 

If you're using a non-GKE cluster, please check out [these instructions](https://cloud.google.com/config-connector/docs/how-to/install-other-kubernetes#upgrading) on how to upgrade ConfigConnector on non-GKE Kubernetes clusters.

**Comment by kvokka** [comment]
Thank you @caieo for clearing things up. 

The trick is that i'm using GKE cluster with GKE version 1.18 and ConfigConnector version 1.12, which was installed following a "Installing on other Kubernetes distributions" guide. ConfigConnector was installed at June of 2020. Looking backwards it seems like it was not possible to install it as a GCP native option at that time.

I did not find any specific instructions about the transition, but it seems that i just should enable it and it will do the magic.
(will manage all this things on Monday)

This auto-update statement in the docs for my case was confusing (or maybe it was just the end of the week)
