### ISSUE TITLE
Any way to determine number DBs in a Spanner instance using KCC?

### ISSUE THREAD

**Issue by marcoderama** [GoogleCloudPlatform/k8s-config-connector#445]
Given the limited number of Spanner DBs per instance, I'd like to determine if the instance has room for a new DB before creating the DB.  Is that possible using Config Connector?

In my experiments, if I create a SpannerDatabase using an external reference to a Spanner instance that has no room left for new DBs, KCC will happily create the SpannerDatabase k8s object.  Eventually the Status for the SpannerDatabase will show that the `UpdateFailed` with a message that includes: 
> ... instance blah has already reached the maximum database limit...

I guess I could watch for that Status but it takes too long to show up for my purposes (upwards of 30 mins now).  I'd rather avoid creating the SpannerDatabase object (in that instance) to begin with.  Any way to do that with vanilla KCC or am I going to have to call out to something like

`gcloud --project gcpproject spanner databases list --instance=theinstance --format='table[no-heading](name)' | wc -l`

I suspect I'm out of luck with KCC but thought I'd ask.  :-)  (fyi, I just created a SpannerInstance object wired to my existing instance and there's nothing in there along these lines.)  Ultimately, I just need a way to quickly determine that "creation of this DB will fail".  Knowing the number of DBs in the instance is just one way to do that.  I'm open to other suggestions.

(Fyi, I'm using CC 1.32 atm.)

**Comment by marcoderama** [comment]
I don't see anything I can use in the Golang client API (https://pkg.go.dev/cloud.google.com/go/spanner).  The RPC and REST APIs look more promising:

RPC API: https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.admin.database.v1#google.spanner.admin.database.v1.DatabaseAdmin.ListDatabases
REST method: https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases/list

**Comment by maqiuyujoyce** [comment]
Hi @marcoderama , thank you for your question! Unfortunately, KCC doesn't support checking quotas/resource limitations before applying the resources. One alternative is that you can use a customized controller to manage quotas. [Gatekeeper policy](https://github.com/open-policy-agent/gatekeeper) could also be an option.

**Comment by marcoderama** [comment]
Thanks for the response.  I'll consider your suggestions but have a clunky solution in place atm.

Feel free to close this.
