### ISSUE TITLE
Support of Pub/Sub by CloudBuildTrigger

### ISSUE THREAD

**Issue by evgenybenchsci** [GoogleCloudPlatform/k8s-config-connector#447]
It is possible to configure Pub/Sub topic as build trigger using the console, however, CloudBuildTrigger lacking this functionality.

There is a scenario, where we have to use Pub/Sub message to trigger the build. The whole infrastructure uses ConfigConnector, so it is painful to create this specific trigger manually. Is it possible to extend CloudBuildTrigger to match functionality provided by the managed resources?

**Comment by maqiuyujoyce** [comment]
Hi @evgenybenchsci , thank you for your request. Once the pubsub trigger is supported in the Terraform resource ([issue #8692](https://github.com/hashicorp/terraform-provider-google/issues/8692)), then we will be able to support it in Config Connector. We will post updates when we have new information.

**Comment by tonybenchsci** [comment]
@maqiuyujoyce Is it always going to be Terraform resource lags GCP API, and KCC resource lags Terraform resource? One would think that KCC being google internal would be ahead of Terraform. Just curious how the behind the scenes of resource support roll out works :)

**Comment by xiaobaitusi** [comment]
Hi @tonybenchsci, KCC has been in a process of migrating off Terraform to another actuation engine, so for new resource added in KCC, we will not expect the intermediate lag from Terraform.

**Comment by mikelnrd** [comment]
> Hi @tonybenchsci, KCC has been in a process of migrating off Terraform to another actuation engine, so for new resource added in KCC, we will not expect the intermediate lag from Terraform.

Is this migration documented anywhere? I'd be interested to read more about the new actuation engine. Thanks.

**Comment by xiaobaitusi** [comment]
> Is this the new actuation engine? https://github.com/GoogleCloudPlatform/declarative-resource-client-library

Yes, this is the new actuation engine used by KCC.

**Comment by tonybenchsci** [comment]
Any idea when pubsub triggered cloudbuildtriggers will be supported? (regardless if terraform or DCL)

**Comment by tonybenchsci** [comment]
@maqiuyujoyce @xiaobaitusi We have installed KCC v1.58.0, which supports `spec.pubsubConfig`. However it doesn't support `spec.filter` which is almost always used with pubsub-based triggers. Is that planned?

**Comment by jcanseco** [comment]
Hi @tonybenchsci, thanks for raising this up. This one's likely just an oversight. Filed the appropriate issue against TF at https://github.com/hashicorp/terraform-provider-google/issues/9755.

**Comment by tonybenchsci** [comment]
Thanks @jcanseco ! Another issue: the schema only allows one of `spec.github` OR `spec.pubsubConfig`. However, GCP expects both to be set (the github repo and branch are required), so it's currently unusable.

**Comment by jcanseco** [comment]
No problem @tonybenchsci!

Re: new issue: This one is interesting since I can see that it should be possible to create a pubsub-based trigger that builds a GitHub repo using the UI (correct me if I'm wrong).

However, if I try to create a `CloudBuildTrigger` with both fields specified, we get the following error which seems to be coming from the API (judging by the `googleapi` string):

```
Update call failed: error applying desired state: summary: Error creating Trigger: googleapi: Error 400: cannot set more than one trigger config, detail:
```

Let me check with the Cloud Build team internally to see what's going on here.

**Comment by jrmanes** [comment]
Hello!

Any news about that issue or any workaround to configure? :S

**Comment by jcanseco** [comment]
Hi @jrmanes. We don't have an update for you yet, unfortunately. Once Terraform implements the field, we can bring it over to KCC. We'll update this thread accordingly once we add support.

**Comment by bharathkkb** [comment]
@jcanseco any updates on this?

**Comment by jcanseco** [comment]
Hi @bharathkkb, none yet unfortunately as it seems Terraform hasn't picked up the [request](https://github.com/hashicorp/terraform-provider-google/issues/9883) yet (their team is quite overloaded right now as I understand).

**Comment by jcanseco** [comment]
Hello folks, it seems we now support both `sourceToBuild` in [KCC 1.79.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.79.0). Closing.
