### ISSUE TITLE
Webhook requires resourceRef fields that are not available

### ISSUE THREAD

**Issue by poy** [GoogleCloudPlatform/k8s-config-connector#448]
## Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

While trying to create an `IAMPolicy`, I created a struct that looks like the following:

```
&v1beta1.IAMPolicy{
	ObjectMeta: metav1.ObjectMeta{
		Name: gsaName,
	},
	Spec: v1beta1.IAMPolicySpec{
		ResourceRef: k8sv1alpha1.ResourceRef{
			External: fmt.Sprintf("projects/%s/serviceAccounts/%s@%s.iam.gserviceaccount.com", project, gsaName, project),
		},
		Bindings: []v1beta1.PolicyBindings{
			{
				Role: "roles/iam.workloadIdentityUser",
				Members: []string{
					fmt.Sprintf("serviceAccount:%s.svc.id.goog[nnn/xxx]", project),
				},
			},
		},
	},
}
```

I then tried to convert this to YAML and apply it via `kubectl`. However, this fails:

```
The IAMPolicy "<redacted>" is invalid: spec.resourceRef.kind: Required value
```

However, looking at the `v1alpha1.ResourceRef` struct, this isn't a field I can actually set:
```
type ResourceRef struct {
	External string `json:"external,omitempty"`
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
}
```

NOTE: Looking at the docs, it appears that there are a few other fields I should be able to set.

### Config Connector Version

v1.42.0

### Config Connector Mode

clusteer

### YAML snippets

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    label-one: "value-one"
  name: pubsubtopic-sample
```

**Comment by maqiuyujoyce** [comment]
Hi @poy , thank you for reporting the issue. It's a known bug (#413) and we are actively working on it. I'll close this one and please track #413 for updates.
