### ISSUE TITLE
Support Logging Bucket

### ISSUE THREAD

**Issue by evgenybenchsci** [GoogleCloudPlatform/k8s-config-connector#454]
To allow the use of LoggingLogSink with Logging Bucket it would be great to add support for Logging Bucket resource. It looks like the required functionality already supported by Terraform. Since there are several types of Logging Buckets, the preference is for the project-level bucket.

Currently, ConfigConnector does not allow configuring LogSink with LogBucket, so we will need to manage it manually (or using scripts).

**Comment by caieo** [comment]
Hi @evgenybenchsci, thanks for your resource request. We have this resource in our queue and might have it supported by June. We will update this thread for more information and updates.

**Comment by evgenybenchsci** [comment]
Hi @caieo Thanks for the prompt response.

**Comment by cNULLde** [comment]
Hi, is there a timeline for LoggingBucket already? Thanks in advance!

**Comment by caieo** [comment]
Hi @cNULLde, unfortunately our original timeline was pushed back. Our current ETA for this resource is now hopefully near the end of Q3. We'll post future updates in this thread.

**Comment by RenePinnow** [comment]
Any updates on this?

**Comment by caieo** [comment]
Hi @RenePinnow, sorry for the delay, but due to some blockers and limited bandwidth on our team, the ETA on this resource was pushed back again. We'll be hoping to have it supported by 2022 Q1. If this timeline does not work out for you, you can raise the priority by filing an issue with GCP support, where we can get some more info to reprioritize it.

**Comment by RenePinnow** [comment]
@caieo 
I see that you added logingLogBuckets but LoggingLogSink is not yet updated to use them. When do you expect this update?

**Comment by RenePinnow** [comment]
@mbzomowski 
Can you give any status for this? #455 is still missing.

**Comment by mbzomowski** [comment]
Hi @RenePinnow we are still tracking this, sorry for the delay. No updates as of yet, but it now looks like this functionality will be added in Q2.

**Comment by diviner524** [comment]
This is added in v1.80.0

https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.80.0
