### ISSUE TITLE
Support Logging Bucket as LoggingLogSink destination

### ISSUE THREAD

**Issue by evgenybenchsci** [GoogleCloudPlatform/k8s-config-connector#455]
To allow the use LoggingLogSink with Logging Bucket it would be great to add Logging Bucket to the list of LoggingLogSink's destinations. It looks like the required functionality already supported by Terraform.

Currently, ConfigConnector does not allow configuring LogSink with LogBucket, so we will need to manage it manually (or using scripts).

**Comment by caieo** [comment]
Hi @evgenybenchsci, thanks for bringing this enhancement to our attention. When we implement `LoggingBucket` (https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/454), we will make sure that `LoggingLogSink` can reference it. We will update this thread for more information.

**Comment by evgenybenchsci** [comment]
Hi @caieo Thanks for the prompt response.

**Comment by diviner524** [comment]
This is added in v1.80.0. Note that only `external` field is supported to configure the reference.

https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.80.0
