### ISSUE TITLE
IAMServiceAccount support for resourceID

### ISSUE THREAD

**Issue by vglocus** [GoogleCloudPlatform/k8s-config-connector#456]
**Describe the feature or resource**
I wish to create IAMServiceAccount with a separate account id (part before @) than meta data name (which is used to reference the resource from others)

There is already the concept of [resourceID](https://cloud.google.com/config-connector/docs/how-to/managing-resources-with-resource-ids) for several other resources. 

I would like to have the same support in IAMServiceAccount.

**Importance**
A nice-to-have or pain point.

I want to generate an IAMServiceAccount together with a set of resources of varying kind, like IAMPolicyMember referring to it. The account id is variable but I need to refer and find the resource.

It would help greatly to be able to look for this resource with (name,namespace) where name can be static like ("workflow-service-account", "my-namespace-1").

The workaround will have to be to find all service accounts for the namespace, try to identify which I am looking for by labels or annotations.

Being able to do this by name would be beneficial as direct lookup but also enforce uniqueness of the resource.

**Comment by caieo** [comment]
Hi @vglocus, thank you for requesting this enhancement and sorry for any pain this lack of IAMServiceAccount resourceID has caused. We encountered a blocker while implementing resourceID support for IAMServiceAccount and have it on our radar to support. Unfortunately, we don't have an ETA to provide you, but we will make sure to update this issue when the feature is supported.

**Comment by vglocus** [comment]
Thank you for your response.

I have a workaround in place which works, albeit slightly ugly. 

Good to know that it is on the radar.

**Comment by xiaobaitusi** [comment]
`IAMServiceAccount` supports resourceID since https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.52.0
