### ISSUE TITLE
Download link for v0.1.7 is broken

### ISSUE THREAD

**Issue by calind** [GoogleCloudPlatform/k8s-config-connector#47]
Following the documentation at https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#installing_kcc and issuing 
```
curl -X GET -sLO \
  -H "Authorization: Bearer $(gcloud auth print-access-token)" \
  --location-trusted \
  https://us-central1-cnrm-eap.cloudfunctions.net/download/latest/infra/install-bundle.tar.gz
```
returns a borken link:
```xml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: cnrm-eap/0.1.7/infra/install-bundle.tar.gz</Details></Error>
```

**Comment by AlexBulankou** [comment]
Thanks for reporting, @calind! I can reproduce - navigating `https://us-central1-cnrm-eap.cloudfunctions.net/download/latest/infra/install-bundle.tar.gz` to directs to `https://storage.googleapis.com/cnrm-eap/0.1.7/infra/install-bundle.tar.gz`. 

While we are fixing it as workaround please use `https://storage.googleapis.com/cnrm-eap/0.1.6/infra/install-bundle.tar.gz`

**Comment by kibbles-n-bytes** [comment]
Hey calind, we have now fixed the problems with the latest release. Please try again with the original URL, and let us know if you have any further issues.

**Comment by destroy-everything** [comment]
Having the same issue again
