### ISSUE TITLE
Update SecretManagerSecret to include support for setting expiration and rotation policies

### ISSUE THREAD

**Issue by tedelwartowski-bestbuy** [GoogleCloudPlatform/k8s-config-connector#471]
The GCP Secret Manager API supports the following which is not part of the **SecretManagerSecret** CRD:
- Expiration policy attached to the Secret. If specified the Secret and all SecretVersions will be automatically deleted at expiration.
-  Rotation policy attached to the Secret.

**Importance**
This would be considered a pain-point as we are automating the creation of secrets and then have to manually update the secret to add a rotation notification or expiration.

**Comment by spew** [comment]
Hello @tedelwartowski-bestbuy thank you for your request. We are prioritizing this one internally and will have a future update.

**Comment by spew** [comment]
Hello @tedelwartowski-bestbuy we are looking into prioritizing this, if this is very important in the near future for you can you work with your GCP account manager to file an issue. This will help raise the priority on our side.

**Comment by gameformush** [comment]
What about adding pub-sub topics notification? Great feature but can't be enabled with CRD hence not really usable for automation :(

**Comment by jcanseco** [comment]
Hi @gameformush, we'll track that one too.

`SecretManagerSecret` is one of our Terraform-based resources, so I've deferred to the Terraform team to add support for the missing fields. It seems that they already had an existing request to add these fields from their users: https://github.com/hashicorp/terraform-provider-google/issues/9195

**Comment by jcanseco** [comment]
Hi @tedelwartowski-bestbuy and @gameformush, we just added support for the `expire`, `rotation`, `topics`, and `ttl` fields in `SecretManagerSecret`  in [KCC 1.56.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.56.0).
