### ISSUE TITLE
Support for BigTable nested Garbage Collection Policy

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [GoogleCloudPlatform/k8s-config-connector#482]
From the documentation https://cloud.google.com/config-connector/docs/reference/resource-docs/bigtable/bigtablegcpolicy looks like nested Garbage Collection Policy for BigTable is not supported. See ref: https://cloud.google.com/bigtable/docs/samples/bigtable-create-family-gc-nested. Is there any plan to release such capabilities?

**Comment by jcanseco** [comment]
Hi @CharmanderJieniJieni, unfortunately, from an initial glance, I don't believe this is something we would be able to support in Config Connector.

Is this issue a blocker for you, or would you consider it more of a friction point?

**Comment by CharmanderJieniJieni** [comment]
Hi @jcanseco, for example below will be a valid use case
`(maxage=7d and maxversions=1) or maxversions=30d`

When we want to keep the latest version for 7 days for compliance reason and delete everything after 30 days.
Since Config Connector is capable to deploy GC policy with both GC modes, it will be really beneficial to enable this feature.

**Comment by jcanseco** [comment]
Gotcha, thanks for elaborating by giving a helpful example, @CharmanderJieniJieni. 

I can bring up the request internally for a discussion, but bear in mind that from what I can see, it will likely be tricky for us to implement this given the existing schema, so any solution will likely take time.

**Comment by CharmanderJieniJieni** [comment]
Hi, just to follow up if any plan on this feature in the roadmap yet?

**Comment by mbzomowski** [comment]
Hi, unfortunately we don't have an update at the moment. We can however give a tentative ETA for this feature of the first half of 2022, although due to our current backlog of resource and feature requests that may need to be pushed further out.

**Comment by kevinsi4508** [comment]
This should be resolved by using [`gc_rules`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_gc_policy#gc_rules). Currently we are waiting for KCC to update to the latest Google Terraform Provider version.

**Comment by mbzomowski** [comment]
`spec.gcRules` has been added to `BigTableGCPolicy` as of Config Connector [v1.97.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.97.0).
