### ISSUE TITLE
Unable to delete resource because of 'unknown field "status.observedGeneration"'

### ISSUE THREAD

**Issue by Nosmoht** [GoogleCloudPlatform/k8s-config-connector#483]
Hi All,

i've a resource which can't be deleted. When i try to delete the resource using `kubectl delete -n <my-namespace> storagebucketaccesscontrol.storage.cnrm.cloud.google.com <my-resource>` the command waits foreverand doesn't work. Not a problem at all. With all other resources where i have that type of problem i simply delete the `finalizers` from the resource. However, with this specific resource it doesn't work. Deleting the `finalizer` ends up in 
```shell
error: storagebucketaccesscontrols.storage.cnrm.cloud.google.com <my-resource-name> could not be patched: admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "status.observedGeneration"
```

I also tried to delete the `status.observedGeneration` field but without sucess. 

How can i delete the resource?

Manifest
```yaml
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: <project-id>
  creationTimestamp: "2021-05-07T14:01:17Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-05-28T08:02:27Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 2
  labels:
  name: <resource-name>
  namespace: <namespace>
  resourceVersion: "349917894"
  selfLink: /apis/storage.cnrm.cloud.google.com/v1beta1/namespaces/<namespace>/storagebucketaccesscontrols/<resource-name>
  uid: 21ec285b-0528-45d3-b276-0d3855497f2e
spec:
  bucketRef:
    external: <bucket-name>
  entity: <sa>@<project-id>.iam.gserviceaccount.com
  role: READER
status:
  conditions:
  - lastTransitionTime: "2021-05-10T07:22:50Z"
    message: 'Update call failed: error fetching live state: error reading underlying
      resource: summary: Error when reading or editing StorageBucketAccessControl
      "<bucket-name>/<sa>@<project-id>.iam.gserviceaccount.com":
      googleapi: Error 400: Cannot get legacy ACL for a bucket that has uniform bucket-level
      access. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access,
      invalid, detail: '
    reason: UpdateFailed
    status: "False"
    type: Ready
  email: <sa>@<project-id>.iam.gserviceaccount.com
  observedGeneration: 1
```

GKE is running version 1.19.9-gke.1400 with Config Connector enabled and managed by Google.

**Comment by jcanseco** [comment]
Hi @Nosmoht, this is a strange issue, and I believe it may be related to a known issue we're currently working to resolve.

Unfortunately, a manual workaround might be quite involved and error-prone.

As an alternate solution, would it be an option for you to upgrade your GKE cluster to `1.20.6-gke.1000`? It is currently the default version for the `RAPID` channel, and upgrading your GKE cluster to that version should also upgrade your Config Connector to a version that should allow you to delete your `StorageBucketAccessControl`.

**Comment by Nosmoht** [comment]
Hi @jcanseco ,

thanks for your fast answer. I'm currently upgrading GKE to `1.20.6-gke.1000`. 

In my case it's the dev cluster and can be upgraded if needed. What about user that can't upgrade GKE?

**Comment by Nosmoht** [comment]
Hi @jcanseco,

i can confirm that after upgrading GKE to `1.20.6-gke.1000` i could delete the resource.

Thanks for your support.
