### ISSUE TITLE
Add label rbac.authorization.k8s.io/aggregate-to-view=true to cnrm-viewer clusterrole

### ISSUE THREAD

**Issue by pmialon** [GoogleCloudPlatform/k8s-config-connector#486]
**Describe the feature or resource**
Adding label rbac.authorization.k8s.io/aggregate-to-view=true to cnrm-viewer clusterrole will allow user with the view clusterrole on a namespace to see the config-connector created resources.

**Importance**
This can be done with a second rolebinding but I think that the label is more in the kubernetes spirit.

**Comment by spew** [comment]
Hi @pmialon thanks for suggesting this enhancment. It likely does make sense to add and we will get back to you when this is prioritized.

**Comment by jcanseco** [comment]
Hi @pmialon, we just added the `aggregate-to-view` label to `cnrm-viewer` and the `aggregate-to-admin` and `aggregate-to-edit` labels to `cnrm-admin` in [KCC 1.56.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.56.0).
