### ISSUE TITLE
Ability to duplicate an existing SQLInstance

### ISSUE THREAD

**Issue by justinr1234** [GoogleCloudPlatform/k8s-config-connector#489]
**Describe the feature or resource**
Ability to create a SQL Instance from a duplicate

**Importance**
Paint point. I need to make workarounds which are very convoluted. Urgency is I'm trying to figure out a janky workaround right now.

**Comment by caieo** [comment]
Thanks for giving us some more information, @justinr1234. We'll look into supporting this feature and post any updates in this thread.

**Comment by jasonvigil** [comment]
This is done in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2429, will be available in release 1.22
