### ISSUE TITLE
Cloud Operation resources (Logging & Monitoring)

### ISSUE THREAD

**Issue by mohitkumar-bestbuy** [GoogleCloudPlatform/k8s-config-connector#490]
**Describe the feature or resource**
KCC supports limited features of Google Cloud Operation suite. Do you have timelines when below resources will be supported by KCC?
- Monitoring dashboard
- Custom metrics
- uptime Checks

**Importance**
This is very much required and blocker for our Observability platform.

Elaborate if you have any other details:
* How would this feature/resource impact you?
We would like to use existing automation pipeline which internally use KCC for GCP resources deployment. This pipeline can't be used for Observability platform as critical resources are not supported by KCC.
* Urgency. If this is a blocker, when would you need it by? If it's not yet a
  blocker, do you foresee it becoming a blocker at some point, and when?
This is blocker currently. we may need to develop a new automation pipeline just for observability and that will be a maintenance overhead on our team.
--->

**Comment by caieo** [comment]
@mohitkumar-bestbuy, here are the timelines we have so far: 
* Monitoring dashboard: Will be supported with this week's release
* Custom metrics: Could you clarify which resource you're asking for? Is it [Monitoring Custom Service](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services)?  
* Uptime Checks (#226): We're aiming to have support for this resource by the end of August.

**Comment by mohitkumar-bestbuy** [comment]
Thanks @caieo for the prompt response.  That's great "monitoring dashboard" will be supported from this week.
Custom metrics -  I was referring to "log based metrics" (https://cloud.google.com/logging/docs/logs-based-metrics), sry for the confusion. Do we have timeline for log based metrics too? 
is there any way to expedite support for Uptime checks?

**Comment by caieo** [comment]
@mohitkumar-bestbuy, `MonitoringDashboard` is now supported in our latest release ([1.54.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.54.0)).

Regarding timelines, can you elaborate on the urgency of this request? If the lack of support for these resources is a blocker, when is the latest you would need these resources supported by?

**Comment by mohitkumar-bestbuy** [comment]
@caieo thanks for the MonitoringDashboard update.
 Yes, this is blocker for Observability platform as we would like to leverage automation pipeline which internally use KCC. MonitoringDashboard will give us some room to start , it would be great if you can provide support for the below resources by July end.
- log based metrics (https://cloud.google.com/logging/docs/logs-based-metrics)
- Uptime checks.

**Comment by maqiuyujoyce** [comment]
Hi @mohitkumar-bestbuy , thank you for your response! We've added LoggingMetric and MonitoringUptimeCheckConfig to the list of resources we're looking into and will let you know when we have more information.

We've been [regularly adding new resources to Config Connector](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases), but the cost to add new resources are different and our priority may shift, so it's hard for us to give specific timelines at this moment. If the request is time-sensitive or there is a critical business need, could you submit an issue with [GCP support](https://cloud.google.com/support-hub)?

**Comment by maqiuyujoyce** [comment]
Hi @mohitkumar-bestbuy , `MonitoringUptimeCheckConfig` has been released in [1.70.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.70.0).

**Comment by jcanseco** [comment]
Hi @mohitkumar-bestbuy, it seems all resources you've requested are now supported on the latest KCC version (1.71.0). See https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/144#issuecomment-1027180119 and https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/490#issuecomment-877424100.
