### ISSUE TITLE
UpdateFailed on cluster after recreating nodePools 

### ISSUE THREAD

**Issue by hsuabina** [GoogleCloudPlatform/k8s-config-connector#491]
Hi,

I was having issues with a workload giving ImagePullBackOff, and after some research I realised the node pools I had created in my cluster did not have sufficient permissions (oauth scopes) to access a private container registry bucket.

First thing I tried was to update the nodeConfig fields (oauth scopes and service account) of my existing node pools, but I was expecting this update to be an immutable error (which I confirmed after seeing the update failed).

So then, I tried recreating the node pools of the cluster and changed their nodeConfig (updated oauth scopes and service account). I deleted the old node pools using KCC without issues.

In this process, I did not attempt to update the cluster resource by any means, but when I now try to add the new pools into this cluster, I'm unable to do so. The cluster is now in a not ready state, due to a failed update. Because of this, the new node pools can't be created as the cluster dependency is not ready. 

I'm not defining any `nodeConfig` in my cluster definition (only on the node pool definitions) and I'm using the annotation to remove the default pool that is created alongside the cluster.

The last event message when describing the cluster is this:

```
Update call failed: cannot make changes to immutable field(s): [nodeConfig.0.OauthScopes.# nodeConfig.0.ShieldedInstanceConfig.# nodeConfig.0.GuestAccelerator.# nodeConfig.# nodeConfig.0.OauthScopes.1277378754 nodeConfig.0.WorkloadMetadataConfig.# nodeConfig.0.Metadata.% nodeConfig.0.Preemptible nodeConfig.0.OauthScopes.172152165]
```

Reading this [comment](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/441#issuecomment-816477944) on #441, made me think that possibly, the updates to the nodeConfig *on the pools* I tried has now left the cluster in this situation. 

Are my thoughts correct? If so, is there any way to avoid having to recreate the cluster?

Thanks in advance.

**Comment by jcanseco** [comment]
Hi @hsuabina. Apologies for the very late reply, and thank you for the detailed description. I think your thoughts are correct. This seems to be the unfortunate result of a combination of odd GKE and KCC behaviors, but I need to try to reproduce on my side first to confirm.

I'll start with a potential workaround, then add more details later as I understand the issue better.

**Workaround:** I would try [abandoning](https://cloud.google.com/config-connector/docs/how-to/managing-deleting-resources#keeping_resources_after_deletion) your `ContainerCluster` first, and then [acquiring](https://cloud.google.com/config-connector/docs/how-to/managing-deleting-resources#acquiring_an_existing_resource) it afterwards but without specifying a `spec.nodeConfig`. Please let us know if that works for you. You may have to do this multiple times if you still have node pools that KCC is in the process of deleting.

**Comment by hsuabina** [comment]
Closing as stale, I ended up recreating the cluster.

Thanks for the help.
