### ISSUE TITLE
Discrepancy between IAMPartialPolicy CRD and the Go Client Type

### ISSUE THREAD

**Issue by lostick** [GoogleCloudPlatform/k8s-config-connector#495]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the [troubleshooting guide](https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

I'm unable to create an `IAMPartialPolicy` resource with the latest version (`1.54.0`) of Config Connector.
The Go client throws an error, as [IAMPartialPolicySpec](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/d0dbae602fe108ab4c875494d43bfbcfb6944ab2/pkg/apis/iam/v1beta1/iampartialpolicy_types.go#L75) does not match the [CRD](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/d0dbae602fe108ab4c875494d43bfbcfb6944ab2/crds/iam_v1beta1_iampartialpolicy.yaml#L105-L119) schema def. 

Solution:
Use [IAMResourceRef](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/d0dbae602fe108ab4c875494d43bfbcfb6944ab2/pkg/apis/k8s/v1alpha1/types.go#L68-L79) type in `IAMPartialPolicySpec`.

```
type IAMPartialPolicySpec struct {
	/* Optional. The list of IAM bindings managed by Config Connector. */
	// +optional
	Bindings []PartialpolicyBindings `json:"bindings,omitempty"`

	/* Immutable. Required. The GCP resource to set the IAM policy on (e.g. organization, project...) */
	ResourceRef v1alpha1.IAMResourceRef `json:"resourceRef"`
}
```

### Kubernetes Cluster Version

`v1.19.9-gke.1900`

### Config Connector Version

`1.54.0`

### Config Connector Mode

`cluster`

## Log Output

```
E0627 20:28:36.073935       1 iam.go:33] Unable to create IAM Policy abc-iam-role-admin: IAMPartialPolicy.iam.cnrm.cloud.google.com "abc-iam-role-admin" is invalid: spec.resourceRef.kind: Required value
```

### Steps to reproduce the issue

Create a new `iamv1beta1.IAMPartialPolicy` resource with the Go client.

**Comment by xiaobaitusi** [comment]
Hi @lostick, thanks for reporting the issue. We will look into fixing this!

**Comment by xiaobaitusi** [comment]
v1.55.0 should have fixed this issue. Let us know if that works!

**Comment by lostick** [comment]
Thanks @xiaobaitusi!
