### ISSUE TITLE
Folder Labels

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#497]
Currently it looks like Folders don't support labels in GCP. We were hoping to provide the KCC Folder Resource name via labels. Are folders going to support labels in the future? I know this is more of a GCP related question, but I'm hoping maybe I can get the answer quicker here vs opening a support ticket.

**Comment by xiaobaitusi** [comment]
@travisrandolph-bestbuy, unfortunately our team is not in a good position to give an authoritative answer to your question

 I would suggest to reach out to resource-manager API team for help - https://cloud.google.com/resource-manager/docs/getting-support
