### ISSUE TITLE
BigtableTable deletion on resource deletion

### ISSUE THREAD

**Issue by xvzf** [GoogleCloudPlatform/k8s-config-connector#499]
Is there a way to trigger the deletion of a BigtableTable when the Kubernetes resource is deleted?

There are no annotations related to this functionality available on https://cloud.google.com/config-connector/docs/reference/resource-docs/bigtable/bigtabletable

**Comment by maqiuyujoyce** [comment]
Hi @xvzf , thank you for your question! Are you trying to delete the underlying bigtable table when deleting the Config Connector BigtableTable resource? It's the same as other Config Connector resources, i.e. you can trigger the deletion via `kubectl delete bigtabletable [resource-name]` as long as you didn't [configure the Config Connector resource to abandon the underlying GCP resource](https://cloud.google.com/config-connector/docs/how-to/managing-deleting-resources#keeping_resources_after_deletion).

**Comment by xvzf** [comment]
Hi @maqiuyujoyce; it seems when there is no annotation present, the BigtableTable is not deleted, only the Kubernetes resource.

**Comment by maqiuyujoyce** [comment]
Hi @xvzf , thank you for your followup. Could you share more information about your issue? I couldn't reproduce it using the sample [here](https://cloud.google.com/config-connector/docs/reference/resource-docs/bigtable/bigtabletable) so would be great if you can provide the following information and we can reproduce and debug.

````
## Additional Diagnostic Information

### Kubernetes Cluster Version

<!--
Run the following command to get the Kubernetes cluster version:

kubectl version --short
-->

### Config Connector Version

<!--
Run the following command to get the installed Config Connector version:

kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'
-->

### Config Connector Mode

<!--
Run the following command to get the Config Connector Mode:

kubectl get ConfigConnector "configconnector.core.cnrm.cloud.google.com" -o=jsonpath="{@.spec.mode}"
-->

## Log Output

<!--
Include any relevant log output. See
  https://cloud.google.com/config-connector/docs/troubleshooting#logging

If the issue is for a specific resource, please include those logs.
-->

## Steps to Reproduce

### Steps to reproduce the issue
<!--- Steps needed to reproduce the issue. --->

### YAML snippets
<!--- YAML snippets needed to reproduce the issue. See the following as an example. --->

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    label-one: "value-one"
  name: pubsubtopic-sample
```
````

**Comment by xvzf** [comment]
Hi @maqiuyujoyce; after restarting config connector it works fine now. Sorry for the bug report!
