### ISSUE TITLE
`kubectl describe` throws error when resource is created before API is enabled

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#5]
1. Make sure redis api is not enabled (or disable is by calling `gcloud services disable redis.googleapis.com`)
1. Create redis instance 
``
kubectl create -f k8s-config-connector/samples/resources/redis_v1alpha2_redisinstance.yaml
``
1. Enable redis api
``
gcloud services enable redis.googleapis.com
``
1. Verify redis instance was created
``
kubectl get redisinstance
``
``
gcloud redis instances list --region=us-central1
``
1. Attempt to describe it
``
kubectl describe redisinstance redisinstance-sample
``
Expected: no error

Actual:
```
$ kubectl get redisinstance      
NAME                   AGE      
redisinstance-sample   18h      
$ kubectl describe redisinstance redistinstance-sample      
Error from server (NotFound): redisinstances.redis.cnrm.cloud.google.com "redistinstance-sample" not found
```

**Comment by kibbles-n-bytes** [comment]
Looks like the resource name is misspelled: you wrote `redistinstance-sample`, but the resource's name is `redisinstance-sample`. Could you try running:

```
kubectl describe redisinstance redisinstance-sample
```

and seeing what the output is?

**Comment by AlexBulankou** [comment]
You're right, I cannot spell :) thanks!
