### ISSUE TITLE
plans to support datastore?

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#50]
would be nice to have

**Comment by xiaobaitusi** [comment]
Hi, which resource are you referring to? We plan to cover all GCP resources eventually. Now we prioritize a selected list of resources based on beta customers feedback and requirements.

**Comment by nrobert13** [comment]
I meant to create the firestore database either in native or in datastore mode.

**Comment by AlexBulankou** [comment]
Dupe of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/18
