### ISSUE TITLE
Unify resource groups to a single one?

### ISSUE THREAD

**Issue by toumorokoshi** [GoogleCloudPlatform/k8s-config-connector#501]
Today, Config Connector registers resources under multiple api groups, all under the top-level api group of "cnrm.cloud.google.com".

I'll propose that it would be better to introduce all resources under a single resource group. The rationale is:

- easier to assign blanket permissions to KCC resources (e.g. look at the [cnrm-system admin cluster role and it's long list of groups](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/install-bundles/install-bundle-workload-identity/0-cnrm-system.yaml#L116).
- If KCC fully adopts [best practices for object references](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#multiple-resource-reference), that may include specifying the group. This could be made much simpler for the user by remembering a single one. 

This is to kick-start a discussion, so it'd be good to add arguments that lead to the original design decision. 

## Priority

This isn't a high priority, but it does enable simpler management long term.

**Comment by justinsb** [comment]
Because we want to promote some beta resources to GA, and because changing resource group would be a breaking change, this does not seem feasible.

/close
