### ISSUE TITLE
Support Internet NEGs (network endpoint groups)

### ISSUE THREAD

**Issue by lmakarov** [GoogleCloudPlatform/k8s-config-connector#502]
**Describe the feature or resource**

Add support for Internet NEGs (network endpoint groups):
https://cloud.google.com/load-balancing/docs/negs/internet-neg-concepts

Applicable endpoint types: `INTERNET_FQDN_PORT` or `INTERNET_IP_PORT`

**Importance**

This is a blocker to using Config Connector as the standard for IaC (infrastructure as code) in our organization.

We are currently using Terraform/Pulumi to manage GCP resources and looking at Config Connector as the next generation framework for IaC. The automatic reconciliation of drifts and the fact that our K8s native as well as GCP resources can be managed in the same way is a huge selling point. Unfortunately, the lack of supported resources in Config Connector means that this transformation is not possible right now.

**Additional context**

We are using GCP LB as the ingress and reverse-proxy for a variety of services and applications.

Here's an example of what routing would look like in our setup:

- https://example.com => marketing website hosted outside of GCP
  - REST Resource: [globalNetworkEndpointGroups](https://cloud.google.com/compute/docs/reference/rest/v1/globalNetworkEndpointGroups)
  - endpoint type: `INTERNET_FQDN_PORT`
- https://example.com/app/ => application frontend hosted with Firebase Hosting
  - REST Resource: [globalNetworkEndpointGroups](https://cloud.google.com/compute/docs/reference/rest/v1/globalNetworkEndpointGroups)
  - endpoint type: `INTERNET_FQDN_PORT`
- https://example.com/api/ => application backend hosted with Cloud Run
  - REST Resource: [regionNetworkEndpointGroups](https://cloud.google.com/compute/docs/reference/rest/v1/regionNetworkEndpointGroups)
  - endpoint type: `SERVERLESS` (Requested in #322)

**Comment by jcanseco** [comment]
Hello @lmakarov, thank you for reaching out. We're glad to hear that you're considering Config Connector for your IaC automation.

Yes, we hear you on the lack of supported resources. This is a recurring problem for our customers, and we have been and will continue to actively invest in automation to accelerate our resource coverage.

I've added your resource requests to our backlog. Thank you for specifying the REST docs -- these really do help us ensure we're implementing the correct resources for our customers.

**Comment by dorfire** [comment]
I also need this; currently forced to use Terraform instead.

**Comment by tedelwartowski-bestbuy** [comment]
@jcanseco - can you advise if https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computeregionnetworkendpointgroup is the enhancement for this reported issue and #322?

**Comment by jcanseco** [comment]
Yes thanks for checking @tedelwartowski-bestbuy. I think both #502 and #322 are resolved now via 

* https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computenetworkendpointgroup
* https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computeregionnetworkendpointgroup
