### ISSUE TITLE
cnrm-controller-manager operator not installed when cluster created

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#506]
## Bug Description

Created a cluster with kcc addon but the cnrm-controller-manager was not installed

These were installed though:
cnrm-deletiondefender
cnrm-resource-stats-recorder
cnrm-webhook-manager

### Kubernetes Cluster Version
 1.18.20-gke.501

### Config Connector Version

`1.52.0`

### Config Connector Mode

namespaced

**Comment by red8888** [comment]
forgot to leave a comment- issue was that I didnt set the config correctly

**Comment by kYann** [comment]
Hello ! I have the same issue. What was the config issue ?
