### ISSUE TITLE
Cloud Functions Resource

### ISSUE THREAD

**Issue by tokatsu-gc** [GoogleCloudPlatform/k8s-config-connector#512]
This is a request to support Cloud Functions.

In order to support Cloud Functions, Config Connector should support the following things

Register functions. 
- Resource: projects.locations.functions, https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions
- Terraform resource: google_cloudfunctions_function https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function

Manage IAM
- Terraform resource: google_cloudfunctions_function_iam_member https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function_iam

Cloud Functions is a handy way to handle light weight tasks.
The number of functions for Cloud Functions is increasing.
With Config Connector, customers can manage functions by a declarative way.

**Comment by caieo** [comment]
Hi @tokatsu-gc, thank you for your resource request. I've added it to the list of resources we're looking into and will let you know when we have more information.

**Comment by tgjonestx** [comment]
+1 

We have a specific use case for provisioning the [cloud-build slack-notifier](https://cloud.google.com/build/docs/configuring-notifications/configure-slack) which uses Cloud Run. At the moment, we have a rather clunky approach that depends on both KCC and TF. Having everything provisioned through KCC would be ideal.

**Comment by maqiuyujoyce** [comment]
Hi @tgjonestx , thx for your use case! According to links mentioned in the description, I believe @tokatsu-gc was requesting for Cloud Function resources (but not Cloud Run).

**Comment by tokatsu-gc** [comment]
> As an ETA, we are slated to deliver this resource by the end of this year.

Is this feature available in this year or is there a new ETA?

**Comment by toumorokoshi** [comment]
Hello!

Although we are on target for code completion, we will most like release mid-January due to a release freeze for the Holidays. 

Apologies about the extended delay.

**Comment by mbzomowski** [comment]
Hi, `CloudFunctionsFunction` has been added as of [v1.72.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.72.0).
