### ISSUE TITLE
Cloud Scheduler Resrouce

### ISSUE THREAD

**Issue by tokatsu-gc** [GoogleCloudPlatform/k8s-config-connector#513]
This is a request to support Cloud Scheduler.

The Google Cloud resource is  v1beta1.projects.locations.jobs, https://cloud.google.com/scheduler/docs/reference/rest/
The Terraform resource is google_cloud_scheduler_job, https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job

Scheduler Jobs is a good tool to run periodic tasks and the number of jobs customers are managing is increasing. With Config Connector, customers can manage jobs by a declarative way.

**Comment by caieo** [comment]
Hi @tokatsu-gc, KCC supports Cloud Scheduler Job as of release 1.39.0 ([notes here](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.39.0)). You can also check the reference page for CloudSchedulerJob here: https://cloud.google.com/config-connector/docs/reference/resource-docs/cloudscheduler/cloudschedulerjob 

If there are other resources you need to request, you can view all of our supported resources here to confirm that we don't currently support it: https://cloud.google.com/config-connector/docs/reference/overview

**Comment by tokatsu-gc** [comment]
Ok. I understand Cloud Scheduler Job has been already supported.
