### ISSUE TITLE
Resource label validation

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#515]
Hello team. Recently we upgraded to KCC version 1.54.0. After the upgrade we started receiving Helm errors regarding resource labels being type nil. I understand that this is our problem and we addressed that. I'm just wondering if label validation, or other resource validations have been added in the recent releases. Example below.

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in DNSManagedZone.metadata.labels.{{REDACTED}}`

**Comment by caieo** [comment]
Hi @travisrandolph-bestbuy, AFAIK, we don't do label validation on the k8s objects. Our validating webhooks check for immutable fields to unknown fields, but we don't do type validation and I don't think we do any webhook validation on labels. If this is something you'd really like us to support, I can add it to our backlog. Before I do, can you give us more information on if the lack of this feature is a blocker, friction point, or nice-to-have?

**Comment by travisrandolph-bestbuy** [comment]
No need to add it to your backlog @caieo. Thanks for your assistance.
