### ISSUE TITLE
sqluser grant fine grain 

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#52]
would be nice to be able create users with custom grants.

**Comment by xiaobaitusi** [comment]
Hi Robert, 
Thanks for your feedback. Can you provide more details about your use case? I'm not aware that custom grants are supported in [the underlying API](https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/users)?

**Comment by nrobert13** [comment]
Hi,

I was thinking about granular mysql grants, like:

```GRANT INSERT,SELECT,UPDATE,DELETE ON DB.Table TO 'user' ```

but I see now that the underlying API doesn't support that either ....

**Comment by xiaobaitusi** [comment]
Mark the issue closed since the underlying API doesn't support the use case.
