### ISSUE TITLE
cloud DNS support

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#53]
would be nice to be able to create DNS records with kcc.

**Comment by kibbles-n-bytes** [comment]
Thanks for the suggestion! DNS managed zone and record set functionality is planned for a release in the next few weeks.

**Comment by kibbles-n-bytes** [comment]
We now have support for `DNSManagedZone` and `DNSRecordSet`. Please let us know if there is any other DNS-related resources you would like to see support for.
