### ISSUE TITLE
Support for Cloud Run Serverless VPC Access connector

### ISSUE THREAD

**Issue by neuromantik33** [GoogleCloudPlatform/k8s-config-connector#531]
I was wondering if there were any plans to support Serverless VPC access as described here
https://cloud.google.com/run/docs/configuring/connecting-vpc

Seeing as its already implenting using Terraform, I imagine it should be feasable. Thanks in advance

**Comment by xiaobaitusi** [comment]
Hi, thanks for the feature request! We've added it to the list of resources we're looking to support and will let you know when we have more information.

**Comment by travisrandolph-bestbuy** [comment]
We are also looking for this feature request.

**Comment by jcanseco** [comment]
Sounds good @travisrandolph-bestbuy; we'll note that down in the internal tracking issue.

**Comment by tokatsu-gc** [comment]
> Hi! There request does not cover Cloud Function, but I see [you filed one already](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/512).
> 
> As an ETA, we are targetting adding this resource by the end of this year.

Is this feature available in this year? or is there a new ETA?

**Comment by toumorokoshi** [comment]
> Is this feature available in this year? or is there a new ETA?

Hello! Although we are on target for code completion, we will most like release mid-January due to a release freeze for the Holidays. Apologies about the extended delay.

**Comment by toumorokoshi** [comment]
Hello! With the release of [1.69.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.69.0), the VPCAccessConnector resource has been added. 

Cloud Run and Cloud Functions are coming in upcoming releases (hopefully both before end of January). Please track those resources in the respective issues.
