### ISSUE TITLE
allow for enabling project level apis

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/k8s-config-connector#535]
**Describe the feature or resource**
We generate a GCP project per internal service, routing all logs, metrics, and traces to that project. The issue is that the trace api isn't enabled on those projects, leaving them without and spans getting ingested. More broadly, I can see wanting to specifically enable/disable specific apis on my project yaml.

**Importance**
Nice to have

**Comment by caieo** [comment]
Hi @derekperkins, thanks for letting us know your use case and asking for this. We have this [`Service` resource](https://cloud.google.com/config-connector/docs/reference/resource-docs/serviceusage/service), where you should be able to enable a `cloudtrace.googleapis.com` service for a specific project. Please give it a try and reply if it doesn't satisfy your use case.

**Comment by derekperkins** [comment]
Can confirm that this works, thanks!
