### ISSUE TITLE
IAMPartialPolicy does not support org resourceRef but docs state organization as example 

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/k8s-config-connector#538]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

IAMPartialPolicy does not seem to have support for Organization as a resourceRef but docs give this as an [example](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampartialpolicy#:~:text=the%20gcp%20resource%20to%20set%20the%20iam%20policy%20on%20(e.g.%20organization%2C%20project...) )

**Comment by diviner524** [comment]
https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.73.0

The feature is now supported. Document is also up to date.
