### ISSUE TITLE
KCC Integration with Google Uptime Checks

### ISSUE THREAD

**Issue by ihaquekzHEqs24** [GoogleCloudPlatform/k8s-config-connector#539]
**Describe the feature or resource**

BenchSci would like to use the Infrastructure-As-Code IAC featureset in KCC to declare and configure Google Uptime Checks: https://cloud.google.com/monitoring/uptime-checks

**Importance**

We are keen to establish the uptime of our services, so we can provide SLAs to our customers.

We try to make sure all of our assets are configured via IAC, so we can manage the lifecycle of these assets properly and all the advantages of IAC.

Not having it in IAC would cause us either:

- double work, by implementing them with mouse through the web UI, and then migrating it over to IAC when/if this feature is implemented
- we won't have uptime metrics and SLAs for our customers if we don't have this feature, and we decide we want to wait for this feature

Elaborate if you have any other details:
- This is a blocker for us to provide our customers with SLAs.

**Comment by maqiuyujoyce** [comment]
Hi @ihaquekzHEqs24 , `MonitoringUptimeCheckConfig` has been released in [1.70.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.70.0).
