### ISSUE TITLE
Spanner Database Resource should support  versionRetentionPeriod and earliestVersionTime

### ISSUE THREAD

**Issue by knechtionscoding** [GoogleCloudPlatform/k8s-config-connector#544]
**Describe the feature or resource**
Spanner Database Resource should support setting the versionRetentionPeriod and earliestVersionTime to allow for PITR:

https://cloud.google.com/blog/products/databases/continuous-data-protection-here-for-spanner-with-pitr

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/531fa4f6b0211f5fb92131c33f3c7d0d5eed8fc5/pkg/apis/spanner/v1beta1/spannerdatabase_types.go#L44-L62

**Importance**

Currently this has to be set manually via the console or the cli rather than being stored in the cnrm config for the resource. Would greatly improve the ability to provision spanner via cnrm

**Comment by KnechtionsCoding** [comment]
Based on the other Issues/PRs I see we need to wait for terraform to support it: https://github.com/hashicorp/terraform-provider-google/issues/8994 will solve this.

**Comment by toumorokoshi** [comment]
Hi! 

> Based on the other Issues/PRs I see we need to wait for terraform to support it: hashicorp/terraform-provider-google#8994 will solve this.

Yes, exactly. Once it's in Terraform expect a 2-3 week maximum delay for it to appear in the next version of Config Connector.

**Comment by KnechtionsCoding** [comment]
@toumorokoshi based on: https://github.com/GoogleCloudPlatform/magic-modules/pull/6141 and the other issue being closed for 30 days, should we expect this to land in config connector in the next release? Or is it already available?

**Comment by toumorokoshi** [comment]
Hi! Just as an FYI I've moved teams, so may not able to help as much.

[I took a quick look at the docs and I don't see the field appearing yet](https://cloud.google.com/config-connector/docs/reference/resource-docs/spanner/spannerdatabase). Likely it will be picked up a Terraform update in the next week or so. 

An engineer working on the product should be able to reply soon with more details.

**Comment by mbzomowski** [comment]
@KnechtionsCoding Likely we will update Config Connector's Terraform provider next week, so this change should be included in our release the week after that, which will be Config Connector v1.92.0.

**Comment by mbzomowski** [comment]
@KnechtionsCoding correction - we won't be updating our Terraform provider this week. We should be updating it two weeks from now, so this change will be included in our release 3 weeks from now.

**Comment by cheftako** [comment]
/fixed
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/v1.113.0/config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_spannerdatabases.spanner.cnrm.cloud.google.com.yaml#L146 shows the version retention period. I do not believe earliestVersionTime was added to TF>
