### ISSUE TITLE
Support for Workload Identity Pools and Providers

### ISSUE THREAD

**Issue by jagheterfredrik** [GoogleCloudPlatform/k8s-config-connector#547]
KCC support for https://cloud.google.com/iam/docs/manage-workload-identity-pools-providers

**Comment by toumorokoshi** [comment]
Thanks for the request! We've added it to our queue. The current ETA on this resource is by EOQ4.

If there's a strong priority or blocker, please add that rationale here or privately via GCP support or representative.

**Comment by toumorokoshi** [comment]
Hello! With [1.69.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.69.0), we now support `IAMWorkloadIdentityPool` and `IAMWorkloadIdentityPoolProvider`. Please give it a try and feel free to comment if the use case isn't satisfied.
