### ISSUE TITLE
Request for KCC Support for Jupyter Notebooks

### ISSUE THREAD

**Issue by pgunter25** [GoogleCloudPlatform/k8s-config-connector#551]
**Describe the feature or resource**
KCC support for Jupyter notebooks. 

**Importance**
Low 

Elaborate if you have any other details:
* How would this feature/resource impact you? Allow FSI customer to move their Jupyter Notebooks to IaC. 
* 
* Urgency. If this is a blocker, when would you need it by? If it's not yet a
  blocker, do you foresee it becoming a blocker at some point, and when? Q2 2022 
--->

**Comment by maqiuyujoyce** [comment]
Hi @pgunter25 , thanks for the request! Could you share more information about what resources in Notebooks service do you need in your use case?

**Comment by toumorokoshi** [comment]
Hi! closing as duplicate of #493
