### ISSUE TITLE
BigtableAppProfile Fails after Create on Update

### ISSUE THREAD

**Issue by jkapdev** [GoogleCloudPlatform/k8s-config-connector#553]
`BigtableAppProfile` fails on Update after a successful Create. The error message does not include any information as to why it had failed, other than the resource already exists - which would be expected. My understanding is that even if the resource exists, `BigtableAppProfile` should be able to export the resource. Is this expected behavior?

Error Message:
```
Update call failed: error applying desired state: summary: Error creating AppProfile: googleapi: Error 409: Requested entity already exists, detail:
```

**Comment by jcanseco** [comment]
Hi @jkapdev, your understanding is correct. 

Can you share the YAMLs you used (both the original and updated `BigtableAppProfile`)?

I just tried creating and updating a `BigtableAppProfile` and did not get the same error. I also tried acquiring an existing `BigtableAppProfile` and that worked just fine too.

**Comment by jkapdev** [comment]
Hi @jcanseco, thank you for the quick response!

This condition happens immediately after a `Create` occurs, seems like it's failing on `Update` from a reconciliation.

The originally applied YAML looks like (with some redactions for privacy):
```golang
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableAppProfile
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: <project_id>
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 2
  name: <name>
  namespace: <namespace>
spec:
  description: App Profile for <>
  instanceRef:
    external: projects/<project_id>/instances/<instance>
  resourceID: <name>
  singleClusterRouting:
    allowTransactionalWrites: true
    clusterId: primary
status:
  conditions:
  - lastTransitionTime: "2021-09-22T19:43:58Z"
    message: 'Update call failed: error applying desired state: summary: Error creating
      AppProfile: googleapi: Error 409: Requested entity already exists, detail: '
    reason: UpdateFailed
    status: "False"
    type: Ready
  name: projects/<project_id>/instances/<instance>/appProfiles/<app_profile>
  observedGeneration: 2
```

**Comment by jcanseco** [comment]
Ah, thank you @jkapdev. I am able to reproduce the same error now.

Interestingly, you can avoid the error by setting `spec.instanceRef.external` to just the _name_ of the instance. This seems to be the correct usage anyway judging by the [description of instanceRef.external](https://cloud.google.com/config-connector/docs/reference/resource-docs/bigtable/bigtableappprofile#spec) which says that it expects a "name" rather than a "selfLink".

The error, however, is quite poor. I suspect I know the reason why, and I have filed an internal bug accordingly. However, I suspect we won't be able to get to fixing it for some time, so I recommend just using the name of the instance for now to set `external`.

**Comment by jkapdev** [comment]
> Interestingly, you can avoid the error by setting `spec.instanceRef.external` to just the _name_ of the instance. This seems to be the correct usage anyway judging by the [description of instanceRef.external](https://cloud.google.com/config-connector/docs/reference/resource-docs/bigtable/bigtableappprofile#spec) which says that it expects a "name" rather than a "selfLink".

Ahha! Good call out, that seems to fix the issue! Thank you for looking into this, agreed a more verbose error would help to identify this failure, alternatively rejecting a "selfLink" to the instance!
