### ISSUE TITLE
Unable to remove LifecycleRule from GCS Resources

### ISSUE THREAD

**Issue by joepeterson-bestbuy** [GoogleCloudPlatform/k8s-config-connector#554]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description
We're unable to remove Lifecycle Rules from GCS resources. When attempting to update a GCS resource in order to remove a Lifecycle Rule, the following behaviors are observed:

1. After deleting the Lifecycle Rule from the configuration, it no longer appears in the release manifest.  However, it still appears when describing the GCS bucket resource or when viewing it through the GCP console.
2. It is possible to update the Lifecycle Rule.  For instance, we can change the type from "SetStorageClass" to "Delete", but cannot remove the Lifecycle Rule from a GCS resource in its entirety after it's been added.  

### Kubernetes Cluster Version

Client Version: v1.19.4
Server Version: v1.18.20-gke.901

### Config Connector Version

1.60.0

### Steps to reproduce the issue

1. Deploy a GCS bucket with a Lifecycle Rule configured.
2. Remove all Lifecycle Rules from the configuration file.
3. The GCS bucket will fail to remove the Lifecycle Rule.

### YAML snippets

```yaml
  {{- if .lifecycle_rules }}
  lifecycleRule:
    {{- range .lifecycle_rules }}
    - action:
      {{- if .storage_class }}
        storageClass: {{ .storage_class }}
      {{- end }}
        type: {{ .type }}
      condition:
        {{ .condition_type }}: {{ .condition_value }}
    {{- end }}
  {{- end }}
```

**Comment by jcanseco** [comment]
Hi @joepeterson-bestbuy, if you are deleting the `lifecycleRule` field from your YAML entirely, then what that is actually doing is telling KCC to let the field be "externally-managed" (i.e. that you don't hold an opinion on the field anymore and are allowing it to just reflect whatever value is on GCP).

If you want to clear the list, you can do so by setting it to an empty list like so: `lifecycleRule: []`

**Comment by joepeterson-bestbuy** [comment]
Thank you @jcanseco

**Comment by kishorv06** [comment]
@jcanseco I have the same issue. Also when setting `lifecycleRule: []`, I am getting the following error:
```
Warning  UpdateFailed  9s (x3 over 11s)   storagebucket-controller  Update call failed: error expanding resource configuration: cannot interpret non-list as list
```

Version information:
```
Client Version: v1.19.2
Server Version: v1.21.5-gke.1302

Config Connector: 1.63.0
Mode: namespaced
```

**Comment by jcanseco** [comment]
Hey @kishorv06, I apologize for having missed your comment. Please don't hesitate to post follow-up comments to ping us in case you have not gotten a response in suitable time.

It seems a new issue has been raised on that same topic in https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/595. Let us continue the discussion there.

**Comment by kishorv06** [comment]
Hey @jcanseco,

Thank you for the update.

> Please don't hesitate to post follow-up comments to ping us in case you have not gotten a response in suitable time.

Yeah sure, I will do that in future. However in this particular case, since my organization was evaluating config-connector for use in production, we have already raised this issue, along with a few others, internally through our point of contact at GCP.

**Comment by jcanseco** [comment]
Ah I see, thanks @kishorv06. Unfortunately, it didn't reach us through GCP support for some reason. Either it got dropped somewhere or I just can't find it, so I apologize about that.

In any case, we're taking a look at the issue and seeing what we find.
