### ISSUE TITLE
Can not export IAMCustomRole with config-connector bulk-export

### ISSUE THREAD

**Issue by PatrickChenSe** [GoogleCloudPlatform/k8s-config-connector#556]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

We're trying to export IAMCustomRole with the config-connector CLI 1.60, and failed. 
Here is my steps:
```
# export resources using gcloud
gcloud asset export -content-type resource --project test --output-path gs://test-bucket/test.txt

# export resource using config-connector
config-connector bulk-export --filter-deleted-iam-members --iam-format=policymember  --input=tmp.txt

```
And got error
```
error in 'config-connector' version '1.60.0': error getting next YAML: error getting unstructured: error getting next unstruct: error converting asset '//iam.googleapis.com/projects/test/roles/roletest1' with kind 'iam.googleapis.com/Role' to skeleton: error importing resource name to TF state: error importing resource: expected 3 partitions in import ID, got 1
```
## Additional Diagnostic Information

Content in the tmp.txt
```json
{"name":"//iam.googleapis.com/projects/test/roles/roletest1","asset_type":"iam.googleapis.com/Role","resource":{"version":"v1","discovery_document_uri":"https://iam.googleapis.com/$discovery/rest","discovery_name":"Role","parent":"//cloudresourcemanager.googleapis.com/projects/82702xxx234","data":{"description":"Created on: 2021-09-24","etag":"BwXMvUMczuo=","groupName":"custom","groupTitle":"Custom","includedPermissions":["storagetransfer.jobs.get","storagetransfer.jobs.list"],"name":"projects/test/roles/roletest1","title":"roletest1"}},"ancestors":["projects/82xxxx34","organizations/64xxxxx7xxxx50"],"update_time":"2021-09-24T12:55:30.399978Z"}
```
### Kubernetes Cluster Version

Client Version: v1.19.2
Server Version: v1.20.9-gke.1001
### Config Connector Version

1.60

**Comment by jcanseco** [comment]
Hi @PatrickChenSe, thanks for filing this issue. I can confirm that I am able to reproduce the same error. Can you comment on whether this issue represents a blocker, friction point, or nice-to-have for you?

**Comment by PatrickChenSe** [comment]
Hi @jcanseco, thanks for the reply. It is kinda a blocker for us right now, since we're hoping to declaratively manage 1000+ CustomRole across the company. Do you have a timetable for when this will be fixed?

**Comment by toumorokoshi** [comment]
Hello! This is now fixed in [1.67.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.67.0). Please give it a try!

Let me know if it doesn't resolve your issue, and I'll re-open the ticket. Closing proactively for issue hygiene.

**Comment by PatrickChenSe** [comment]
I verified, it works with 1.67. Thanks!

**Comment by toumorokoshi** [comment]
Great! glad to hear it.
