### ISSUE TITLE
Default resources for cnrm-controller-manager in pod are too low

### ISSUE THREAD

**Issue by calind** [GoogleCloudPlatform/k8s-config-connector#56]
By default, the `cnrm-controller-manager` pod requests `40Mi` of memory and limits it to `60Mi`. This results in the pods almost always being OOMKilled. At `256Mi` the pod looks stable.

**Comment by xiaobaitusi** [comment]
Hi Calin, thanks for bring it up. Do you mind sharing how many CRs/resources that are managed by Config Connector in your case? Mark it as enhancement for our tracking.

**Comment by calind** [comment]
Here are the managed resources:
* 1 ServiceAccount
* 1 IAM Policy
* 1 StorageBucket
* 1 StorageBucketAccessControl

With `256Mi` there were no restarts in the last 20 hours.

```console
$ kubectl -n cnrm-system get pod
NAME                        READY   STATUS    RESTARTS   AGE
cnrm-controller-manager-0   1/1     Running   0          19h
```

<img width="1639" alt="Screenshot 2019-10-22 at 15 08 56" src="https://user-images.githubusercontent.com/266375/67284280-fcef4600-f4dd-11e9-8033-bb8b40668947.png">

The cnrm image is `gcr.io/cnrm-eap/controller:85a6ab0` so I guess is version 0.2.0.

**Comment by kibbles-n-bytes** [comment]
Thanks calind! For the release next week, we've bumped it to request: 128Mi, limit: 256Mi.
