### ISSUE TITLE
config-connector util dosent get the correct CRD (GKE nodepools)

### ISSUE THREAD

**Issue by MalulDekel** [GoogleCloudPlatform/k8s-config-connector#567]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

config-connector export gets the uncorrent CRD kind 

running the following command:
```
config-connector export -v //container.googleapis.com/projects/myproject/locations/europe-west1/clusters/mycluster/nodePools/mynodepoll
```
Gets the Containercluster kind and not the cotainernodepoll wanted CRD.

containernodepull api reference from the config connector docs https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containernodepool
### Kubernetes Cluster Version

1.19

### Config Connector Version

1.58.0

### Config Connector Mode

cluster

## Steps to Reproduce

* Create GKE cluster
* Run config-connector export on one of his nodepools

**Comment by jcanseco** [comment]
Hey @MalulDekel, it seems `config-connector export` doesn't actually support `ContainerNodePool` resources.

Please see [this comment](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/507#issuecomment-879427504) which shows you how to tell what resources are supported by `export` an `bulk-export`, and a possible workaround for importing `ContainerNodePool` resources by using `bulk-export` and a filtered Cloud Asset Inventory export file.

**Comment by MalulDekel** [comment]
@jcanseco Thanks for the quick reply. I have thought on another workaround for it but I will try it also if the workaround will fail.

**Comment by MalulDekel** [comment]
@jcanseco I got the nodepool associated to the config connector but I got the following issue:
```
Update call failed: cannot make changes to immutable field(s): [nodeConfig.0.OauthScopes.# nodeConfig.0.OauthScopes.172152165 nodeConfig.0.OauthScopes.1277378754
```
I tried to remove and added them back without any success
