### ISSUE TITLE
run as nonRoot

### ISSUE THREAD

**Issue by egym-cr** [GoogleCloudPlatform/k8s-config-connector#57]
Hey guys,

I tried to run the controller as nonRoot user, but it's failing due to:
```
WORKDIR /root/
```
Is there a requirement to use `/root` or could you change the image to use a different path so we can run it as nonRoot..

Thanks

**Comment by AlexBulankou** [comment]
@egym-cr, thanks for flagging it. Best practices recommend to [avoid running as root](https://cloud.google.com/solutions/best-practices-for-operating-containers#avoid_running_as_root) and we will follow up on whether there's a requirement for us to do it.

**Comment by kibbles-n-bytes** [comment]
This is now fixed in the latest release. Please reopen this issue if you're still having issues with running as non-root.
