### ISSUE TITLE
BigQuery Authorized Dataset support

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#572]
**Describe the feature or resource**
We have users who would like to use KCC to create Authorized Datasets for BigQuery. This would simplify BigQuery table/view IaC. [https://cloud.google.com/bigquery/docs/authorized-datasets](url)

**Importance**
Pain point

**Comment by xiaobaitusi** [comment]
Hi @travisrandolph-bestbuy, thanks for making the request.

Given that KCC use terraform provider to actuate this resource, we need terraform to support this feature first. Luckily there is already a feature request tracked on their side. https://github.com/hashicorp/terraform-provider-google/issues/10555

KCC CRD pipeline will inherit the support once Terraform adds the authorized dataset support.

Thanks

**Comment by erik-carlson** [comment]
Looks like terraform supports this now and support was added in KCC release 1.76.0.  Is there anything outstanding for this issue, or should it be closed?

**Comment by diviner524** [comment]
@erik-carlson Thanks for the update! Yes this support was added in KCC release 1.76.0 and you should be able to use KCC to create Authorized Datasets for BigQuery now.

We will close this issue. Let us know if you see any future issues when using this new feature.
