### ISSUE TITLE
Config Connector reconciler error after installation on other Kubernetes distributions

### ISSUE THREAD

**Issue by suckowbiz** [GoogleCloudPlatform/k8s-config-connector#574]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

Hello together,

I am working for a big company that evaluates Google Config Connector for production use. We have an inhouse kubernetes cluster that is used for our customers.

Since we do not use GKE I had to install the Config Connector as for "other Kubernetes distributions". I followed the [offical guide](https://cloud.google.com/config-connector/docs/troubleshooting).

After installation succeeded I verified everything works as expected:

```shell
# $ kubectl wait -n cnrm-system --for=condition=Ready pod --all
pod/cnrm-controller-manager-0 condition met
pod/cnrm-deletiondefender-0 condition met
pod/cnrm-webhook-manager-7fc6f759c-cn94w condition met
pod/cnrm-webhook-manager-7fc6f759c-rhkl9 condition met
```

Then I tried to simply enable a service API at GCP like so:

```yaml
# enable-pubsub.yaml
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: pubsub.googleapis.com
```

Then kubectl to fire the yaml.

```shell
kubectl apply -f enable-pubsub.yaml
```
Checking the logs:

```shell
# $ kubectl logs cnrm-controller-manager-0
{"severity":"info","timestamp":"2021-11-18T15:00:50.992Z","logger":"service-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"pubsub.googleapis.com"}}
{"severity":"error","timestamp":"2021-11-18T15:00:54.695Z","logger":"controller.service-controller","msg":"Reconciler error","reconciler group":"serviceusage.cnrm.cloud.google.com","reconciler kind":"Ser
vice","name":"pubsub.googleapis.com","namespace":"cnrm-system","error":"Update call failed: error fetching live state: error reading underlying resource: summary: Error when reading or editing Project Se
rvice projects/cnrm-system/services/: Request `List Project Services cnrm-system` returned error: Failed to list enabled services for project cnrm-system: googleapi: Error 403: Permission denied to list 
services for consumer container [projects/751327568111]\nHelp Token: Ae-hA1MsQc8j6WAuY56ifDCsz0MiqPX-adOjryBN_Z0zNXMWVO2Fj5HE_bj-hECrD6x-PxLdNw-q-xQgp_ImSr6elpkCqxdLQbHPhRvgb5Ik6ORD\nDetails:\n[\n  {\n  
  \"@type\": \"type.googleapis.com/google.rpc.PreconditionFailure\",\n    \"violations\": [\n      {\n        \"subject\": \"110002\",\n        \"type\": \"googleapis.com\"\n      }\n    ]\n  },\n  {\n  
  \"@type\": \"type.googleapis.com/google.rpc.ErrorInfo\",\n    \"domain\": \"serviceusage.googleapis.com\",\n    \"reason\": \"AUTH_PERMISSION_DENIED\"\n  }\n]\n, forbidden"}
```
I double checked that the service account I set for Config Connector has `roles/owner` and is really active:

```shell
gcloud auth list
                            Credentialed Accounts
ACTIVE  ACCOUNT
*       config-connector@{obfuscated}.iam.gserviceaccount.com
```

### Kubernetes Cluster Version

```shell
# $ kubectl version --short
Client Version: v1.22.3
Server Version: v1.21.5
```

### Config Connector Version

```shell
# $ kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'
1.67.0
```

### Config Connector Mode

```shell
# $ kubectl get ConfigConnector "configconnector.core.cnrm.cloud.google.com" -o=jsonpath="{@.spec.mode}"
cluster
```

## Log Output

```shell
# kubectl get logs cnrm-controller-manager-0
{"severity":"info","timestamp":"2021-11-18T15:21:45.787Z","logger":"service-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"pubsub.googleapis.com"}}
{"severity":"error","timestamp":"2021-11-18T15:21:49.606Z","logger":"controller.service-controller","msg":"Reconciler error","reconciler group":"serviceusage.cnrm.cloud.google.com","reconciler kind":"Service","name":"pubsub.googleapis.com","namespace":"cnrm-system","error":"Update call failed: error fetching live state: error reading underlying resource: summary: Error when reading or editing Project Service projects/cnrm-system/services/: Request `List Project Services cnrm-system` returned error: Failed to list enabled services for project cnrm-system: googleapi: Error 403: Permission denied to list services for consumer container [projects/751327568111]\nHelp Token: Ae-hA1N3A2Y8nEOo8SribuMj-G2kEk5yRxNhj37R3yJJGpQWfZxKZEgxHsJeNefE-vlejc2tvpJ1hxcGr6FRoGu94aNRPbyxdK7Z6NT9kzFSUQ3Q\nDetails:\n[\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.PreconditionFailure\",\n    \"violations\": [\n      {\n        \"subject\": \"110002\",\n        \"type\": \"googleapis.com\"\n      }\n    ]\n  },\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.ErrorInfo\",\n    \"domain\": \"serviceusage.googleapis.com\",\n    \"reason\": \"AUTH_PERMISSION_DENIED\"\n  }\n]\n, forbidden"}
```

```shell
# kubectl get events --namespace cnrm-system
23m         Warning   UpdateFailed       service/pubsub.googleapis.com                        Update call failed: error fetching live state: error reading underlying resource: summary: Error when reading or editing Project Service projects/cnrm-system/services/: Request `List Project Services cnrm-system` returned error: Failed to list enabled services for project cnrm-system: googleapi: Error 403: Permission denied to list services for consumer container [projects/751327568111]...
```

### Steps to reproduce the issue
Follow the official guide to install Google Config Connector to a custom Kubernetes Cluster.

### YAML snippets

```yaml
# enable-pubsub.yaml
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: pubsub.googleapis.com
```

Then kubectl to fire the yaml.

```shell
kubectl apply -f enable-pubsub.yaml
```

What can I try to figure out what is wrong with the permissions?

**Comment by xiaobaitusi** [comment]
Hi @suckowbiz,

Looking at the error message blow, the root cause is that the controller thinks `cnrm-system` namespace name as the project id. You need to configure the namespace where the Config Connector resource objects live in per the second step in the 
[Before you begin](https://cloud.google.com/config-connector/docs/how-to/getting-started#before_you_begin) section.

By default, Config Connector expects the resource's namespace to match the Google Cloud project ID where it's created
For advanced patterns, you can read this [page](https://cloud.google.com/config-connector/docs/concepts/namespaces-and-projects) to learn more about how to associate k8s namespaces with GCP projects/folders/orgs   

Note that we don't recommend creating Config Connector resource objects in `cnrm-system` namespace because `cnrm-system` namespace is meant to be the namespace to hold Config Connector system components/workloads only. 

```
Error when reading or editing Project Service projects/cnrm-system/services/: Request `List Project Services cnrm-system` returned error: Failed to list enabled services for project cnrm-system: googleapi: Error 403: Permission denied to list services for consumer container...
```

**Comment by suckowbiz** [comment]
Hi @xiaobaitusi,

thank you very much for clarification. I switched to the namespace that I previously annotated with the desired project_id and triggered `kubectl` again. It worked as expected.

For the others running into Config-Connector-newbe things like this:

Config-Connector needs to determine what project, folder, or organization to create the resources in. This can either be described with the resource itself or with an annotation on the namespace (https://cloud.google.com/config-connector/docs/how-to/organizing-resources/overview).

My failure was to not having activated the annotated namespace. Config-Connector could not resolve the project_id because there was no one at the resource and none at the namespace `cnrm-system` that I accidentally used.

Thanks again,

I am going to close this issue.
