### ISSUE TITLE
Question: Config Connector direct download URL

### ISSUE THREAD

**Issue by suckowbiz** [GoogleCloudPlatform/k8s-config-connector#575]
Hi together,

I am evaluating Google Config Connector for my customer for production use. The company has an in-house Kubernetes solution so I am installing Config Connector as of "Install on other Kubernetes distributions" (https://cloud.google.com/config-connector/docs/how-to/install-other-kubernetes).

We are implementing a CI/CD pipeline that automatically installs the Kubernetes Config Connector manifests into a K8s cluster.  I am wondering if it could be possible to download Config Connector with a direct link without the need to have `gsutil` in place.

The installation docs say that Config Connector manifests are available via `gsutil cp gs://configconnector-operator/latest/release-bundle.tar.gz release-bundle.tar.gz`:

```shell
# gsutil cp gs://configconnector-operator/latest/release-bundle.tar.gz release-bundle.tar.gz
Copying gs://configconnector-operator/latest/release-bundle.tar.gz...
/ [1 files][  3.5 KiB/  3.5 KiB]                                                
Operation completed over 1 objects/3.5 KiB. 
```

**My Question is:** What is the officially supported direct download URL to download Config-Connector manifests that are appropriate for the mentioned installation how-to?

**Comment by caieo** [comment]
Hi @suckowbiz, thanks for reaching out to ask. Unfortunately, we don't have an officially supported direct download URL aside from using the `gsutil` commands you mentioned. We perform our release directly to our GCP storage buckets, which can only be accessed using that command. I'm not an expert with CI/CD pipelines, but is there a specific reason you're not able to use those commands to install Config Connector?

**Comment by suckowbiz** [comment]
Hi @caieo ,

thank you very much for your reply.

> I'm not an expert with CI/CD pipelines, but is there a specific reason you're not able to use those commands to install Config Connector?

I think that "issue" is not only specific to CI. It is just the fact, that you need an additional software to download a file. In our case this adds the need to manage and maintain that additional software which is something we want to avoid from the perspective of KISS principle (and operations).

It would be great if you could provide a direct download URL in the future.

**Comment by jcanseco** [comment]
@suckowbiz, thanks for elaborating. The request makes sense. 

I know you're using K8s on-prem, so you can't use the GKE add-on to install Config Connector.

That said, I'd like to bring your attention to [Config Controller](https://cloud.google.com/anthos-config-management/docs/concepts/config-controller-overview). It is effectively a Config Connector instance that is hosted and managed by GCP, removing the need to install and manage Config Connector yourself.

I mention this option in case it might actually be a better fit for your needs and also because I don't think we'll be able to get to your original request of providing a direct download URL very soon given the size of our backlog currently.

**Comment by jcanseco** [comment]
@suckowbiz, it turns out you can actually use the following URL to directly download the tarball without needing to use `gsutil`: https://storage.googleapis.com/cnrm/latest/release-bundle.tar.gz

**Comment by suckowbiz** [comment]
Hi  @jcanseco,

works as defined. Thank you very much!

I am closing this question now since it is totally answered .
