### ISSUE TITLE
Google Cloud Logging Log Based Metrics API Resource

### ISSUE THREAD

**Issue by minherz** [GoogleCloudPlatform/k8s-config-connector#579]
**Describe the feature or resource**
We use K8s to create Grafana dashboards on the fly. We need a way to show some information derived from Google Cloud Logging in the dashboards. Currently Grafana has the integration only with Google Cloud Monitoring. We can use this integration by creating log based metrics. For this we need a support to create log based metrics via Config Connector.

API: https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics

**Importance**
The absence of the support requires to create an expensive integration via 3rd party and is seen as a blocker for us.

**Comment by mbzomowski** [comment]
Hi @minherz! This resource has already been requested here: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/144, so we're already looking into adding it.
