### ISSUE TITLE
Spot option for containernodepools crd

### ISSUE THREAD

**Issue by MalulDekel** [GoogleCloudPlatform/k8s-config-connector#585]
**Describe the feature or resource**
Hey, in the docs there is option to create container node pools with type spot for it. 
Can we make it available on the crd also?
<img width="912" alt="image" src="https://user-images.githubusercontent.com/92375231/148213621-62c1727c-c458-4172-987d-5cb2d87302b9.png">
https://cloud.google.com/kubernetes-engine/docs/how-to/spot-vms

**Comment by maqiuyujoyce** [comment]
Hi @MalulDekel , thank you for requesting this new feature in `ContainerNodePool`. We're working on supporting it, and it should be out in our next release.

**Comment by MalulDekel** [comment]
@maqiuyujoyce Thanks for the great support
