### ISSUE TITLE
Supporting --server-dry-run

### ISSUE THREAD

**Issue by ismailbaskin** [GoogleCloudPlatform/k8s-config-connector#59]
Currently `cnrm-validating-webhook-configuration` ValidatingWebhookConfiguration does not support kubectl --server-dry-run . I think the problem can be solved by specifying the ValidatingWebhookConfiguration.webhooks[].sideEffects parameter.

**Comment by AlexBulankou** [comment]
@ismailbaskin , thanks for suggestion! marking as enhancement and we'll consider it in our planning.

**Comment by tonybenchsci** [comment]
Yeah having the ability to do diff or server-dry-run would really help with kcc pipelines.

**Comment by xiaobaitusi** [comment]
The version 1.13.1 now supports --server-dry-run.
