### ISSUE TITLE
Add support for pubsub topics which schemas

### ISSUE THREAD

**Issue by dcardinha** [GoogleCloudPlatform/k8s-config-connector#592]
It would be nice if config connector could support management of pubsub topics with schemas (protobuf and avro)

This feature would allow us to follow the principle of infrastructure as code for our topics which have schemas. Currently we rely on a not ideal process (with manual steps) to manage our topics

**Comment by jcanseco** [comment]
Hi @dcardinha, yep agreed. It seems there is already an existing issue for this request: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/435

Let us close this issue and move to that one instead.
