### ISSUE TITLE
unable to parse logging sink id

### ISSUE THREAD

**Issue by obito** [GoogleCloudPlatform/k8s-config-connector#614]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

Logging Sink is unable to parse the sink ID when we specify the projectRef: `logginglogsink-controller  Update call failed: error fetching live state: error importing resource: unable to parse logging sink id "projects/themecloud-dev###logginglogsink-sample"`.
When we don't, we get another error: ` Update call failed: error fetching live state: error importing resource: no sink type specified`

### Kubernetes Cluster Version

Client Version: v1.23.3
Server Version: v1.22.6-gke.300

### Config Connector Version

1.74.0
### Config Connector Mode

cluster

## Log Output

```
{"severity":"error","timestamp":"2022-02-24T09:37:59.405Z","logger":"controller.logginglogsink-controller","msg":"Reconciler error","reconciler group":"logging.cnrm.cloud.google.com","reconciler kind":"LoggingLogSink","name":"logginglogsink-sample","namespace":"cnrm-system","error":"Update call failed: error fetching live state: error importing resource: unable to parse logging sink id \"projects/themecloud-dev###logginglogsink-sample\""}
{"severity":"info","timestamp":"2022-02-24T09:38:54.461Z","logger":"logginglogsink-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"logginglogsink-sample"}}
{"severity":"error","timestamp":"2022-02-24T09:38:54.479Z","logger":"controller.logginglogsink-controller","msg":"Reconciler error","reconciler group":"logging.cnrm.cloud.google.com","reconciler kind":"LoggingLogSink","name":"logginglogsink-sample","namespace":"cnrm-system","error":"Update call failed: error fetching live state: error importing resource: unable to parse logging sink id \"projects/themecloud-dev###logginglogsink-sample\""}
{"severity":"info","timestamp":"2022-02-24T09:40:54.480Z","logger":"logginglogsink-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"logginglogsink-sample"}}
{"severity":"error","timestamp":"2022-02-24T09:40:54.497Z","logger":"controller.logginglogsink-controller","msg":"Reconciler error","reconciler group":"logging.cnrm.cloud.google.com","reconciler kind":"LoggingLogSink","name":"logginglogsink-sample","namespace":"cnrm-system","error":"Update call failed: error fetching live state: error importing resource: unable to parse logging sink id \"projects/themecloud-dev###logginglogsink-sample\""}
```

### Steps to reproduce the issue

Apply the YAML, and get the logs of the loggingsink: `kubectl -n cnrm-system describe logginglogsink logginglogsink-sample`
### YAML snippets

```yaml
  apiVersion: logging.cnrm.cloud.google.com/v1beta1
  kind: LoggingLogSink
  metadata:
    name: logginglogsink-sample
  spec:
    projectRef:
      external: "projects/themecloud-dev"
    destination:
      storageBucketRef:
        name: logbucket-sample
    filter: resource.type="bigquery_project"
```

**Comment by caieo** [comment]
Hi @obito, thanks for filing this issue and I'm sorry you ran into this. I was able to reproduce your issue and agree that it might be a small bug on our side. As a workaround, I suggest removing the `projects/` prefix in your `projectRef.external` field. I made sure this worked on my side and the error did not appear, but please let us know if you run into other problems.

**Comment by obito** [comment]
> Hi @obito, thanks for filing this issue and I'm sorry you ran into this. I was able to reproduce your issue and agree that it might be a small bug on our side. As a workaround, I suggest removing the `projects/` prefix in your `projectRef.external` field. I made sure this worked on my side and the error did not appear, but please let us know if you run into other problems.

Thanks for the quick answer. Indeed I have another issue that I pointed here #617
