### ISSUE TITLE
sqlinstance diskSize

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#62]
would it maybe make sense to make the `diskSize` field in the `SQLInstance` a kind of `minDiskSize`, if the database grows, we wouldn't need to adjust the `diskSize` in the `SQLInstance`  to avoid the controller complaining about not being able to shrink the disk...

**Comment by AlexBulankou** [comment]
@nrobert13 thanks for your suggestion. I don't think `minDiskSize` would be possible with available API, however did you consider not specifying `diskSize` and instead leaving default `diskAutoresize` field to true. This will ensure automated storage increate is happening as explained [here](https://cloud.google.com/sql/docs/postgres/instance-settings) - see `Automatic Storage Increase`.
Does it address your scenario?

**Comment by nrobert13** [comment]
@AlexBulankou, yeap diskAutoresize would address my concern. was wondering if there's use case for setting diskSize and disabling diskAutoresize, this would be the only option diskSize would make sense in cnrm context, where a continuous reconciliation happens....

**Comment by toumorokoshi** [comment]
I'll close the issue as the question was answered.

To the question regarding why expose diskSize at all: Definitely agreed that this is a less valuable use case in the world where continuous reconciliation might reduce the size of a disk to something something undesired. However, we include the value for completeness. 

It may be possible that someone has very stringent requirements for disk size (e.g. to ensure that cost is not an issue), and I think it would be better to enable the use case, even if it's rare.

philosophically I don't think Config Connector should be put it a position where it restricts what one can or cannot express.
