### ISSUE TITLE
storagebucket specs

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#63]
hey Guys,

how could I specify `location`, `location type` and `access control type` for a `storagebucket`?
I cannot find it in the sample manifest.

thanks.

**Comment by spew** [comment]
Hi nrobert13,

The `location` can be specified at the spec level. We do not support `location type`. For `access control type` do you mean what is made available by the KCC type `StorageBucketAccessControl` ?

**Comment by kibbles-n-bytes** [comment]
We support setting `location` via our `spec.location` field, and support setting access controls with the `StorageBucketAccessControl` type. `locationType` on the underlying API is not a writable field.

Going to close out this issue; feel free to open another one if there are any additional questions on how to configure storage buckets.
