### ISSUE TITLE
`client-go` Code Generation

### ISSUE THREAD

**Issue by axisofentropy** [GoogleCloudPlatform/k8s-config-connector#64]
We're planning to use Config Connector through the Go Kubernetes Client and it's pretty difficult to use with Custom Resource Definitions like those used by Config Connector.  Is there an accompanying extra library to make this easier?  Maybe y'all can use code generation to supply a library?

**Comment by spew** [comment]
Hi @axisofentropy, can you describe a bit more about your application which requires it to talk to the K8s APIs directly? Is this simply so you can avoid calling out to `kubectl` within a go application that creates infrastructure or something different?

**Comment by axisofentropy** [comment]
Yeah lots of automation, provisioning resources for each of our customers.
And coordinating with a database, so we're keeping tight transactions.

**Comment by caieo** [comment]
Hi @axisofentropy , thanks for putting this on our radar and providing us the context in which you will be using this. We don't have immediate plans to supply an extra library for interacting directing with K8s API yet, but it is a feature that has been requested by other customers and is important for us to get to. We'll make sure to update this thread when we add it to Config Connector!

**Comment by n1koo** [comment]
As is, this tool is pretty useless for any end-to-end automation like provisioning a database and letting a pod use it directly.

`Deployment` etc resources can't use any data in CRs so even though we have `Host` address etc in the `Status` field of the CR that cannot be consumed directly by `Pod`s.

I was thinking of building a tool to bridge this gap and output these things that `Pod`s need to `ConfigMap`s and `Secret`s but since libraries aren't available its pretty clumsy. 

Right now best option is to dynamically recreate these in your own code with eg. dynamic support ( https://soggy.space/namespaced-crds-dynamic-client/ ) but since we have no idea how the API is gonna change this is not only error prone but likely to break in the future.

**Comment by spew** [comment]
Hi @n1koo ,

Thanks for sharing the limitations you are running into. Referencing the fields & values in a config connector resource is something we want to provide help with and are experimenting with some solutions right now.

**Comment by n1koo** [comment]
@spew awesome! I understand `config-connector` is in beta and that you mentioned that you are only just testing, but any idea of a timeline where we might be able to take it for a drive?

**Comment by spew** [comment]
Unfortunately I cannot share more in this forum, but if you would like we can schedule a video-meeting and go over what we are thinking.

**Comment by AeroNotix** [comment]
Being able to create google resources via kubectl is very useful and a very welcome addition to using kubernetes on GCP. That said, there are definite use-cases where people would like to create their own operators which include creating Google resources.

Having access to the source code simply to reference the types in our own operators makes life much simpler.

**Comment by whizard** [comment]
Any update for this? Without this it is very difficult to create operators to use GCP resources. Could someone at least give us options on how to do this?

**Comment by spew** [comment]
Hello @whizard we are prioritizing this for the team as this is an important ask from multiple customers. I apologize for the delay, at this time I do not have a date to share, but will update when we do.

**Comment by whizard** [comment]
Thanks for the response. We are eagerly waiting for your update.

**Comment by errordeveloper** [comment]
I am also very keen to see this, I am going to try something in the meantime and post an update if I find a feasible solution.

**Comment by errordeveloper** [comment]
I did find that it was quite easy to use turn JSON manifests into `unstructured.UnstructuredList` and then I was able to pass those to `k8s.io/controller-runtime` client. The only trick I've had to implement was scheme registration, I basically have this:

``` 
// Package  API Schema definitions for the CNRM API
package cnrm

import (
        "k8s.io/apimachinery/pkg/runtime/schema"
        "sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
        GroupVersion  = schema.GroupVersion{Group: "container.cnrm.cloud.google.com", Version: "v1beta1"}
        SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}
        AddToScheme   = SchemeBuilder.AddToScheme
)
```

And in `main.go`, the `init` function looks like this:
```

func init() {
        _ = clientgoscheme.AddToScheme(scheme)

        _ = myapiv1alpha1.AddToScheme(scheme)
        // +kubebuilder:scaffold:scheme

        // register Config Connector scheme, so that the client can access its objects
        _ = cnrm.AddToScheme(scheme)
}
```

**Comment by spew** [comment]
Hello, we will release generated go clients in the very near future.

**Comment by evalsocket** [comment]
@spew Do you have any date for release ?

**Comment by caieo** [comment]
Hi @evalsocket, we're aiming to release this in next week's release.

**Comment by caieo** [comment]
Update: we ran into a blocker that delayed this release but we have all the go clients for our CRDs staged for next week's release.

**Comment by aw185176** [comment]
Any update on this?

**Comment by kibbles-n-bytes** [comment]
Our latest release, 1.39.0, includes the initial release of the Go structs and client libraries: https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/generated/pkg . Please give things a try and let us know if you have any issues.

**Comment by toumorokoshi** [comment]
@caieo can we close this issue? since the go clients are not available.

**Comment by caieo** [comment]
Yep, we can close this issue now that go-clients are available.
