### ISSUE TITLE
Need DLP , SCC and Cloud Armor YAML template 

### ISSUE THREAD

**Issue by vivek725k** [GoogleCloudPlatform/k8s-config-connector#640]
Hi Team , 

Request you to provide the YAML template for below google services-

- DLP
- Security command center (SCC)
- Cloud Armor 

respective templates are not available with GCP config connector

**Comment by vivek725k** [comment]
please add the BeyondCorp enterprise YAML templets as well

**Comment by caieo** [comment]
Hi @vivek725k, are you asking for samples or new resource you'd like Config Connector to support? If you're asking for specific resource coverage support, please fill out the necessary information in our Enhancement issue template: "New Issue" > "Enhancement"

**Comment by caieo** [comment]
Closing this because it looks like @vivek725k filed #642.
