### ISSUE TITLE
Need YAML templets for DLP, Security Command Center, Beyond Corp and Cloud Armor

### ISSUE THREAD

**Issue by vivek725k** [GoogleCloudPlatform/k8s-config-connector#642]
## Checklist

- [ ] I did not find a related open enhancement request.  - No 
- [ ] I understand that enhancement requests filed in the GitHub repository are by default low priority. - Yes
- [ ] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).- Yes

## Describe the feature or resource
Need only basic YAML templets for DLP, Security Command Center, Beyond Corp and Cloud Armor as its not available in config connector

**Comment by caieo** [comment]
@vivek725k, I'm assuming you're asking for resource support for these 4 services ([DLP](https://cloud.google.com/dlp/docs/reference/rest), [Security Command Center](https://cloud.google.com/security-command-center/docs/reference/rest), [Beyond Corp](https://cloud.google.com/beyondcorp-enterprise/docs/reference), [Cloud Armor](https://cloud.google.com/armor/docs/apis)), but after taking a look at them I think there are a lot of possible resources that would need to be supported for this. Can you please elaborate which resources you need to support in particular? Or if there is an order of resources/services that you are requesting support for? 

I'd also like to emphasize that we cannot appropriately prioritize your request unless you provide some context around the importance of it. Seeing that you marked the issue as time-sensitive, I also assume you filed a corresponding issue with GCP support that will help provide additional context behind your request. Is this request a blocker, nice-to-have, or friction point for you?

**Comment by vivek725k** [comment]
yes these four services are road blocker for us at least we required the  YAMAL templets as reference based on this we can add some values there and use as blueprint with current assignment

**Comment by caieo** [comment]
@vivek725k, I'm sorry this is a road blocker for you, but I need you to specify *which* resources in these services you need. Each service looks like it has 5-10 separate resources, which is fine to request, but we will need you to list them and file separate issues for them. Take a look at this resource request that was completed for example: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/539.

**Comment by vivek725k** [comment]
ok , will update you shortly

**Comment by diviner524** [comment]
@vivek725k Thank you for providing the extra context! Could you please file separate requests for each of the resources you mentioned? It will be easier to track and manage different resource requests separately.

- Here is a [link](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/new?assignees=&labels=enhancement&template=enhancement.md) to file a new "resource request" for Config Connector.
- Here is an [example](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/586) "resource request".
  
It will also be helpful if you can include more details in each requests, ex: The link to corresponding Terraform resource page, or the link to the GCP REST API reference doc.

**Comment by diviner524** [comment]
Closing this issue as we are tracking resource requests in respective threads.

**Comment by vivek725k** [comment]
Hi team , this not a DLP YAML template , please provide the correct the template for same.

**Comment by diviner524** [comment]
@vivek725k could you please comment on the specific issue thread?

Were you referring to #644?

Note that we will need your help to specify the exact GCP resource you would like to support.

It would be great if you can provide a link to the REST resource page. Ex, you can specify:

```
We would like Config Connector to support DLP jobTriggers resource:

https://cloud.google.com/dlp/docs/reference/rest/v2/projects.jobTriggers
```

**Comment by vivek725k** [comment]
Hi Team , based on the resource which you shared please arrange the generic Blueprint/YAML templated which can trigger the jobs and scanning for project.
