### ISSUE TITLE
Upgrade to GKE 1.21 caused cnrm-deletiondefender (1.63.0) to go into CrashloopBackOff; User "system:serviceaccount:cnrm-system:cnrm-deletiondefender" cannot list resource

### ISSUE THREAD

**Issue by jketcham** [GoogleCloudPlatform/k8s-config-connector#651]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

I just upgraded my GKE cluster to v1.21 and after the control plane was updated, I started getting CrashloopBackOff errors from the `cnrm-deletiondefender` Pod. All other Config Connector pods are running without issue, and all pods are running on nodes at the same version as the cluster control plane.

A couple weeks ago I upgraded to k8s 1.20 without issue, and haven't changed any cluster wide settings related to serviceaccounts that deal with Config Connector, or anything related to Config Connector for that matter.

Workload Identity is enabled for the cluster and permission issues have not been a problem in the past.

Is there some setting I'm missing that Config Connector needs to continue working?

### Kubernetes Cluster Version

`1.21.5-gke.1805`

### Config Connector Version

`1.63.0`

### Config Connector Mode

`cluster`

## Log Output

I'm seeing errors like the one below for many different API groups, which `sourceLocation` indicates is coming from the `reflector.go` file, line `138`:
```
sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: privatecacapools.privateca.cnrm.cloud.google.com is forbidden: User "system:serviceaccount:cnrm-system:cnrm-deletiondefender" cannot list resource "privatecacapools" in API group "privateca.cnrm.cloud.google.com" at the cluster scope
```

followed by many messages like this:
```
failed to wait for identityplatformtenant-deletion-defender-controller caches to sync: timed out waiting for cache to be synced
```

### Steps to reproduce the issue

Run a GKE cluster at version 1.20 with Config Connector version 1.63.0 and upgrade to 1.21?

### YAML snippets

n/a

**Comment by maqiuyujoyce** [comment]
@jketcham Thank you for your feedback.

> Is there some setting I'm missing that Config Connector needs to continue working?

No, there shouldn't be.

I tried to reproduce the issue but the deletion defender seems to be working fine after GKE version upgrade. More specifically, I did the following:

1. Created a GKE cluster with the static version 1.20.15-gke.5000.
2. Installed Config Connector v1.63.0 in the cluster mode, and created a PubSubTopic resource.
3. Upgraded the GKE cluster to 1.21.5-gke.1805, and upgraded all the node pools to the same version.
4. Checked the status of pod `cnrm-deletiondefender-0`, deleted the pod and waited for it to be recreated, also deleted the PubSubTopic resource.

Could you provide more details about your issue? Not sure if I've missed any steps.

Meanwhile, could you try to upgrade the Config Connector to [v1.75.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.75.0) or above? Config Connector v1.63.0 is depending on [controller-runtime v0.9.7](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.9.7), which seems to only `Update dependencies to Kubernetes v1.21.4`. And since v1.75.0, Config Connector is depending on [controller-runtime v0.11.1](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.11.1). I wondered if the forward compatibility of controller-runtime could be relevant.

**Comment by jketcham** [comment]
Hi @maqiuyujoyce, thanks for taking a look! 

Since I've installed Config Connector through the cluster add-on, I'm not sure how I can manually trigger an upgrade, are there docs on that somewhere I can reference?

As for more details, I'm afraid those logs are all I have to go off of, seems like something wrong with the cluster service account and how it talks with its gcloud IAM service account? Some sort of disconnect there? If there's somewhere I can get more info to include here I can do that.

I did open a ticket with gcloud support and apparently this issue is known and fixed in KCC >= 1.67.0. They suggested I upgrade to k8s 1.22 to get the fix, but our cluster is on the stable release channel and 1.21 is the most recent version available (and we need to update some other configs ahead of upgrading to 1.22 as well). I was hoping there'd be some fix I can manually apply, or KCC 1.67 could get included in a 1.21 release.

**Comment by maqiuyujoyce** [comment]
Hi @jketcham , thank you for the further clarification!

If you installed Config Connector via the GKE add-on, then the issue might be that your GKE cluster upgrade caused a downgrade of Config Connector. Within GKE 1.21, you can try to upgrade the cluster to 1.21.8-gke.1800, 1.21.8-gke.1900, 1.21.8-gke.2000 or 1.21.8-gke.2100 to upgrade Config Connector to 1.70.0.

**Comment by jketcham** [comment]
Hey @maqiuyujoyce, I just got another response on my support ticket that indeed said there is/was an issue when upgrading from 1.20 to 1.21 that downgraded Config Connector.

I'll look out for a new 1.21 release on the stable channel, but currently I'm at the latest version available `1.21.5-gke.1805` (that I can see in the UI version select).

While we wait for a new release in the stable channel, I was curious about what specifically deletiondefender handles for Config Connector, so I can know what to look for if something goes wrong in the mean time? Is it just making sure that cloud resources defined in Config Connector get recreated if they get deleted for some reason outside of the Config Connector system?

**Comment by maqiuyujoyce** [comment]
Hi @jketcham , thank you for the follow up.

> I was curious about what specifically deletiondefender handles for Config Connector, so I can know what to look for if something goes wrong in the mean time?

The deletion defender is to protect the underlying GCP resources from being deleted unexpectedly when there is an accidental CRD deletion or when you uninstall Config Connector.

> Is it just making sure that cloud resources defined in Config Connector get recreated if they get deleted for some reason outside of the Config Connector system?

Actually drift-correction is handled by cnrm-controller-manager.

**Comment by jketcham** [comment]
Ok great, thanks for that info @maqiuyujoyce! 

I think I'm good to close this issue out, if anything else comes up I'll re-open it 👍
