### ISSUE TITLE
Support includeBuildLogs in cloud build triggers

### ISSUE THREAD

**Issue by erik-carlson** [GoogleCloudPlatform/k8s-config-connector#667]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Cloud build triggers recently added an option to stream logs to GitHub along with build status using the includeBuildLogs field and I would like to be able to enable that with cloud build triggers that I'm creating with KCC.

### Additional information

https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger.IncludeBuildLogs

### Importance

This would be a nice to have.  Users can get logs by clicking through to view them in cloud logging, but it would make the developer experience better to not have to leave GitHub to see results of the cloud build job beyond status.

**Comment by maqiuyujoyce** [comment]
Hi @erik-carlson , thank you for the request! We've added it to the list of field requests we're looking into and will let you know when we have more information.

**Comment by jcanseco** [comment]
Added in [KCC 1.90.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.90.0).
