### ISSUE TITLE
Add support for cdnPolicy.cacheKeyPolicy.includeNamedCookie

### ISSUE THREAD

**Issue by zlk89** [GoogleCloudPlatform/k8s-config-connector#677]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

From the doc: https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computebackendservice it appears, `cdnPolicy.cacheKeyPolicy.includeNamedCookie` is not supported yet.

But it actually is supported on gcloud  CDN: https://cloud.google.com/cdn/docs/using-cache-keys#updating_cache_keys_to_use_named_cookies

**Comment by maqiuyujoyce** [comment]
Hi @zlk89 , thank you for the request. This field should be supported in the next release of Config Connector.

**Comment by andypanix** [comment]
Hi, any update on this? Has a possible release date been planned? 

Thx

**Comment by diviner524** [comment]
@andypanix it was introduced a while back and you can find it in the resource reference doc:

https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computebackendservice

Please make sure you are using a proper installation methods to get a more recent version of Config Connector. If you are using GKE Add-on with some early GKE minor version you will have a significant lag behind the latest Config Connector version. 

https://cloud.google.com/config-connector/docs/concepts/installation-types#installation_methods

**Comment by andypanix** [comment]
Ah, thank you very much, I suspect at this point that I have an outdated version of config connector. Thanks
