### ISSUE TITLE
DNSRecordSet v1beta2 not available on cluster

### ISSUE THREAD

**Issue by whyvez** [GoogleCloudPlatform/k8s-config-connector#680]
### Describe your question

I'm trying to use the lastest `DNSRecordSet` CRD so I can use the `rrdatasRefs` field [added May 10 in ConfigConnector 1.84](https://cloud.google.com/config-connector/docs/release-notes#May_10_2022).

If I use the latest `DNSRecordSet` schema I was get the following error:

```
error validating data: [ValidationError(DNSRecordSet.spec): unknown field "rrdatasRefs" in com.google.cloud.cnrm.dns.v1beta1.DNSRecordSet.spec, ValidationError(DNSRecordSet.spec): missing required field "rrdatas" in com.google.cloud.cnrm.dns.v1beta1.DNSRecordSet.spec]
```

Looks like I might be on an earlier version of config-connector that does not include this newer resource version.

I could only find one reference to [ConfigConnector upgrade](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall) but it's quite vague.

I upgraded my cluster to `1.23.5-gke.1503` thinking that might install the version I'm looking for, but the same issues persisted.

I think the config connector reference docs should have a GKE version selector, otherwise, the documentation is inaccurate and misleading.

At this point, I am blocked and would really appreciate some insight into how I can get the latest `DNSRecordSet` running on my cluster.

The [documentation](https://cloud.google.com/config-connector/docs/reference/resource-docs/dns/dnsrecordset) is also be missleading. Looks like this new resource is part of `v1beta2` but the examples show using `v1beta1`

Another solution I thought of is updating the `ConfigConnector` resource from `v1beta1` to `v2beta2`.

**Comment by maqiuyujoyce** [comment]
Hi @whyvez , thanks for reaching out and sorry you've got confused by the documentation.

IIUC, you are using Config Connector via the GKE add-on and your GKE cluster version is `1.23.5-gke.1503`, right? Unfortunately, the latest version of Config Connector supported on GKE 1.23 via the add-on is `1.82.0`, so it doesn't contain the change you need. You can verify your Config Connector version by running `kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'` on your GKE cluster.

If you want to upgrade Config Connector to 1.84.0 or above, you'll need to install Config Connector via the [advanced install options](https://cloud.google.com/config-connector/docs/how-to/advanced-install). You'll be able to choose the exact version you want to install (or just install the latest version).

**Comment by maqiuyujoyce** [comment]
And following are some clarifications of your questions and confusions:

> I could only find one reference to [ConfigConnector upgrade](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall) but it's quite vague.
>
> I upgraded my cluster to 1.23.5-gke.1503 thinking that might install the version I'm looking for, but the same issues persisted.
>
> I think the config connector reference docs should have a GKE version selector, otherwise, the documentation is inaccurate and misleading.

Thanks for the suggestion! We understand that this is a friction point for GKE add-on users and have been considering improving it by providing a version mapping doc. Unfortunately it's not easy to achieve so we're still looking into it.

> The [documentation](https://cloud.google.com/config-connector/docs/reference/resource-docs/dns/dnsrecordset) is also be missleading. Looks like this new resource is part of v1beta2 but the examples show using v1beta1
>
> Another solution I thought of is updating the ConfigConnector resource from v1beta1 to v2beta2.

In the documentation, the version in the table is part of the `Google Cloud REST Resource Name`, so `v2beta2` is the version of the underlying GCP API, but not the version of the corresponding Config Connector resource. `v1beta1` is the correct version for the DNSRecordSet Config Connector resource, and it is actually a shared version across all the Config Connector resources at the moment. You can find it either in the CRD or in the samples.

**Comment by whyvez** [comment]
Thank you for your suggestions. I've gone ahead and installed ConfigConnector manually and can now provision using the `v1beta2.DNSRecordSet`. Super happy this landed, it was the first thing that was blocking me from using ConfigConnector when I initially looked at it last year.
