### ISSUE TITLE
Add support for managedPrometheusConfig in ContainerCluster resource

### ISSUE THREAD

**Issue by wmuizelaar** [GoogleCloudPlatform/k8s-config-connector#683]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [ ] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

I would like to enable Managed Prometheus on our GKE clusters with config connector.

Currently it is already possible to use with Terraform (see https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_monitoring_config). Would it be possible to add this to Config Connector as well?

### Additional information

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.MonitoringConfig shows it's possible to set a managedPrometheusConfig.

### Importance

We can work around it for now by enabling it manually through the console, but that's not quite declarative ;-)

**Comment by diviner524** [comment]
@wmuizelaar Thanks for the enhancement suggestion! Yes we are currently working on this, and Managed Prometheus should be supported in the next Config Connector release.

**Comment by jcanseco** [comment]
Added in [KCC 1.90.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.90.0).
