### ISSUE TITLE
Configure Copybara to set proper commit title

### ISSUE THREAD

**Issue by tsawada** [GoogleCloudPlatform/k8s-config-connector#685]
Currently, Copybara formats all commit messages as:
```
Automated Config Connector import.

- <commit hash> <commit title> <commit message, all in a single line>
```
which makes it hard to find what has changed from the commit history.

Please configure Copybara to mirror the original commit message format as much as possible.

**Comment by diviner524** [comment]
@tsawada Thank you for the feedback! We have created an internal work item to track this improvement. 

Our eventual goal is to use GitHub repo as source of truth, which should eliminate this problem!

**Comment by tsawada** [comment]
it'd be great if you could revisit this. It is quite a barrier for people outside to collaborate with the repository.

**Comment by diviner524** [comment]
@tsawada Definitely and sorry for not making much progress on this front. We plan to start the migration and switch to GitHub as source of truth in Q1 2023, which should solve this problem.

**Comment by tsawada** [comment]
It's been more than a year and the commit history is still being quite useless. I feel this is unfortunate because in my opinion this is keeping contributors away, although Config Connector is being actively developed and the fix is only a few lines of Copybara config change.
I understand the team is busy but it'd be great if you could revisit this. Thanks!

**Comment by diviner524** [comment]
@tsawada Thanks a lot for sharing your thoughts, and I completely get why this might be frustrating.

Just to clarify, the situation is a bit more intricate than simply adjusting the Copybara config.

The real challenge is to ensure that we clean our internal commit history to prevent any customer PII from being exposed.

The most effective approach is to transition to utilizing this GitHub repository as the source of truth for the project. This way, contributors will have a clearer understanding that they're contributing to an open-source project. This transition is currently underway, as we're integrating more tools and GitHub workflow support into the repository.

**Comment by tsawada** [comment]
Hi Shuxian, thank you for getting back. I know you've been working very hard on the project and I really appreciate what you've done.
Regarding the config and PII, what I'm looking for is, instead of

```
Automated Config Connector import. 

  - d20faeb5f478dcd0ec4174fff992d9a6a6123a95 Improvements on OSS Getting Started Guide by Config Connector Team <no-reply@google.com>

GitOrigin-RevId: d20faeb5f478dcd0ec4174fff992d9a6a6123a95
```
Just make it like this:

```

**Comment by diviner524** [comment]
Mark this as closed since we are now using GitHub as our source of truth.
