### ISSUE TITLE
PubSubTopic IAMPolicy Bindings from two namespaces aren't merged

### ISSUE THREAD

**Issue by karlbunnell** [GoogleCloudPlatform/k8s-config-connector#688]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Namespace Scoped Config Connector.
I create unique gsa (google service accounts) in two namespaces using Config-Connector that bind to the same PubSubTopic resource.
I observe the bindings switching between those defined in one namespace (a) to those bound in namespace (b). 

### Additional Diagnostic Information

For example:
 % gcloud pubsub topics get-iam-policy sps-user-management-ds                                        
bindings:
- members:
  - serviceAccount:ams-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:gc-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:um-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  role: roles/pubsub.publisher
- members:
  - serviceAccount:ams-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:gc-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:um-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  role: roles/pubsub.viewer
etag: BwXkWwEwEK4=
version: 1

(wait some time, maybe 10 minutes) Run it again:

gcloud pubsub topics get-iam-policy sps-user-management-ds
bindings:
- members:
  - serviceAccount:ams-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:gc-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:um-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  role: roles/pubsub.publisher
- members:
  - serviceAccount:ams-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:gc-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  - serviceAccount:um-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
  role: roles/pubsub.viewer
etag: BwXkWnzOsW4=
version: 1

What I'd expected was for these to be merged (all bindings for sidea and sideb to be merged as a single set). If I look at a description of the IAMPolicy objects for both namespaces they are as follows:

----------------------------
kubectl describe IAMPolicy iampolicy-um-biz-pub-binding-sidea-ds --namespace sedicdsaas-pubsub-wi-test  
W0721 19:38:26.963057   35131 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Name:         iampolicy-um-biz-pub-binding-sidea-ds
Namespace:    sedicdsaas-pubsub-wi-test
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: icds-dev-stage-wi-test-release2
              meta.helm.sh/release-namespace: sedicdsaas-pubsub-wi-test
API Version:  iam.cnrm.cloud.google.com/v1beta1
Kind:         IAMPolicy
Metadata:
  Creation Timestamp:  2022-07-22T00:56:39Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
    cnrm.cloud.google.com/deletion-defender
  Generation:  1
  Managed Fields:
    API Version:  iam.cnrm.cloud.google.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:bindings:
        f:resourceRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
    Manager:      helm
    Operation:    Update
    Time:         2022-07-22T00:56:39Z
    API Version:  iam.cnrm.cloud.google.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cnrm.cloud.google.com/deletion-defender":
          v:"cnrm.cloud.google.com/finalizer":
      f:status:
        .:
        f:observedGeneration:
    Manager:      cnrm-controller-manager
    Operation:    Update
    Time:         2022-07-22T00:56:42Z
    API Version:  iam.cnrm.cloud.google.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
    Manager:         cnrm-controller-manager
    Operation:       Update
    Subresource:     status
    Time:            2022-07-22T00:56:42Z
  Resource Version:  1215685704
  UID:               ad4a78ba-1192-4f60-9b09-e6927662d28a
Spec:
  Bindings:
    Members:
      serviceAccount:ams-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.publisher
    Members:
      serviceAccount:ams-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.viewer
    Members:
      serviceAccount:um-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.publisher
    Members:
      serviceAccount:um-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.viewer
    Members:
      serviceAccount:gc-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.publisher
    Members:
      serviceAccount:gc-pubsub-gsa-sidea-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.viewer
  Resource Ref:
    API Version:  pubsub.cnrm.cloud.google.com/v1beta1
    Kind:         PubSubTopic
    Name:         sps-user-management-ds
Status:
  Conditions:
    Last Transition Time:  2022-07-22T00:56:42Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Observed Generation:     1
Events:
  Type     Reason              Age                From                  Message
  ----     ------              ----               ----                  -------
  Warning  DependencyNotFound  41m (x3 over 41m)  iampolicy-controller  reference PubSubTopic sedicdsaas-pubsub-wi-test/sps-user-management-ds is not found
  Normal   UpToDate            41m                iampolicy-controller  The resource is up to date

-----------------------------------------
Now look at the IAMPolicy object for the other namespace:

kubectl describe IAMPolicy iampolicy-um-biz-pub-binding-sideb-ds --namespace sedicdsaas-pubsub-wi-test2 
W0721 19:53:00.166516   39058 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Name:         iampolicy-um-biz-pub-binding-sideb-ds
Namespace:    sedicdsaas-pubsub-wi-test2
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: icds-dev-stage-wi-test-release2
              meta.helm.sh/release-namespace: sedicdsaas-pubsub-wi-test2
API Version:  iam.cnrm.cloud.google.com/v1beta1
Kind:         IAMPolicy
Metadata:
  Creation Timestamp:  2022-07-22T00:32:37Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
    cnrm.cloud.google.com/deletion-defender
  Generation:  1
  Managed Fields:
    API Version:  iam.cnrm.cloud.google.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:bindings:
        f:resourceRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
    Manager:      helm
    Operation:    Update
    Time:         2022-07-22T00:32:37Z
    API Version:  iam.cnrm.cloud.google.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cnrm.cloud.google.com/deletion-defender":
          v:"cnrm.cloud.google.com/finalizer":
      f:status:
        .:
        f:observedGeneration:
    Manager:      cnrm-controller-manager
    Operation:    Update
    Time:         2022-07-22T00:32:48Z
    API Version:  iam.cnrm.cloud.google.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
    Manager:         cnrm-controller-manager
    Operation:       Update
    Subresource:     status
    Time:            2022-07-22T00:32:48Z
  Resource Version:  1215663125
  UID:               57b7309c-4221-4c41-819a-674cbfdb6587
Spec:
  Bindings:
    Members:
      serviceAccount:ams-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.publisher
    Members:
      serviceAccount:ams-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.viewer
    Members:
      serviceAccount:um-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.publisher
    Members:
      serviceAccount:um-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.viewer
    Members:
      serviceAccount:gc-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.publisher
    Members:
      serviceAccount:gc-pubsub-gsa-sideb-ds@saas-dev-sed-sharedicd-gke.iam.gserviceaccount.com
    Role:  roles/pubsub.viewer
  Resource Ref:
    API Version:  pubsub.cnrm.cloud.google.com/v1beta1
    Kind:         PubSubTopic
    Name:         sps-user-management-ds
Status:
  Conditions:
    Last Transition Time:  2022-07-22T00:32:48Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Observed Generation:     1
Events:                    <none>

I've checked the Config-Connector logs, no errors. Everything appears to be fine but obviously the IAM bindings keep changing between the gsa's from each namespace. 

### Kubernetes Cluster Version

k version --short Flag --short has been deprecated, and will be removed in the future. The --short output will become the default. W0721 19:57:54.369474   40580 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead. To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke Client Version: v1.24.1 Kustomize Version: v4.5.4 Server Version: v1.22.9-gke.1300 WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

### Config Connector Version

1.71.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

The objective is to share a PubSubTopic between two namespaces so services (using Workload identity) in each NameSpace can both publish to the same topic.

1. Create a PubSubTopic in namespace 1 (e.g shared_topic)
2. Create a PubSubTopic in namespace 2 (e.g. shared_topic)
3. Create gsa in namespace 1 (e.g. gsa-ns1)
4. Create gsa in namespace 2 (e.g. gsa-ns2)
5. Create IAMPolicy that binds gsa-ns1 to shared_topic
6. Create IAM Policy that binds gsa-ns1 to shared_topic

### YAML snippets

```YAML
For step 5 above:
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  labels:
  name: {{ $iamPolicyName }}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: shared_topic
  bindings:
    - members:
        - {{ $gsaNs1 }}
      role: roles/pubsub.publisher
    - members:
        - {{ $gsaNs1 }}
      role: roles/pubsub.viewer    

For step 6 above:
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  labels:
  name: {{ $iamPolicyName }}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: shared_topic
  bindings:
    - members:
        - {{ $gsaNs2 }}
      role: roles/pubsub.publisher
    - members:
        - {{ $gsaNs2 }}
      role: roles/pubsub.viewer
```

**Comment by jcanseco** [comment]
Hi @karlbunnell, that is intentional: `IAMPolicy` is meant to be _authoritative_ (see top paragraphs in [IAMPolicy doc](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampolicy)).

I believe what you want to use instead is [IAMPartialPolicy](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampartialpolicy) which is non-authoritative (see linked doc for an explanation of how it works).

Let us know if that works for you.

**Comment by karlbunnell** [comment]
I've confirmed that IAMPartialPolicy merges bindings when invoked from two different name spaces. Thank you. closing.
