### ISSUE TITLE
Configuring memory/cores for PostgresSQLInstance

### ISSUE THREAD

**Issue by marcoderama** [GoogleCloudPlatform/k8s-config-connector#69]
When creating a PostgresSQL instance from the GUI, one can configure
   * memory
   * cores
(This also seems to be the way to go based on https://cloud.google.com/sql/docs/postgres/instance-settings.)

Is there a way to configure those using SQLInstance configs?  I don't see how...  The CRD does allow one to specify the tier though.  Is one expected to manage memory/cores specs indirectly by tier choice?

(Bonus question: Any way to configure an Automatic Storage Increase Limit?)

**Comment by AlexBulankou** [comment]
For `tier` parameters you can specify one of the predefined machine types from [Machine Types Spec](https://cloud.google.com/compute/docs/machine-types), for example, `db-f1-micro` or a custom machine type using [GCP custom machine types spec](https://cloud.google.com/dataproc/docs/concepts/compute/custom-machine-types#understand_custom_machine_types_first), for example, `db-custom-6-23040`. 


To your second question, [storageAutoResizeLimit](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances#settings.storageAutoResizeLimit)  is not currently supported with Config Connector, so you can either specify `diskSize` (note, it can only be increased, not decreased) or set `diskAutoresize` to `true` ([more details](https://cloud.google.com/sql/docs/postgres/instance-settings#automatic-storage-increase-2ndgen)).

**Comment by marcoderama** [comment]
Thank you.  That answers my questions.
