### ISSUE TITLE
Add Bigquery Subscription to pubsub

### ISSUE THREAD

**Issue by YogenRaii** [GoogleCloudPlatform/k8s-config-connector#694]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Terraform support has been added for BigQuery subscription https://cloud.google.com/pubsub/docs/bigquery with https://github.com/GoogleCloudPlatform/magic-modules/pull/6346

We need to have support for this in kcc as well

**Comment by mbzomowski** [comment]
Hi @YogenRaii, this change will be pulled in when we next update our Terraform provider (likely next week), and should be included in the next release after that.

**Comment by YogenRaii** [comment]
thank you @mbzomowski

**Comment by mbzomowski** [comment]
@YogenRaii correction - we won't be updating our Terraform provider this week. We should be updating it two weeks from now, so this change will be included in our release 3 weeks from now.

**Comment by YogenRaii** [comment]
ok, thank you for keeping posted on this!

**Comment by YogenRaii** [comment]
@mbzomowski any update on this?

**Comment by YogenRaii** [comment]
oh i see it has been pulled yesterday! https://github.com/GoogleCloudPlatform/k8s-config-connector/commit/c825e459d93a6fe63f39c822e1a438cd45439b69#diff-378ad2756f5b27217c23c40a855ed6e0299804753429474f54a011909067f8ea

thank you

**Comment by mbzomowski** [comment]
You're welcome!
