### ISSUE TITLE
Support DataFlowJob resource

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#70]
Multiple customers requested [DataFlowJob](https://cloud.google.com/dataflow/) resource and I'm starting this issue to ensure that requirements are captured correctly and providing a place of comments, updates and questions.

Implementation proposed:

1. Consistent with how other resources are implemented, we will wrap CRD of DataFlowJob from Terraform's [google_dataflow_job](https://www.terraform.io/docs/providers/google/r/dataflow_job.html) and will support the same properties and deletion behavior (canceled or drained).
1. The job that reaches terminal state (`FAILED`, `COMPLETE`, `CANCELLED`) can either be automatically recreated that is expected for continuous jobs or stopped that is expected for one-time jobs. There's still a decision to be made whether we will decide on one of these approaches or provide a way for customer to configure it.

**Comment by morgante** [comment]
Note that the REST API seems to expose a [job_type option](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs#jobtype) which Terraform does not. I'd think we should consider adding support for this, as it covers the two different main DataFlow scenarios.

**Comment by jcanseco** [comment]
Hi all, we have an update/proposal on what support for Dataflow Jobs is going to look like in #84. Let us move our discussion (including feedback and suggestions) over there.

**Comment by jcanseco** [comment]
@morgante: To answer your question: yes, we can expose a `jobType` field.
