### ISSUE TITLE
GCS Bucket interoperability HMAC keys for Service Account

### ISSUE THREAD

**Issue by dkulchinsky** [GoogleCloudPlatform/k8s-config-connector#721]
### Describe your question

Hello folks,

We're trying to figure out if it's possible to generate GCS bucket interoperability HMAC keys for Service Account using the Config Connector, similarly to how this is implemented in Terraform (https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_storage_hmac_key.go)

We couldn't find any reference to it, but wanted to double check and if not possible at the moment perhaps this can be considered as an enhancement.

**Comment by jcanseco** [comment]
Thanks for the qustion @dkulchinsky. Doesn't seem like we support this. I added a resource request in our backlog.

**Comment by mdtoro-wyn** [comment]
Hi Guys, 
Any progress on this?

**Comment by diviner524** [comment]
It is available as a v1alpha1 (preview) CRD.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/storage_v1alpha1_storagehmackey.yaml

For instructions on how to install and manage these v1alpha1 CRDs:

https://cloud.google.com/config-connector/docs/how-to/install-alpha-crds
