### ISSUE TITLE
"gcloud beta services identity create" analogue

### ISSUE THREAD

**Issue by sthomson-wyn** [GoogleCloudPlatform/k8s-config-connector#728]
### Describe your question

Is there an analogue to https://cloud.google.com/sdk/gcloud/reference/beta/services/identity/create?

Example: enabling multiclustermetering.googleapis.com is not sufficient in triggering the creation of the service-{proj-number}@gcp-sa-mcmetering.iam.gserviceaccount.com service account

Though it can be triggered by running

gcloud beta services identity create --service multiclustermetering.googleapis.com --project=my-project-id

Is there an analogue for achieving this in config connector?

**Comment by maqiuyujoyce** [comment]
Hi @sthomson-wyn , thank you for question and the context. Right now, this resource (or a similar feature) is not yet supported in Config Connector. We've added it to the list of resources we're looking into and will let you know when we have more information.
Please reach out to us via Cloud support to prioritize your request if it is a blocker.

**Comment by mbzomowski** [comment]
This resource was added in KCC [v1.100.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.100.0).
