### ISSUE TITLE
Sample Apps: CNRM prerequisite

### ISSUE THREAD

**Issue by ferraricharles** [GoogleCloudPlatform/k8s-config-connector#73]
I'm wondering if the CNRM prerequisite and the cnrm init command could have a further explanation as there is no link to such documentation/software.

**Comment by maqiuyujoyce** [comment]
Hi @ferraricharles, thank you for bringing up the problem. Please follow [Config Connector Getting Started doc](https://cloud.google.com/config-connector/docs/how-to/getting-started) to install and use Config Connector. You should be able to use the sample apps after the installation.

**Comment by kibbles-n-bytes** [comment]
We have now removed references to the stale `cnrm` CLI from our sample apps; closing out this issue.
