### ISSUE TITLE
New API: Cloud Run jobs

### ISSUE THREAD

**Issue by errordeveloper** [GoogleCloudPlatform/k8s-config-connector#732]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Config Connector already supports Cloud Run Services, it would be really great if it had support for Cloud Run Jobs also.

### Importance

This is blocking a new project.

**Comment by maqiuyujoyce** [comment]
Hi @rafaeltello , do you happen to have any idea if there is a plan for supporting Cloud Run Job resource in Config Connector?

**Comment by rafaeltello** [comment]
Hi @errordeveloper! Thanks for your interest in Cloud Run Jobs! I can confirm supporting Cloud Run Job resources is in our roadmap, but we don't have a timeline yet. We understand it's a blocker for your project: filing a ticket via Cloud support would help us prioritize this internally.

**Comment by red8888** [comment]
@rafaeltello Your saying I can open a GCP support request merely stating I really want this feature and that would be helpful? 

Also, is there a public feature request for this I can start to show my interest as well? Thanks!

**Comment by urmet** [comment]
according to changelogs RunJob resource support has been added in [1.106.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.106.0), so this issue can be closed now

**Comment by errordeveloper** [comment]
@rafaeltello could you please confirm?

**Comment by urmet** [comment]
docs are there with all the other resources :)
https://cloud.google.com/config-connector/docs/reference/resource-docs/run/runjob

**Comment by errordeveloper** [comment]
@urmet ah, thanks a lot, I'm now convinced this is a real thing!
