### ISSUE TITLE
sqlServerUserDetails.serverRoles accepted values

### ISSUE THREAD

**Issue by esn89** [GoogleCloudPlatform/k8s-config-connector#734]
### Describe your question

The documentation doesn't mention what these values are.

I am not sure what to pass in here.  What are some of the accepted values and where can I check it?

**Comment by mbzomowski** [comment]
Hi @esn89 - `sqlServerUserDetails` is actually a read-only field and this will be addressed in our documentation with the next Config Connector release. Additionally, this field will be moved under `status` instead of `spec` in the SQLUser CRD.
