### ISSUE TITLE
Add support for BigQuery routines

### ISSUE THREAD

**Issue by erik-carlson** [GoogleCloudPlatform/k8s-config-connector#739]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Add config connector support for BigQuery routines to be able to create/manage procedures.

### Additional information

Terraform supports routines: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_routine

### Importance

Today we can manage datasets and tables via config connector but then need to have a separate process for managing routines. It would be nice to be able to manage the routines in the same way as other BQ resources.

**Comment by diviner524** [comment]
@erik-carlson 

Thank you for your suggestion. BigQuery routines is already in the list of resources we are planning to support. We will let you know when we have more information.

Please reach out to us via Cloud support to prioritize your request if it is a blocker.

**Comment by mbzomowski** [comment]
This resource was added in KCC [v1.100.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.100.0).
