### ISSUE TITLE
StorageBucket AutoClass support?

### ISSUE THREAD

**Issue by markrandall** [GoogleCloudPlatform/k8s-config-connector#742]
### Describe your question

The StorageBucket documentation: https://cloud.google.com/config-connector/docs/reference/resource-docs/storage/storagebucket specifies:

> The Storage Class of the new bucket. Supported values include: STANDARD, MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE.

However I wish to have buckets created using the autoclass storage system (https://cloud.google.com/storage/docs/autoclass).

I took a punt at using AUTOCLASS in the `storageClass` field but unsurprisingly it failed.

Is specifying autoclass via config connector a supported mechanism, and if not are there plans to make it so?

**Comment by mbzomowski** [comment]
Hi @markrandall - we use Terraform to interact with the GCP APIs, so we require that fields be added there first. It looks like Terraform added `AUTOCLASS` in their [last release](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.46.0), so we'll probably have this feature out for Config Connector by the end of January.

**Comment by maqiuyujoyce** [comment]
Released in [v1.99.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.99.0)
