### ISSUE TITLE
SQLInstance should support Instance Termination Protection

### ISSUE THREAD

**Issue by jmymy** [GoogleCloudPlatform/k8s-config-connector#748]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Hello, The terraform provider supports instance termination protection for SQL instances. Would like to have that as an option in the schema for SQLinstance.

### Additional information

gcloud sql instances patch [INSTANCE_NAME] \
    --deletion-protection
    
    

### Importance

Very important as it allows accidental deletion of this resource to completely wipe out all data and backups associated

**Comment by mbzomowski** [comment]
`spec.settings.deletionProtectionEnabled` was added to `SQLInstance` in KCC [v1.100.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.100.0).
