### ISSUE TITLE
Examples of creating a resource in another project

### ISSUE THREAD

**Issue by themanifold** [GoogleCloudPlatform/k8s-config-connector#75]
Hello,

The [docs](https://cloud.google.com/config-connector/docs/how-to/managing-multiple-projects) claim that you can create resources in another project and tell you how to set up the GCP IAM, but I cannot find any examples. Please can you show me an example, or point to some docs I am missing?

Thanks

**Comment by xiaobaitusi** [comment]
In this [doc](https://cloud.google.com/config-connector/docs/how-to/setting-default-namespace), it describes how to annotate a namespace with 'cnrm.cloud.google.com/project-id=[PROJECT_ID]'. 
Once the namespace is annotated with project id, resources that created in the namespace will be provisioned by KCC in the mapped project assuming that it has the appropriate permission. Let us know if you have more questions.

**Comment by themanifold** [comment]
@xiaobaitusi So there is no way of administering two projects from the same namespace?

**Comment by kibbles-n-bytes** [comment]
@themanifold We are currently in the process of documenting some new functionality for 1.0.0; with 1.0.0-rc1, you can use the `cnrm.cloud.google.com/project-id` annotation on individual resources as a resource-level override to the namespace mapping. We'll have more examples and details in the coming couple weeks.

**Comment by toumorokoshi** [comment]
This is now live! see https://cloud.google.com/config-connector/docs/how-to/organizing-resources/overview.
