### ISSUE TITLE
Is it possible to restrict CRDs installed/controllers started?

### ISSUE THREAD

**Issue by snuggie12** [GoogleCloudPlatform/k8s-config-connector#759]
### Describe your question

Having so many CRDs messes with kubernetes clients and their burst cache. If you only use a dozen or so CRDs the additional 100+ only hurt the cluster.

Is there a way to restrict which CRDs are installed and shut off the controllers trying to do reconciliation?

**Comment by diviner524** [comment]
@snuggie12 This is not supported today, but we are definitely considering similar features.

**Comment by maqiuyujoyce** [comment]
Hi @snuggie12 , thank you for your feedback! I think this is similar with what was discussed in #650. I'll close this issue and let's continue discussing in #650 instead.

Feel free to reopen if needed.
