### ISSUE TITLE
Support Cloud Run probes in Config Connector

### ISSUE THREAD

**Issue by knowhoper** [GoogleCloudPlatform/k8s-config-connector#778]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Hi,

None of the probes supported by CloudRun are supported by your Cloud Run template. These are crucial to our HA architecture as we move from GKE to CR. Do you have these on your roadmap? Currently we are using YAML deployments and `gcloud` to get around this gap, but it means our CI/CD is no longer homogeneous.

Thanks and best.
K

### Additional information

https://cloud.google.com/run/docs/configuring/healthchecks

### Importance

High. This is a significant gap.

**Comment by diviner524** [comment]
@rafaeltello this seems to be a CloudRun specific feature request, could you help on the question? Thanks!

**Comment by knowhoper** [comment]
Hi, has there been any progress on this work? This is getting quite urgent for us now. We cant contribute to this repo and our  deployment pipelines are diverging to support this now in services requiring HA.

**Comment by diviner524** [comment]
@knowhoper The Google Cloud Run team is working on this. It is a bit complicated as this current CRD is based on DCL [1] [2], and they are trying to migrate this CRD to become Terraform based which might take some time.

If this is time-sensitive, please create a GCP support case and we can help to route to Cloud Run team to get an ETA.

[1] https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/run_v1beta1_runservice.yaml#L22
[2] https://github.com/GoogleCloudPlatform/declarative-resource-client-library

**Comment by newtondev** [comment]
This seems to be implemented in the latest version of KCC (v1.111.0).

Now a Terraform resource:
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/c08e4c866df4f249e7b083144313312cd7491dc3/crds/run_v1beta1_runservice.yaml#L25C27-L25C33

Startup probe:
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/c08e4c866df4f249e7b083144313312cd7491dc3/crds/run_v1beta1_runservice.yaml#L440 

Liveness probe: 
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/c08e4c866df4f249e7b083144313312cd7491dc3/crds/run_v1beta1_runservice.yaml#L322

**Comment by diviner524** [comment]
Yes, we have completed the migration of Cloud Run from DCL based implementation to Terraform based, with more supported fields in Cloud Run. Thanks for sharing all the pointers @newtondev!
