### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by knowhoper** [GoogleCloudPlatform/k8s-config-connector#785]
### Describe your question

Hi, Is there a basic guide on how to extend config connector - other than running the local build which working fine. It would be useful to know how to add a basic field to a CRD, the specific file(s) to update and any supporting requirements. There are unsupported GCP features i would like to implement in a fork. 

Cheers
KH

**Comment by knowhoper** [comment]
Hi @diviner524 thank you for your response, could you perhaps answer one question for me, which would help me massively in lieu of the above:

When i makes changes to the CRDs located in either `crd` or the `install-bundles` directories, these changes are not propagated to the generated manifests when I run `make manifests`. Why is this? Can you help with this?

**Comment by diviner524** [comment]
@knowhoper Sure, it really depends on which CRD you are trying to update, and there are quite a few concepts/steps involved. As mentioned we are trying to get these better documented.

Most CRDs in Config Connector are generated programmatically, which means we don't make changes to the CRDs directly. For example, if the CRD is based on a Terraform resource, we will generate the CRD based on the corresponding [TF schema](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/pkg/crd/crdgeneration/tf2crdgeneration.go#L37). So usually you will only see CRD fields added/updated when a new version of Terraform provider is integrated with Config Connector.

There are indeed situations we may need to patch certain CRDs on top of the auto-generated schema, for various reasons. But it is not that common and is done differently.

**Comment by knowhoper** [comment]
I see. The resource I am interested in is the RunService. This has readiness and liveness probes, which are supported by the Terraform provider in the [samples](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/scripts/resource-autogen/generated/samples/CloudRunV2-CloudRunV2Service-cloudrunv2_service_probes/main.tf), however they don't materialise in the RunService CRD.

This is crucial for us maintaining HA in CR. Thanks for your reply, much appreciated as would be further guidance.

**Comment by diviner524** [comment]
@knowhoper Thanks for sharing. If this is a blocking issue for you, please consider submit a corresponding issue with [GCP support](https://cloud.google.com/support-hub) so we can better prioritize.

AFAIK we are working on updating this CRD but it might take some time. Also @rafaeltello FYI.

**Comment by knowhoper** [comment]
Thanks!
