### ISSUE TITLE
As of 1.101.0, some struct members have changed type

### ISSUE THREAD

**Issue by mistydemeo** [GoogleCloudPlatform/k8s-config-connector#791]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

As of 1.101.0, several struct fields changed type from `string` to `*string`. This was introduced in 646b25a7e42f85ae8def46357bc7d2efaaf7a1a3; for example, this field: https://github.com/GoogleCloudPlatform/k8s-config-connector/commit/646b25a7e42f85ae8def46357bc7d2efaaf7a1a3#diff-3c70332db0c503d3adea1c6bc56a2d486c8e143bea09161382136fc5928b100aL469-R454

This change went unmentioned in the release notes, and the commit only mentions a change in the method used to generate the code, not any intended changes to the code itself.

### Additional Diagnostic Information

N/A

### Kubernetes Cluster Version

N/A

### Config Connector Version

N/A

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Reference these types in code:

```go
if obj.Status.CurrentStatus == "RUNNING" {}
```

In 1.100.0 and older, this works. In 1.101.0, the compiler complains:

```
invalid operation: cannot compare obj.Status.CurrentStatus == "RUNNING" (mismatched types *string and untyped string)
```

**Comment by diviner524** [comment]
@mistydemeo Apologize, we overlooked this change when compiling our release notes. I have updated release note for 1.101.0 to include the change.

Also please note the Config Connector Go client is still in ALPHA, which means that future versions of the go-client may include other breaking changes.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/pkg/clients/generated/apis/accesscontextmanager/group.go#L26

**Comment by mistydemeo** [comment]
Thanks for updating the documentation. That makes sense - I understand the API might change while it's still in alpha!

**Comment by diviner524** [comment]
Feel free to re-open or create new issues if you have questions related to the Go client.
