### ISSUE TITLE
Config Connector on GKE Autopilot throws errors with admission webhooks

### ISSUE THREAD

**Issue by knowhoper** [GoogleCloudPlatform/k8s-config-connector#794]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Hi, i use KCC extensively in my organisation. We are a small engineering team, very cloud focused, and KCC allows us to give our engineers freedom to provision infrastructure without moving too far away from tools they are used to. This product is awesome. 

We've recently switched to AutoPilot. We use ArgoCD to manage the CC installation and sync all our entities. AutoPilot (i know this isn't support OOTB appears to be working fine except one small sync issues).  Here are the logs from the controller.

> {"severity":"error","timestamp":"2023-03-27T23:38:16.810Z","msg":"applying manifest","error":"error when creating \"manifestString\": admission webhook \"gkepolicy.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-disallow-hostnamespaces]\":[\"enabling hostNetwork is not allowed in Autopilot.\"],\"[denied by autogke-no-host-port]\":[\"container recorder specifies host ports [48797 23232], which are disallowed in Autopilot.\"]}\nRequested by user: 'system:serviceaccount:configconnector-operator-system:configconnector-operator', groups: 'system:serviceaccounts,system:serviceaccounts:configconnector-operator-system,system:authenticated'."}
> 
> {"severity":"error","timestamp":"2023-03-27T23:38:16.830Z","logger":"controller.configconnector-controller","msg":"Reconciler error","reconciler group":"core.cnrm.cloud.google.com","reconciler kind":"ConfigConnector","name":"configconnector.core.cnrm.cloud.google.com","namespace":"","error":"error applying manifest: error when creating \"manifestString\": admission webhook \"gkepolicy.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-disallow-hostnamespaces]\":[\"enabling hostNetwork is not allowed in Autopilot.\"],\"[denied by autogke-no-host-port]\":[\"container recorder specifies host ports [48797 23232], which are disallowed in Autopilot.\"]}\nRequested by user: 'system:serviceaccount:configconnector-operator-system:configconnector-operator', groups: 'system:serviceaccounts,system:serviceaccounts:configconnector-operator-system,system:authenticated'."}

I understand why this restriction is in place, is there a way i can apply policies to the cluster to remove this? Our clusters are private and low risk so relaxing security within system namespaces is not something I would worry too much about. I dont want to move away from KCC as its the centrepoint of our DevOps stack, but I also dont want to manage GKE nodes.

Any guidance would be much appreciated. 

CHeers

### Additional Diagnostic Information

{"severity":"error","timestamp":"2023-03-27T23:38:16.810Z","msg":"applying manifest","error":"error when creating \"manifestString\": admission webhook \"gkepolicy.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-disallow-hostnamespaces]\":[\"enabling hostNetwork is not allowed in Autopilot.\"],\"[denied by autogke-no-host-port]\":[\"container recorder specifies host ports [48797 23232], which are disallowed in Autopilot.\"]}\nRequested by user: 'system:serviceaccount:configconnector-operator-system:configconnector-operator', groups: 'system:serviceaccounts,system:serviceaccounts:configconnector-operator-system,system:authenticated'."}

{"severity":"error","timestamp":"2023-03-27T23:38:16.830Z","logger":"controller.configconnector-controller","msg":"Reconciler error","reconciler group":"core.cnrm.cloud.google.com","reconciler kind":"ConfigConnector","name":"configconnector.core.cnrm.cloud.google.com","namespace":"","error":"error applying manifest: error when creating \"manifestString\": admission webhook \"gkepolicy.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-disallow-hostnamespaces]\":[\"enabling hostNetwork is not allowed in Autopilot.\"],\"[denied by autogke-no-host-port]\":[\"container recorder specifies host ports [48797 23232], which are disallowed in Autopilot.\"]}\nRequested by user: 'system:serviceaccount:configconnector-operator-system:configconnector-operator', groups: 'system:serviceaccounts,system:serviceaccounts:configconnector-operator-system,system:authenticated'."}

### Kubernetes Cluster Version

1.24.9-gke.3200

### Config Connector Version

1.101.0

### Config Connector Mode

namespaced mode (default)

### Log Output

{"severity":"error","timestamp":"2023-03-27T23:38:16.810Z","msg":"applying manifest","error":"error when creating \"manifestString\": admission webhook \"gkepolicy.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-disallow-hostnamespaces]\":[\"enabling hostNetwork is not allowed in Autopilot.\"],\"[denied by autogke-no-host-port]\":[\"container recorder specifies host ports [48797 23232], which are disallowed in Autopilot.\"]}\nRequested by user: 'system:serviceaccount:configconnector-operator-system:configconnector-operator', groups: 'system:serviceaccounts,system:serviceaccounts:configconnector-operator-system,system:authenticated'."}

{"severity":"error","timestamp":"2023-03-27T23:38:16.830Z","logger":"controller.configconnector-controller","msg":"Reconciler error","reconciler group":"core.cnrm.cloud.google.com","reconciler kind":"ConfigConnector","name":"configconnector.core.cnrm.cloud.google.com","namespace":"","error":"error applying manifest: error when creating \"manifestString\": admission webhook \"gkepolicy.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-disallow-hostnamespaces]\":[\"enabling hostNetwork is not allowed in Autopilot.\"],\"[denied by autogke-no-host-port]\":[\"container recorder specifies host ports [48797 23232], which are disallowed in Autopilot.\"]}\nRequested by user: 'system:serviceaccount:configconnector-operator-system:configconnector-operator', groups: 'system:serviceaccounts,system:serviceaccounts:configconnector-operator-system,system:authenticated'."}

### Steps to reproduce the issue

Install CC one a GKE autopilot cluster.

**Comment by diviner524** [comment]
@knowhoper Thank you for sharing your user scenario! 

Yes we are aware of this limitation and actually we plan to support Config Connector on GKE Autopilot in our next release as an opt-in feature with some limitations. (As you can imagine, we will need to disable the `recorder` container to make Config Connector work on Autopilot, which means you will lose certain prometheus metrics.)

We will add more documentation once the release is done, to explain how this new feature can be enabled. Also @cheftako who is currently working on this new feature.

**Comment by knowhoper** [comment]
Excellent, thanks for the update!
