### ISSUE TITLE
Not able to create VertexAI endpoint.  

### ISSUE THREAD

**Issue by kishor-bestbuy** [GoogleCloudPlatform/k8s-config-connector#812]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Vertex AI Endpoint is getting created but it is going into failed state.
error :- Update call failed: error fetching live state: error reading underlying resource: summary: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

Configuration does not accept region filed, I have passed location.

crd-to-sample-yaml a187671$ cat vertexendpointcrt.yaml
apiVersion: vertexai.cnrm.cloud.google.com/v1alpha1
kind: VertexAIEndpoint
metadata:
  name: vertexaiendpointscrd
spec:
  description: index_endpointcrd
  displayName: index_endpointcrd
  location: us-central1
  network: projects/*****/global/networks/bby-net1
  projectRef:
    external: ****

### Additional Diagnostic Information

There is no attribute for region. 

### Kubernetes Cluster Version

1.24

### Config Connector Version

1.103.0 release

### Config Connector Mode

namespaced mode (default)

### Log Output

Status:
  Conditions:
    Last Transition Time:  2023-05-05T20:21:16Z
    Message:               Update call failed: error fetching live state: error reading underlying resource: summary: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
    Reason:                UpdateFailed
    Status:                False
    Type:                  Ready
  Observed Generation:     1
Events:
  Type     Reason        Age                 From                         Message
  ----     ------        ----                ----                         -------
  Warning  UpdateFailed  87s (x29 over 47m)  vertexaiendpoint-controller  Update call failed: error fetching live state: error reading underlying resource: summary: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

### Steps to reproduce the issue

Apply below yaml. 

crd-to-sample-yaml a187671$ cat vertexendpointcrt.yaml
apiVersion: vertexai.cnrm.cloud.google.com/v1alpha1
kind: VertexAIEndpoint
metadata:
  name: vertexaiendpointscrd
spec:
  description: index_endpointcrd
  displayName: index_endpointcrd
  location: us-central1
  network: projects/*****/global/networks/bby-net1
  projectRef:
    external: ****

**Comment by diviner524** [comment]
This seems to be the same issue as discussed in https://github.com/hashicorp/terraform-provider-google/issues/12944

We should be able to fix this in future release after the region field is introduced in the CRD.

**Comment by newtondev** [comment]
The reference issue on https://github.com/hashicorp/terraform-provider-google/issues/12944 is marked as closed and I see a few merge requests that were merged.

@diviner524, is this something I could possibly pick up and work on?

**Comment by diviner524** [comment]
@newtondev I see the region field is already added in the CRD, so the issue might have already been fixed through a previous Terraform provider update in Config Connector.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/vertexai_v1alpha1_vertexaiendpoint.yaml#L137

Are you still seeing error in this resource using the latest version of Config Connector?

Note this is a preview CRD (v1alpha1) and we have instructions here on how to use them.

https://cloud.google.com/config-connector/docs/how-to/install-alpha-crds

**Comment by newtondev** [comment]
@diviner524 I am not seeing this error in the latest version (1.111.0) and can set the region on the CR.

**Comment by diviner524** [comment]
Thanks for confirming @newtondev!

**Comment by kishor-bestbuy** [comment]
Thanks for the update, this is working as expected.
