### ISSUE TITLE
Add support for Vertex AI Index Endpoints

### ISSUE THREAD

**Issue by erik-carlson** [GoogleCloudPlatform/k8s-config-connector#819]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Terraform support for Vertex AI Index Endpoints is available with the merge of this PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/6873

I'm not sure if this would get pulled in automatically as an auto-generated CRD or not, but if not we would like support in KCC for this resource.

### Importance

nice to have as indexes are supported but require an endpoint to access them.

**Comment by diviner524** [comment]
@erik-carlson Yes, this will be automatically generated as a new v1alpha1 CRD. 

It shouldn't take very long, but we do not have a specific ETA. We are discussing the frequency of updates for auto-generation and exploring ways to collaborate with external contributors to enhance the usefulness of these CRDs.

**Comment by erik-carlson** [comment]
For others finding this issue, VertexAIIndexEndpoint v1alpha1 was added in version 1.109.0.
