### ISSUE TITLE
Cloud Build Triggers support

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/k8s-config-connector#82]
We would like to be able to create and manage triggers with cloud connector, specifically GitHub app triggers.

cc @whizard

**Comment by caieo** [comment]
Hi @derekperkins , thanks for bringing this up -- it would definitely help to have this and we're aiming to have this supported in the following weeks.

**Comment by jcanseco** [comment]
Hi @derekperkins, thanks for waiting. We've just added support for the `CloudBuildTrigger` resource in Config Connector `v1.7.0`.

This particular [sample](https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/resources/cloudbuildtrigger/build-trigger-for-github-repo) demonstrates how to create and manage GitHub app triggers with Config Connector.

**Comment by derekperkins** [comment]
Great, thanks!
