### ISSUE TITLE
Is GDCE supported?

### ISSUE THREAD

**Issue by philippart** [GoogleCloudPlatform/k8s-config-connector#834]
I would like to use config connector to manage GDCE clusters and networking, essentially the equivalent of `gcloud edge-cloud ...` commands. Is this already supported with the current GKE cluster, nodepools and compute networks, or new dedicated resources will be created in the future?

Thank you.

**Comment by diviner524** [comment]
@philippart New resources in Config Connector will be based on Terraform provider. It seems the resource you are looking for is not in Terraform Google Provider [1], then we will need to wait until it is supported before adding it into Config Connector.

[1] https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources
