### ISSUE TITLE
Do not use doc region tags

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/k8s-config-connector#836]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

This repo should not be copying region tags from sample code ([go/code-snippets-101#region-tag](https://goto.google.com/code-snippets-101#region-tag)). Region tags have been found for GCF samples in generated tests, https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/a87ba386fc05af7d03d2b03aa534bc6ac52809d1/third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/iam_cloudfunctions2_function_generated_test.go, and samples, https://github.com/search?q=repo%3AGoogleCloudPlatform%2Fk8s-config-connector+%22%23+%5BSTART%22+path%3Ascripts%2F&type=code. This is breaking DevRel services ability to disambiguate samples and adding inappropriate samples to the official docs https://cloud.google.com/functions/docs/samples/functions-v2-basic.

### Additional Diagnostic Information

NA

### Kubernetes Cluster Version

NA

### Config Connector Version

NA

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Do not copy over region tags `[START ...]` and `[END ..]` from https://github.com/terraform-google-modules/terraform-docs-samples

**Comment by diviner524** [comment]
@averikitsch This repo does not copy from https://github.com/terraform-google-modules/terraform-docs-samples, instead it is depending on [terraform-provider-google-beta](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/iam_cloudfunctions2_function_generated_test.go) thus copying over the files from that repo.

If you can update/remove the relevant files in [terraform-provider-google-beta](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/iam_cloudfunctions2_function_generated_test.go) then the corresponding tags in this repo will be gone.

**Comment by averikitsch** [comment]
Thank you @diviner524

**Comment by diviner524** [comment]
Closing the issue. Let us know if you need any further help!

**Comment by averikitsch** [comment]
@diviner524 Do you have a time estimate on when I can expect the automation to remove the region tags now that they have been removed (https://github.com/hashicorp/terraform-provider-google-beta/pull/5879)?

**Comment by diviner524** [comment]
It will be our next Terraform update, which should happen around mid August.
