### ISSUE TITLE
ControllerManager resource customization for namespaced scope

### ISSUE THREAD

**Issue by vitalii-buchyn-exa** [GoogleCloudPlatform/k8s-config-connector#842]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Hello community,

We are trying to use resource customization for a ControllerManager in config connector namespaced mode.
But we're getting error `"resource customization failed for the following containers because there are no matching containers in the manifest: manager"`
We can see that currently resource customization is implemented for a cluster scope https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/v1.106.0/operator/pkg/controllers/utils.go#L145C48-L173

It would be nice to have that feature for a namespaced scope in the nearest future.

Thank you.

**Comment by diviner524** [comment]
This is added in [v1.108.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.108.0)
