### ISSUE TITLE
Adding conditionPrometheusQueryLanguage support to MonitoringAlertPolicy

### ISSUE THREAD

**Issue by ronan-fitzgerald-zoe** [GoogleCloudPlatform/k8s-config-connector#847]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

GCP have recently added PromQL support to alerting policies, this is a request to support this via ConfigConnector.

This requires some additional fields to be added as per https://cloud.google.com/monitoring/promql/promql-in-alerting#field-conversion

### Additional information

https://cloud.google.com/monitoring/promql/promql-in-alerting#field-conversion
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies/create

### Importance

It would be great to see these added to ConfigConnector, as we are currently migrating away from MonitoringAlertPolicy resources using MQL to Google Managed Prometheus rules with PromQL, and we have currently accepted the risk of running our rule evaluation and alert management systems in a semi-managed way, but we would much prefer a fully managed solution like Google's Alert Policy system if we could easily decentralise the config.

**Comment by griseau** [comment]
That would be very nice to have indeed !

**Comment by burnjake** [comment]
Promising [commit](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/5806f65433ffd474543aeba95063f6acf8e4f1b1/pkg/clients/generated/apis/monitoring/v1beta1/monitoringalertpolicy_types.go#L240) from yesterday 👀

**Comment by griseau** [comment]
Now available :) https://cloud.google.com/config-connector/docs/reference/resource-docs/monitoring/monitoringalertpolicy

**Comment by diviner524** [comment]
This is released in [v1.109.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.109.0).
