### ISSUE TITLE
Support for Cloud SQL client certificates

### ISSUE THREAD

**Issue by jroper** [GoogleCloudPlatform/k8s-config-connector#91]
Config connector doesn't (as far as I can see) support creating SQL client certificates, ie as described here:

https://cloud.google.com/sql/docs/postgres/configure-ssl-instance#client-certs

Ideally, this would be managed by adding a secret (or list of secrets) that client certificates should be created and stored in. Even better, the config connector should automatically rotate them as they get close to expiring.

**Comment by maqiuyujoyce** [comment]
Hi @jroper, thank you for your suggestion. We've added Cloud SQL SSL Cert into the list of resources we're looking into and will let you know when we have more information.

**Comment by maqiuyujoyce** [comment]
Now it is supported in KCC v1.11.0.
