### ISSUE TITLE
How can we customize the crnm-controller-manager statefulset or control the CRDs deployed?

### ISSUE THREAD

**Issue by ericduranddd** [GoogleCloudPlatform/k8s-config-connector#914]
### Describe your question

I have checked and did not find a way to do this in the documentation.
Basically we'd need to do 2 things:
. Add a sidecar container to the crnm-controller-manager statefulset defined there: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/operator/channels/packages/configconnector/1.110.0/cluster/gcp-identity/0-cnrm-system.yaml
. Avoid to deploy the full list of CRDs that come from here: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/operator/channels/packages/configconnector/1.110.0/crds.yaml
I don't see how we can do this apart from building our own image of the operator, is there any other way that you'd suggest?
Thanks
Eric

**Comment by diviner524** [comment]
@ericduranddd 

* Regarding the first issue (sidecar container), it appears challenging to accommodate this within the predefined statefulset. The `configconnector-operator` ships with a default statefulset configuration for `crnm-controller-manager` and will correct any detected deviations.

* Regarding the second issue, we've been receiving similar requests from other users, and we do indeed have plans to introduce similar features. However, we don't have a specific timeframe for this implementation at the moment.

@jingyih FYI.

**Comment by ericduranddd** [comment]
thanks!
