### ISSUE TITLE
SourceRepository and CloudBuild Support

### ISSUE THREAD

**Issue by kewei5zhang** [GoogleCloudPlatform/k8s-config-connector#95]
Our team would love to choose KCC over Terraform, but sourcerepository and cloudbuild resources are required for our cluster 0 provisioning activity. Would those two resources get supported anytime soon?

**Comment by maqiuyujoyce** [comment]
Hi @kewei5zhang thank you for your suggestion. We've added them to the list of resources we're
looking into and will let you know when we have more information.

**Comment by kewei5zhang** [comment]
Thanks @maqiuyujoyce. Is there any ETA you could kindly suggest? This will be helpful for our decision making.

**Comment by kibbles-n-bytes** [comment]
Hey @kewei5zhang , currently we're conservatively estimating April for Cloud Source Repository repo support, and summer for Cloud Build triggers. If you're interested in pre-release support for these features, and so we can better understand your use case, please contact our team through your customer representative.

**Comment by jcanseco** [comment]
Hi @kewei5zhang, thanks for waiting. We've just added support for the `SourceRepoRepository` and `CloudBuildTrigger` resources in Config Connector `v1.7.0`.
