### ISSUE TITLE
Creation of DNSManagedZone fails silently if `visibility` is not specified

### ISSUE THREAD

**Issue by ssmall** [GoogleCloudPlatform/k8s-config-connector#97]
`kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

# Steps to Reproduce
1. Install Config Connector using Workload Identity per [guide](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall)
2. Apply the following YAML using `kubectl apply -f`:
```yaml
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: my-dns-zone
spec:
  dnsName: "example.com."
```

*NOTE:* This doesn't actually work with `example.com.` -- you will need to substitute a domain that you actually own to avoid errors creating the managed zone.

# Expected Behavior
Running `kubectl get dnsmanagedzone -o json --all-namespaces` shows an entry for `my-dns-zone`

# Actual Behavior
Running `kubectl get dnsmanagedzone -o json --all-namespaces` shows an empty result set

# Workaround
Adding `visibility: public` to the `spec` seems to fix the issue.

**Comment by AlexBulankou** [comment]
@ssmall , thanks for reporting the issue. I cannot reproduce it on the latest Config Connector version (`image: gcr.io/cnrm-eap/controller:b06a1e6`). Creating your example:
```
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: my-dns-zone
spec:
  dnsName: "example.com."
```
and then calling:
```
kubectl get dnsmanagedzone -o json --all-namespaces
```
returns:
```
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "dns.cnrm.cloud.google.com/v1beta1",
            "kind": "DNSManagedZone",
            "metadata": {
                "annotations": {
                    "cnrm.cloud.google.com/management-conflict-prevention-policy": "resource",
                    "cnrm.cloud.google.com/project-id": "default",
                    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"dns.cnrm.cloud.google.com/v1beta1\",\"kind\":\"DNSManagedZone\",\"metadata\":{\"annotations\":{},\"name\":\"my-dns-zone\",\"namespace\":\"default\"},\"spec\":{\"dnsName\":\"example.com.\"}}\n"
                },
                "creationTimestamp": "2020-02-26T14:52:01Z",
                "generation": 2,
                "name": "my-dns-zone",
                "namespace": "default",
                "resourceVersion": "9490",
                "selfLink": "/apis/dns.cnrm.cloud.google.com/v1beta1/namespaces/default/dnsmanagedzones/my-dns-zone",
                "uid": "8b8e6cc4-58a7-11ea-bf47-42010a8000a7"
            },
            "spec": {
                "dnsName": "example.com."
            },
            "status": {
                "conditions": [
                    {
                        "lastTransitionTime": "2020-02-26T14:52:01Z",
                        "message": "Update call failed: error fetching live state: error reading underlying resource: Error reading DNSManagedZone \"projects/default/managedZones/my-dns-zone\": googleapi: Error 403: Permission denied on resource project default., forbidden",
                        "reason": "UpdateFailed",
                        "status": "False",
                        "type": "Ready"
                    }
                ]
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```
The underlying GCP resource creation fails, as expected, because I don't own `example.com`, but Config Connector K8s resources is created as expected and I can query it using kubectl get.
Can you please verify on the latest version of Config Connector?

**Comment by ssmall** [comment]
Yes, running `kubectl get pod/cnrm-controller-manager-0 -n cnrm-system -o yaml` I see

```yaml
spec:
  containers:
    ...
    image: gcr.io/cnrm-eap/controller:b06a1e6
    ...
```

Out of curiosity, are you able to reproduce the issue using a domain that you actually own (**not** `example.com`)? I saw this behavior specifically using my own custom domain that I do own -- I included `example.com` in the issue description for privacy reasons.

**Comment by AlexBulankou** [comment]
@ssmall , thanks for confirming. When K8s `dnsmanagedzone` resource is initially created, there is only K8s API server validation that happens at this point, and not API calls are issued to GCP yet. So whether the account owns the domain wouldn't does impact these initial steps and whether K8s resource is created, they will only impact of subsequent steps to determine whether GCP resource gets provisioned.
If you every come across a situation when attempting to create a Config Connector resource fails, can you capture if `cnrm-controller-manager-0` is reporting anything in the logs (you can launch `kubectl logs cnrm-controller-manager-0 -n cnrm-system -f` in a separate console window while you're running the apply command).

**Comment by kibbles-n-bytes** [comment]
@ssmall When you run `kubectl apply -f`, is the response code 0? And is there any output to the console? The resource must be getting rejected at admission, which means either the schema is malformed or our validating webhooks are blocking it.

**Comment by kibbles-n-bytes** [comment]
Hey @ssmall , I also cannot reproduce the issue. The only reason a resource wouldn't be persisted in etcd is if it failed admission, which does not reach out to GCP and does no validation of domain ownership. The configuration you gave successfully passes admission from my tests. My guess is, during your `kubectl apply -f`, there likely was a non-zero exit code and error message that was missed.

As we have validated Config Connector is working as intended with the given configuration, and haven't gotten an update from you in a while, I'm going to close out this issue. Feel free to open a new issue if you can confirm the `kubectl apply` in step 2 is returning 0 with successful output, and yet the `kubectl get` command still doesn't list anything.
